// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package billingmock

import (
	context "context"
	billing "xata/services/auth/billing"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CountPendingInvoices provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) CountPendingInvoices(ctx context.Context, externalCustomerID string) (int, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CountPendingInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPendingInvoices'
type Client_CountPendingInvoices_Call struct {
	*mock.Call
}

// CountPendingInvoices is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) CountPendingInvoices(ctx interface{}, externalCustomerID interface{}) *Client_CountPendingInvoices_Call {
	return &Client_CountPendingInvoices_Call{Call: _e.mock.On("CountPendingInvoices", ctx, externalCustomerID)}
}

func (_c *Client_CountPendingInvoices_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_CountPendingInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_CountPendingInvoices_Call) Return(_a0 int, _a1 error) *Client_CountPendingInvoices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateCustomer provides a mock function with given fields: ctx, name, email, externalCustomerID, organizationsCount, metadata
func (_m *Client) CreateCustomer(ctx context.Context, name string, email string, externalCustomerID string, organizationsCount int, metadata billing.OrbCustomerMetadata) error {
	ret := _m.Called(ctx, name, email, externalCustomerID, organizationsCount, metadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, billing.OrbCustomerMetadata) error); ok {
		r0 = rf(ctx, name, email, externalCustomerID, organizationsCount, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_CreateCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomer'
type Client_CreateCustomer_Call struct {
	*mock.Call
}

// CreateCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - externalCustomerID string
//   - organizationsCount int
//   - metadata billing.OrbCustomerMetadata
func (_e *Client_Expecter) CreateCustomer(ctx interface{}, name interface{}, email interface{}, externalCustomerID interface{}, organizationsCount interface{}, metadata interface{}) *Client_CreateCustomer_Call {
	return &Client_CreateCustomer_Call{Call: _e.mock.On("CreateCustomer", ctx, name, email, externalCustomerID, organizationsCount, metadata)}
}

func (_c *Client_CreateCustomer_Call) Run(run func(ctx context.Context, name string, email string, externalCustomerID string, organizationsCount int, metadata billing.OrbCustomerMetadata)) *Client_CreateCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int), args[5].(billing.OrbCustomerMetadata))
	})
	return _c
}

func (_c *Client_CreateCustomer_Call) Return(_a0 error) *Client_CreateCustomer_Call {
	_c.Call.Return(_a0)
	return _c
}

// CreateStripeCheckoutSession provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) CreateStripeCheckoutSession(ctx context.Context, externalCustomerID string) (*billing.CheckoutSession, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 *billing.CheckoutSession
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.CheckoutSession); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CheckoutSession)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CreateStripeCheckoutSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStripeCheckoutSession'
type Client_CreateStripeCheckoutSession_Call struct {
	*mock.Call
}

// CreateStripeCheckoutSession is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) CreateStripeCheckoutSession(ctx interface{}, externalCustomerID interface{}) *Client_CreateStripeCheckoutSession_Call {
	return &Client_CreateStripeCheckoutSession_Call{Call: _e.mock.On("CreateStripeCheckoutSession", ctx, externalCustomerID)}
}

func (_c *Client_CreateStripeCheckoutSession_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_CreateStripeCheckoutSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_CreateStripeCheckoutSession_Call) Return(_a0 *billing.CheckoutSession, _a1 error) *Client_CreateStripeCheckoutSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateStripePaymentMethodSession provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) CreateStripePaymentMethodSession(ctx context.Context, externalCustomerID string) (*billing.PaymentMethodSession, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 *billing.PaymentMethodSession
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.PaymentMethodSession); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.PaymentMethodSession)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CreateStripePaymentMethodSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStripePaymentMethodSession'
type Client_CreateStripePaymentMethodSession_Call struct {
	*mock.Call
}

// CreateStripePaymentMethodSession is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) CreateStripePaymentMethodSession(ctx interface{}, externalCustomerID interface{}) *Client_CreateStripePaymentMethodSession_Call {
	return &Client_CreateStripePaymentMethodSession_Call{Call: _e.mock.On("CreateStripePaymentMethodSession", ctx, externalCustomerID)}
}

func (_c *Client_CreateStripePaymentMethodSession_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_CreateStripePaymentMethodSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_CreateStripePaymentMethodSession_Call) Return(_a0 *billing.PaymentMethodSession, _a1 error) *Client_CreateStripePaymentMethodSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CustomerExists provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) CustomerExists(ctx context.Context, externalCustomerID string) (bool, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CustomerExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CustomerExists'
type Client_CustomerExists_Call struct {
	*mock.Call
}

// CustomerExists is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) CustomerExists(ctx interface{}, externalCustomerID interface{}) *Client_CustomerExists_Call {
	return &Client_CustomerExists_Call{Call: _e.mock.On("CustomerExists", ctx, externalCustomerID)}
}

func (_c *Client_CustomerExists_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_CustomerExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_CustomerExists_Call) Return(_a0 bool, _a1 error) *Client_CustomerExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeletePaymentMethod provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) DeletePaymentMethod(ctx context.Context, externalCustomerID string) error {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeletePaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePaymentMethod'
type Client_DeletePaymentMethod_Call struct {
	*mock.Call
}

// DeletePaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) DeletePaymentMethod(ctx interface{}, externalCustomerID interface{}) *Client_DeletePaymentMethod_Call {
	return &Client_DeletePaymentMethod_Call{Call: _e.mock.On("DeletePaymentMethod", ctx, externalCustomerID)}
}

func (_c *Client_DeletePaymentMethod_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_DeletePaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_DeletePaymentMethod_Call) Return(_a0 error) *Client_DeletePaymentMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

// EnsureDefaultPaymentMethod provides a mock function with given fields: ctx, stripeCustomerID, paymentMethodID
func (_m *Client) EnsureDefaultPaymentMethod(ctx context.Context, stripeCustomerID string, paymentMethodID string) error {
	ret := _m.Called(ctx, stripeCustomerID, paymentMethodID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, stripeCustomerID, paymentMethodID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_EnsureDefaultPaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDefaultPaymentMethod'
type Client_EnsureDefaultPaymentMethod_Call struct {
	*mock.Call
}

// EnsureDefaultPaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - stripeCustomerID string
//   - paymentMethodID string
func (_e *Client_Expecter) EnsureDefaultPaymentMethod(ctx interface{}, stripeCustomerID interface{}, paymentMethodID interface{}) *Client_EnsureDefaultPaymentMethod_Call {
	return &Client_EnsureDefaultPaymentMethod_Call{Call: _e.mock.On("EnsureDefaultPaymentMethod", ctx, stripeCustomerID, paymentMethodID)}
}

func (_c *Client_EnsureDefaultPaymentMethod_Call) Run(run func(ctx context.Context, stripeCustomerID string, paymentMethodID string)) *Client_EnsureDefaultPaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_EnsureDefaultPaymentMethod_Call) Return(_a0 error) *Client_EnsureDefaultPaymentMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

// FetchBillingCustomerWithDefaultPaymentMethod provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) FetchBillingCustomerWithDefaultPaymentMethod(ctx context.Context, externalCustomerID string) (*billing.Customer, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 *billing.Customer
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.Customer); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchBillingCustomerWithDefaultPaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBillingCustomerWithDefaultPaymentMethod'
type Client_FetchBillingCustomerWithDefaultPaymentMethod_Call struct {
	*mock.Call
}

// FetchBillingCustomerWithDefaultPaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) FetchBillingCustomerWithDefaultPaymentMethod(ctx interface{}, externalCustomerID interface{}) *Client_FetchBillingCustomerWithDefaultPaymentMethod_Call {
	return &Client_FetchBillingCustomerWithDefaultPaymentMethod_Call{Call: _e.mock.On("FetchBillingCustomerWithDefaultPaymentMethod", ctx, externalCustomerID)}
}

func (_c *Client_FetchBillingCustomerWithDefaultPaymentMethod_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_FetchBillingCustomerWithDefaultPaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchBillingCustomerWithDefaultPaymentMethod_Call) Return(_a0 *billing.Customer, _a1 error) *Client_FetchBillingCustomerWithDefaultPaymentMethod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchCustomer provides a mock function with given fields: ctx, customerID
func (_m *Client) FetchCustomer(ctx context.Context, customerID string) (*billing.Customer, error) {
	ret := _m.Called(ctx, customerID)

	var r0 *billing.Customer
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.Customer); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCustomer'
type Client_FetchCustomer_Call struct {
	*mock.Call
}

// FetchCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *Client_Expecter) FetchCustomer(ctx interface{}, customerID interface{}) *Client_FetchCustomer_Call {
	return &Client_FetchCustomer_Call{Call: _e.mock.On("FetchCustomer", ctx, customerID)}
}

func (_c *Client_FetchCustomer_Call) Run(run func(ctx context.Context, customerID string)) *Client_FetchCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchCustomer_Call) Return(_a0 *billing.Customer, _a1 error) *Client_FetchCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchCustomerByExternalID provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) FetchCustomerByExternalID(ctx context.Context, externalCustomerID string) (*billing.Customer, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 *billing.Customer
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.Customer); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchCustomerByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCustomerByExternalID'
type Client_FetchCustomerByExternalID_Call struct {
	*mock.Call
}

// FetchCustomerByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) FetchCustomerByExternalID(ctx interface{}, externalCustomerID interface{}) *Client_FetchCustomerByExternalID_Call {
	return &Client_FetchCustomerByExternalID_Call{Call: _e.mock.On("FetchCustomerByExternalID", ctx, externalCustomerID)}
}

func (_c *Client_FetchCustomerByExternalID_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_FetchCustomerByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchCustomerByExternalID_Call) Return(_a0 *billing.Customer, _a1 error) *Client_FetchCustomerByExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchInvoice provides a mock function with given fields: ctx, invoiceID
func (_m *Client) FetchInvoice(ctx context.Context, invoiceID string) (*billing.Invoice, error) {
	ret := _m.Called(ctx, invoiceID)

	var r0 *billing.Invoice
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.Invoice); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Invoice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchInvoice'
type Client_FetchInvoice_Call struct {
	*mock.Call
}

// FetchInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID string
func (_e *Client_Expecter) FetchInvoice(ctx interface{}, invoiceID interface{}) *Client_FetchInvoice_Call {
	return &Client_FetchInvoice_Call{Call: _e.mock.On("FetchInvoice", ctx, invoiceID)}
}

func (_c *Client_FetchInvoice_Call) Run(run func(ctx context.Context, invoiceID string)) *Client_FetchInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchInvoice_Call) Return(_a0 *billing.Invoice, _a1 error) *Client_FetchInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchPaymentIntentPaymentMethodID provides a mock function with given fields: ctx, paymentIntentID
func (_m *Client) FetchPaymentIntentPaymentMethodID(ctx context.Context, paymentIntentID string) (string, error) {
	ret := _m.Called(ctx, paymentIntentID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, paymentIntentID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentIntentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchPaymentIntentPaymentMethodID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPaymentIntentPaymentMethodID'
type Client_FetchPaymentIntentPaymentMethodID_Call struct {
	*mock.Call
}

// FetchPaymentIntentPaymentMethodID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentIntentID string
func (_e *Client_Expecter) FetchPaymentIntentPaymentMethodID(ctx interface{}, paymentIntentID interface{}) *Client_FetchPaymentIntentPaymentMethodID_Call {
	return &Client_FetchPaymentIntentPaymentMethodID_Call{Call: _e.mock.On("FetchPaymentIntentPaymentMethodID", ctx, paymentIntentID)}
}

func (_c *Client_FetchPaymentIntentPaymentMethodID_Call) Run(run func(ctx context.Context, paymentIntentID string)) *Client_FetchPaymentIntentPaymentMethodID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchPaymentIntentPaymentMethodID_Call) Return(_a0 string, _a1 error) *Client_FetchPaymentIntentPaymentMethodID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchSetupIntentPaymentMethodID provides a mock function with given fields: ctx, setupIntentID
func (_m *Client) FetchSetupIntentPaymentMethodID(ctx context.Context, setupIntentID string) (string, error) {
	ret := _m.Called(ctx, setupIntentID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, setupIntentID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, setupIntentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchSetupIntentPaymentMethodID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSetupIntentPaymentMethodID'
type Client_FetchSetupIntentPaymentMethodID_Call struct {
	*mock.Call
}

// FetchSetupIntentPaymentMethodID is a helper method to define mock.On call
//   - ctx context.Context
//   - setupIntentID string
func (_e *Client_Expecter) FetchSetupIntentPaymentMethodID(ctx interface{}, setupIntentID interface{}) *Client_FetchSetupIntentPaymentMethodID_Call {
	return &Client_FetchSetupIntentPaymentMethodID_Call{Call: _e.mock.On("FetchSetupIntentPaymentMethodID", ctx, setupIntentID)}
}

func (_c *Client_FetchSetupIntentPaymentMethodID_Call) Run(run func(ctx context.Context, setupIntentID string)) *Client_FetchSetupIntentPaymentMethodID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchSetupIntentPaymentMethodID_Call) Return(_a0 string, _a1 error) *Client_FetchSetupIntentPaymentMethodID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchStripeCustomer provides a mock function with given fields: ctx, stripeCustomerID
func (_m *Client) FetchStripeCustomer(ctx context.Context, stripeCustomerID string) (*billing.StripeCustomer, error) {
	ret := _m.Called(ctx, stripeCustomerID)

	var r0 *billing.StripeCustomer
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.StripeCustomer); ok {
		r0 = rf(ctx, stripeCustomerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.StripeCustomer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stripeCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchStripeCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchStripeCustomer'
type Client_FetchStripeCustomer_Call struct {
	*mock.Call
}

// FetchStripeCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - stripeCustomerID string
func (_e *Client_Expecter) FetchStripeCustomer(ctx interface{}, stripeCustomerID interface{}) *Client_FetchStripeCustomer_Call {
	return &Client_FetchStripeCustomer_Call{Call: _e.mock.On("FetchStripeCustomer", ctx, stripeCustomerID)}
}

func (_c *Client_FetchStripeCustomer_Call) Run(run func(ctx context.Context, stripeCustomerID string)) *Client_FetchStripeCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchStripeCustomer_Call) Return(_a0 *billing.StripeCustomer, _a1 error) *Client_FetchStripeCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchStripePaymentMethodCard provides a mock function with given fields: ctx, paymentMethodID
func (_m *Client) FetchStripePaymentMethodCard(ctx context.Context, paymentMethodID string) (*billing.StripePaymentMethodCard, error) {
	ret := _m.Called(ctx, paymentMethodID)

	var r0 *billing.StripePaymentMethodCard
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.StripePaymentMethodCard); ok {
		r0 = rf(ctx, paymentMethodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.StripePaymentMethodCard)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentMethodID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchStripePaymentMethodCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchStripePaymentMethodCard'
type Client_FetchStripePaymentMethodCard_Call struct {
	*mock.Call
}

// FetchStripePaymentMethodCard is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethodID string
func (_e *Client_Expecter) FetchStripePaymentMethodCard(ctx interface{}, paymentMethodID interface{}) *Client_FetchStripePaymentMethodCard_Call {
	return &Client_FetchStripePaymentMethodCard_Call{Call: _e.mock.On("FetchStripePaymentMethodCard", ctx, paymentMethodID)}
}

func (_c *Client_FetchStripePaymentMethodCard_Call) Run(run func(ctx context.Context, paymentMethodID string)) *Client_FetchStripePaymentMethodCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchStripePaymentMethodCard_Call) Return(_a0 *billing.StripePaymentMethodCard, _a1 error) *Client_FetchStripePaymentMethodCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchUpcomingInvoice provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) FetchUpcomingInvoice(ctx context.Context, externalCustomerID string) (*billing.UpcomingInvoice, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 *billing.UpcomingInvoice
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.UpcomingInvoice); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.UpcomingInvoice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchUpcomingInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUpcomingInvoice'
type Client_FetchUpcomingInvoice_Call struct {
	*mock.Call
}

// FetchUpcomingInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) FetchUpcomingInvoice(ctx interface{}, externalCustomerID interface{}) *Client_FetchUpcomingInvoice_Call {
	return &Client_FetchUpcomingInvoice_Call{Call: _e.mock.On("FetchUpcomingInvoice", ctx, externalCustomerID)}
}

func (_c *Client_FetchUpcomingInvoice_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_FetchUpcomingInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchUpcomingInvoice_Call) Return(_a0 *billing.UpcomingInvoice, _a1 error) *Client_FetchUpcomingInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FinalizeSubscription provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) FinalizeSubscription(ctx context.Context, externalCustomerID string) error {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_FinalizeSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeSubscription'
type Client_FinalizeSubscription_Call struct {
	*mock.Call
}

// FinalizeSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) FinalizeSubscription(ctx interface{}, externalCustomerID interface{}) *Client_FinalizeSubscription_Call {
	return &Client_FinalizeSubscription_Call{Call: _e.mock.On("FinalizeSubscription", ctx, externalCustomerID)}
}

func (_c *Client_FinalizeSubscription_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_FinalizeSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FinalizeSubscription_Call) Return(_a0 error) *Client_FinalizeSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

// HasOutstandingInvoices provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) HasOutstandingInvoices(ctx context.Context, externalCustomerID string) (bool, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_HasOutstandingInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasOutstandingInvoices'
type Client_HasOutstandingInvoices_Call struct {
	*mock.Call
}

// HasOutstandingInvoices is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) HasOutstandingInvoices(ctx interface{}, externalCustomerID interface{}) *Client_HasOutstandingInvoices_Call {
	return &Client_HasOutstandingInvoices_Call{Call: _e.mock.On("HasOutstandingInvoices", ctx, externalCustomerID)}
}

func (_c *Client_HasOutstandingInvoices_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_HasOutstandingInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_HasOutstandingInvoices_Call) Return(_a0 bool, _a1 error) *Client_HasOutstandingInvoices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// HasValidDefaultPaymentMethod provides a mock function with given fields: ctx, stripeCustomerID
func (_m *Client) HasValidDefaultPaymentMethod(ctx context.Context, stripeCustomerID string) (bool, error) {
	ret := _m.Called(ctx, stripeCustomerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, stripeCustomerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stripeCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_HasValidDefaultPaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasValidDefaultPaymentMethod'
type Client_HasValidDefaultPaymentMethod_Call struct {
	*mock.Call
}

// HasValidDefaultPaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - stripeCustomerID string
func (_e *Client_Expecter) HasValidDefaultPaymentMethod(ctx interface{}, stripeCustomerID interface{}) *Client_HasValidDefaultPaymentMethod_Call {
	return &Client_HasValidDefaultPaymentMethod_Call{Call: _e.mock.On("HasValidDefaultPaymentMethod", ctx, stripeCustomerID)}
}

func (_c *Client_HasValidDefaultPaymentMethod_Call) Run(run func(ctx context.Context, stripeCustomerID string)) *Client_HasValidDefaultPaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_HasValidDefaultPaymentMethod_Call) Return(_a0 bool, _a1 error) *Client_HasValidDefaultPaymentMethod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListCustomersCreatedAfter provides a mock function with given fields: ctx, createdAfter
func (_m *Client) ListCustomersCreatedAfter(ctx context.Context, createdAfter time.Time) ([]*billing.Customer, error) {
	ret := _m.Called(ctx, createdAfter)

	var r0 []*billing.Customer
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*billing.Customer); ok {
		r0 = rf(ctx, createdAfter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, createdAfter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListCustomersCreatedAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCustomersCreatedAfter'
type Client_ListCustomersCreatedAfter_Call struct {
	*mock.Call
}

// ListCustomersCreatedAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - createdAfter time.Time
func (_e *Client_Expecter) ListCustomersCreatedAfter(ctx interface{}, createdAfter interface{}) *Client_ListCustomersCreatedAfter_Call {
	return &Client_ListCustomersCreatedAfter_Call{Call: _e.mock.On("ListCustomersCreatedAfter", ctx, createdAfter)}
}

func (_c *Client_ListCustomersCreatedAfter_Call) Run(run func(ctx context.Context, createdAfter time.Time)) *Client_ListCustomersCreatedAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *Client_ListCustomersCreatedAfter_Call) Return(_a0 []*billing.Customer, _a1 error) *Client_ListCustomersCreatedAfter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListInvoices provides a mock function with given fields: ctx, externalCustomerID, opts
func (_m *Client) ListInvoices(ctx context.Context, externalCustomerID string, opts billing.InvoiceListOptions) (*billing.InvoicesPage, error) {
	ret := _m.Called(ctx, externalCustomerID, opts)

	var r0 *billing.InvoicesPage
	if rf, ok := ret.Get(0).(func(context.Context, string, billing.InvoiceListOptions) *billing.InvoicesPage); ok {
		r0 = rf(ctx, externalCustomerID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.InvoicesPage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, billing.InvoiceListOptions) error); ok {
		r1 = rf(ctx, externalCustomerID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvoices'
type Client_ListInvoices_Call struct {
	*mock.Call
}

// ListInvoices is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
//   - opts billing.InvoiceListOptions
func (_e *Client_Expecter) ListInvoices(ctx interface{}, externalCustomerID interface{}, opts interface{}) *Client_ListInvoices_Call {
	return &Client_ListInvoices_Call{Call: _e.mock.On("ListInvoices", ctx, externalCustomerID, opts)}
}

func (_c *Client_ListInvoices_Call) Run(run func(ctx context.Context, externalCustomerID string, opts billing.InvoiceListOptions)) *Client_ListInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(billing.InvoiceListOptions))
	})
	return _c
}

func (_c *Client_ListInvoices_Call) Return(_a0 *billing.InvoicesPage, _a1 error) *Client_ListInvoices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RefundPaymentIntent provides a mock function with given fields: ctx, paymentIntentID, metadata, idempotencyKey
func (_m *Client) RefundPaymentIntent(ctx context.Context, paymentIntentID string, metadata map[string]string, idempotencyKey string) error {
	ret := _m.Called(ctx, paymentIntentID, metadata, idempotencyKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string, string) error); ok {
		r0 = rf(ctx, paymentIntentID, metadata, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_RefundPaymentIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefundPaymentIntent'
type Client_RefundPaymentIntent_Call struct {
	*mock.Call
}

// RefundPaymentIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentIntentID string
//   - metadata map[string]string
//   - idempotencyKey string
func (_e *Client_Expecter) RefundPaymentIntent(ctx interface{}, paymentIntentID interface{}, metadata interface{}, idempotencyKey interface{}) *Client_RefundPaymentIntent_Call {
	return &Client_RefundPaymentIntent_Call{Call: _e.mock.On("RefundPaymentIntent", ctx, paymentIntentID, metadata, idempotencyKey)}
}

func (_c *Client_RefundPaymentIntent_Call) Run(run func(ctx context.Context, paymentIntentID string, metadata map[string]string, idempotencyKey string)) *Client_RefundPaymentIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string), args[3].(string))
	})
	return _c
}

func (_c *Client_RefundPaymentIntent_Call) Return(_a0 error) *Client_RefundPaymentIntent_Call {
	_c.Call.Return(_a0)
	return _c
}

// SetOrbCustomerStripeChargeProvider provides a mock function with given fields: ctx, externalCustomerID, stripeCustomerID
func (_m *Client) SetOrbCustomerStripeChargeProvider(ctx context.Context, externalCustomerID string, stripeCustomerID string) error {
	ret := _m.Called(ctx, externalCustomerID, stripeCustomerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, externalCustomerID, stripeCustomerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_SetOrbCustomerStripeChargeProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrbCustomerStripeChargeProvider'
type Client_SetOrbCustomerStripeChargeProvider_Call struct {
	*mock.Call
}

// SetOrbCustomerStripeChargeProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
//   - stripeCustomerID string
func (_e *Client_Expecter) SetOrbCustomerStripeChargeProvider(ctx interface{}, externalCustomerID interface{}, stripeCustomerID interface{}) *Client_SetOrbCustomerStripeChargeProvider_Call {
	return &Client_SetOrbCustomerStripeChargeProvider_Call{Call: _e.mock.On("SetOrbCustomerStripeChargeProvider", ctx, externalCustomerID, stripeCustomerID)}
}

func (_c *Client_SetOrbCustomerStripeChargeProvider_Call) Run(run func(ctx context.Context, externalCustomerID string, stripeCustomerID string)) *Client_SetOrbCustomerStripeChargeProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_SetOrbCustomerStripeChargeProvider_Call) Return(_a0 error) *Client_SetOrbCustomerStripeChargeProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateOrbCustomerEmail provides a mock function with given fields: ctx, externalCustomerID, email
func (_m *Client) UpdateOrbCustomerEmail(ctx context.Context, externalCustomerID string, email string) (*billing.Customer, error) {
	ret := _m.Called(ctx, externalCustomerID, email)

	var r0 *billing.Customer
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *billing.Customer); ok {
		r0 = rf(ctx, externalCustomerID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, externalCustomerID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_UpdateOrbCustomerEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrbCustomerEmail'
type Client_UpdateOrbCustomerEmail_Call struct {
	*mock.Call
}

// UpdateOrbCustomerEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
//   - email string
func (_e *Client_Expecter) UpdateOrbCustomerEmail(ctx interface{}, externalCustomerID interface{}, email interface{}) *Client_UpdateOrbCustomerEmail_Call {
	return &Client_UpdateOrbCustomerEmail_Call{Call: _e.mock.On("UpdateOrbCustomerEmail", ctx, externalCustomerID, email)}
}

func (_c *Client_UpdateOrbCustomerEmail_Call) Run(run func(ctx context.Context, externalCustomerID string, email string)) *Client_UpdateOrbCustomerEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_UpdateOrbCustomerEmail_Call) Return(_a0 *billing.Customer, _a1 error) *Client_UpdateOrbCustomerEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// VoidInvoice provides a mock function with given fields: ctx, invoiceID
func (_m *Client) VoidInvoice(ctx context.Context, invoiceID string) error {
	ret := _m.Called(ctx, invoiceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_VoidInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoidInvoice'
type Client_VoidInvoice_Call struct {
	*mock.Call
}

// VoidInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID string
func (_e *Client_Expecter) VoidInvoice(ctx interface{}, invoiceID interface{}) *Client_VoidInvoice_Call {
	return &Client_VoidInvoice_Call{Call: _e.mock.On("VoidInvoice", ctx, invoiceID)}
}

func (_c *Client_VoidInvoice_Call) Run(run func(ctx context.Context, invoiceID string)) *Client_VoidInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_VoidInvoice_Call) Return(_a0 error) *Client_VoidInvoice_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
