apiVersion: v1
kind: ConfigMap
metadata:
  name: clusters-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: clusters
data:
  XATA_CLUSTERS_NAMESPACE: {{ .Values.config.clusters.clustersNamespace | quote }}
  XATA_DISKPOOL_NAMESPACE: {{ .Values.config.clusters.openebs.namespace | quote }}
  XATA_CLUSTERS_STORAGE_CLASS: {{ .Values.config.clusters.storageClass | quote }}
  {{- if .Values.config.clusters.nodeSelector }}
  XATA_CLUSTERS_NODE_SELECTOR: {{ .Values.config.clusters.nodeSelector | quote }}
  {{- end }}
  {{- if .Values.config.clusters.volumeSnapshotClass }}
  XATA_CLUSTERS_VOLUME_SNAPSHOT_CLASS: {{ .Values.config.clusters.volumeSnapshotClass | quote }}
  {{- end }}
  {{- if .Values.config.observability.victoriaMetricsURL }}
  VICTORIAMETRICS_URL: {{ .Values.config.observability.victoriaMetricsURL | quote }}
  {{- end }}
  {{- if .Values.config.observability.victoriaLogsURL }}
  VICTORIALOGS_URL: {{ .Values.config.observability.victoriaLogsURL | quote }}
  {{- end }}
  XATA_XATASTOR_ENABLED: {{ .Values.config.clusters.xatastor.enabled | default false | quote }}
