apiVersion: v1
kind: Service
metadata:
  name: clusters
  namespace: {{ .Release.Namespace }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
{{- end }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
  selector:
    app: clusters
