// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	XataScopes = "xata.Scopes"
)

// Defines values for BranchCreationDetailsMode.
const (
	BranchCreationDetailsModeCustom  BranchCreationDetailsMode = "custom"
	BranchCreationDetailsModeInherit BranchCreationDetailsMode = "inherit"
)

// Defines values for BranchFromConfigurationMode.
const (
	BranchFromConfigurationModeCustom BranchFromConfigurationMode = "custom"
)

// Defines values for BranchFromParentMode.
const (
	Inherit BranchFromParentMode = "inherit"
)

// Defines values for BranchMetricsRequestAggregations.
const (
	BranchMetricsRequestAggregationsAvg BranchMetricsRequestAggregations = "avg"
	BranchMetricsRequestAggregationsMax BranchMetricsRequestAggregations = "max"
	BranchMetricsRequestAggregationsMin BranchMetricsRequestAggregations = "min"
)

// Defines values for BranchMetricsRequestMetric.
const (
	ConnectionsActive  BranchMetricsRequestMetric = "connections_active"
	ConnectionsIdle    BranchMetricsRequestMetric = "connections_idle"
	Cpu                BranchMetricsRequestMetric = "cpu"
	Disk               BranchMetricsRequestMetric = "disk"
	IopsRead           BranchMetricsRequestMetric = "iops_read"
	IopsWrite          BranchMetricsRequestMetric = "iops_write"
	LatencyRead        BranchMetricsRequestMetric = "latency_read"
	LatencyWrite       BranchMetricsRequestMetric = "latency_write"
	Memory             BranchMetricsRequestMetric = "memory"
	NetworkEgress      BranchMetricsRequestMetric = "network_egress"
	NetworkIngress     BranchMetricsRequestMetric = "network_ingress"
	ReplicationLagTime BranchMetricsRequestMetric = "replication_lag_time"
	ThroughputRead     BranchMetricsRequestMetric = "throughput_read"
	ThroughputWrite    BranchMetricsRequestMetric = "throughput_write"
	WalSyncTime        BranchMetricsRequestMetric = "wal_sync_time"
)

// Defines values for ExtensionType.
const (
	ExtensionTypeExtension ExtensionType = "extension"
	ExtensionTypeModule    ExtensionType = "module"
	ExtensionTypePlugin    ExtensionType = "plugin"
)

// Defines values for MetricSeriesAggregation.
const (
	MetricSeriesAggregationAvg MetricSeriesAggregation = "avg"
	MetricSeriesAggregationMax MetricSeriesAggregation = "max"
	MetricSeriesAggregationMin MetricSeriesAggregation = "min"
)

// Defines values for PostgresConfigParameterDefaultValueSource.
const (
	InstanceType PostgresConfigParameterDefaultValueSource = "instance_type"
	Postgres     PostgresConfigParameterDefaultValueSource = "postgres"
)

// Defines values for PostgresConfigParameterType.
const (
	Boolean  PostgresConfigParameterType = "boolean"
	Bytes    PostgresConfigParameterType = "bytes"
	Duration PostgresConfigParameterType = "duration"
	Enum     PostgresConfigParameterType = "enum"
	Float    PostgresConfigParameterType = "float"
	Int      PostgresConfigParameterType = "int"
	String   PostgresConfigParameterType = "string"
)

// BackupConfiguration Details about the branch continuous backup configuration
type BackupConfiguration struct {
	// BackupTime time of day/week when we are taking a full backup
	BackupTime *string `json:"backupTime,omitempty"`

	// RetentionPeriod how long are we keeping the backups around for
	RetentionPeriod *int32 `json:"retentionPeriod,omitempty"`
}

// BackupMetadata metadata about a continuous backup
type BackupMetadata struct {
	// BranchID the branchID the branch associated with the backup
	BranchID string `json:"branchID"`

	// Description description of the backup
	Description string `json:"description"`

	// EarliestRestore the earlies point in time available for restoring the branch
	EarliestRestore *time.Time `json:"earliestRestore,omitempty"`

	// Id unique identifier for the backup
	Id string `json:"id"`

	// LatestRestore the latest point in time available for restoring the branch
	LatestRestore *time.Time `json:"latestRestore,omitempty"`
}

// BranchCreationDetails Details required when creating a new branch
type BranchCreationDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Description Optional description for the branch purpose or contents (max 50 characters)
	Description *string `json:"description,omitempty"`

	// Mode The mode used to discriminate between types of branches.
	Mode BranchCreationDetailsMode `json:"mode"`

	// Name Human-readable name for the new branch
	Name string `json:"name"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
	union       json.RawMessage
}

// BranchCreationDetailsMode The mode used to discriminate between types of branches.
type BranchCreationDetailsMode string

// BranchCredentials Credentials for accessing a branch, username and password
type BranchCredentials struct {
	// Password Password for accessing the branch database
	Password string `json:"password"`

	// Username Username for accessing the branch database
	Username string `json:"username"`
}

// BranchFromConfiguration defines model for BranchFromConfiguration.
type BranchFromConfiguration struct {
	// Configuration Configuration details for a database cluster backing a branch
	Configuration ClusterConfiguration        `json:"configuration"`
	Mode          BranchFromConfigurationMode `json:"mode"`
}

// BranchFromConfigurationMode defines model for BranchFromConfiguration.Mode.
type BranchFromConfigurationMode string

// BranchFromParent defines model for BranchFromParent.
type BranchFromParent struct {
	Mode BranchFromParentMode `json:"mode"`

	// ParentID If present, the branch will inherit the parent branch configuration and data
	ParentID string `json:"parentID"`
}

// BranchFromParentMode defines model for BranchFromParent.Mode.
type BranchFromParentMode string

// BranchListMetadata Metadata about a branch used when listing branches in a project
type BranchListMetadata struct {
	// BackupsEnabled Whether the branch is in a region that supports backups
	BackupsEnabled bool `json:"backupsEnabled"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchMetadata Detailed metadata about a branch, including its status and configuration
type BranchMetadata struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// BackupsEnabled Whether the branch is in a region that supports backups
	BackupsEnabled bool `json:"backupsEnabled"`

	// Configuration Configuration details for a database cluster backing a branch
	Configuration ClusterConfiguration `json:"configuration"`

	// ConnectionString Database connection string for accessing this branch
	ConnectionString *string `json:"connectionString"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero ScaleToZeroConfiguration `json:"scaleToZero"`

	// Status Detailed status information about a branch and its underlying database cluster
	Status BranchStatus `json:"status"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchMetrics A collection of metrics (cpu, memory, disk,...) for each of the instances of a branch
type BranchMetrics struct {
	End    time.Time      `json:"end"`
	Metric string         `json:"metric"`
	Series []MetricSeries `json:"series"`
	Start  time.Time      `json:"start"`

	// Unit The unit of the metric (percentage, bytes, ms, etc.)
	Unit string `json:"unit"`
}

// BranchMetricsRequest defines model for BranchMetricsRequest.
type BranchMetricsRequest struct {
	// Aggregations List of aggregations to get, this is how the data-points within the interval are aggregated. Each one will generate a separate time-series in the response.
	Aggregations []BranchMetricsRequestAggregations `json:"aggregations"`

	// End End time
	End time.Time `json:"end"`

	// Instances List of instance IDs to query
	Instances []string `json:"instances"`

	// Metric Metric name to query
	Metric BranchMetricsRequestMetric `json:"metric"`

	// Start Start time
	Start time.Time `json:"start"`
}

// BranchMetricsRequestAggregations defines model for BranchMetricsRequest.Aggregations.
type BranchMetricsRequestAggregations string

// BranchMetricsRequestMetric Metric name to query
type BranchMetricsRequestMetric string

// BranchShortMetadata Basic metadata about a branch, used in response to create/update operations
type BranchShortMetadata struct {
	// ConnectionString Database connection string for accessing this branch
	ConnectionString *string `json:"connectionString"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchStatus Detailed status information about a branch and its underlying database cluster
type BranchStatus struct {
	// InstanceCount Total number of database instances in the cluster
	InstanceCount int `json:"instanceCount"`

	// InstanceReadyCount Number of database instances that are ready and operational
	InstanceReadyCount int `json:"instanceReadyCount"`

	// Instances Details about each individual database instance in the cluster
	Instances []InstanceStatus `json:"instances"`

	// Lifecycle Information about the current lifecycle state of a database cluster
	// Deprecated:
	Lifecycle *ClusterLifecycle `json:"lifecycle,omitempty"`

	// Message Human-readable message explaining the current status
	// Deprecated:
	Message *string `json:"message,omitempty"`

	// Status Status indicator for the branch according to CNPG
	Status string `json:"status"`

	// StatusType Type of status of the branch
	StatusType interface{} `json:"statusType"`
}

// BranchUpdateDetails Details that can be updated for an existing branch
type BranchUpdateDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Description New description for the branch (max 50 characters)
	Description *string `json:"description,omitempty"`

	// Hibernate Enabled when the branch should be hibernated, disabled if it needs to be reactivated.
	Hibernate *bool `json:"hibernate,omitempty"`

	// Image PostgreSQL image to use for the database instances
	Image *string `json:"image,omitempty"`

	// InstanceType New instance type for the branch
	InstanceType *string `json:"instanceType,omitempty"`

	// Name New name for the branch
	Name *string `json:"name,omitempty"`

	// PostgresConfigurationParameters Arbitrary PostgreSQL configuration parameters for the cluster
	PostgresConfigurationParameters *map[string]string `json:"postgresConfigurationParameters,omitempty"`

	// PreloadLibraries List of PostgreSQL extensions and libraries to preload
	PreloadLibraries *[]string `json:"preloadLibraries,omitempty"`

	// Replicas Number of database replicas to scale to
	Replicas *int32 `json:"replicas,omitempty"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`

	// Storage Branch storage in GiB (gigabytes)
	Storage *int32 `json:"storage,omitempty"`
}

// CidrEntry defines model for CidrEntry.
type CidrEntry struct {
	// Cidr CIDR block (e.g., "192.168.0.0/24")
	Cidr string `json:"cidr"`

	// Description Optional label for the CIDR entry
	Description *string `json:"description,omitempty"`
}

// ClusterConfiguration Configuration details for a database cluster backing a branch
type ClusterConfiguration struct {
	// Image PostgreSQL image to use for the database instances
	Image string `json:"image"`

	// InstanceType The instance type according to the xata instance types available
	InstanceType string `json:"instanceType"`

	// PostgresConfigurationParameters Arbitrary PostgreSQL configuration parameters for the cluster
	PostgresConfigurationParameters *map[string]string `json:"postgresConfigurationParameters,omitempty"`

	// PreloadLibraries List of PostgreSQL extensions and libraries to preload
	PreloadLibraries *[]string `json:"preloadLibraries,omitempty"`

	// Region Geographic region where the cluster will be deployed
	Region string `json:"region"`

	// Replicas Number of replicas in the branch. Every child branch is created with no replicas. This can be updated.
	Replicas int32 `json:"replicas"`

	// Storage Branch storage in GiB (gigabytes)
	Storage *int32 `json:"storage,omitempty"`
}

// ClusterLifecycle Information about the current lifecycle state of a database cluster
type ClusterLifecycle struct {
	// Phase Current phase within the lifecycle process
	Phase string `json:"phase"`

	// Reason Reason for the current lifecycle state, especially useful for non-ready states
	Reason *string `json:"reason,omitempty"`

	// State Current operational state of the cluster (ready, creating, updating, etc.)
	State interface{} `json:"state"`
}

// CreateGithubAppInstallationRequest defines model for CreateGithubAppInstallationRequest.
type CreateGithubAppInstallationRequest struct {
	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`
}

// CreateGithubRepositoryRequest defines model for CreateGithubRepositoryRequest.
type CreateGithubRepositoryRequest struct {
	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`
}

// Extension Details of a postgres extension
type Extension struct {
	// Description Extension description
	Description string `json:"description"`

	// Docs Documentation URL
	Docs string `json:"docs"`

	// Name Extension name
	Name string `json:"name"`

	// PreloadRequired is preload required for the extension or not
	PreloadRequired bool `json:"preloadRequired"`

	// Type type of installation
	Type ExtensionType `json:"type"`

	// Version Extension version
	Version string `json:"version"`
}

// ExtensionType type of installation
type ExtensionType string

// GithubInstallation A GitHub App installation associated with an organization
type GithubInstallation struct {
	// CreatedAt Timestamp when the installation was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier of the installation record
	Id string `json:"id"`

	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`

	// Organization Organization ID this installation belongs to
	Organization string `json:"organization"`

	// UpdatedAt Timestamp when the installation was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GithubRepository A mapping between a GitHub repository and a Xata project
type GithubRepository struct {
	// CreatedAt Timestamp when the mapping was created
	CreatedAt time.Time `json:"createdAt"`

	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`

	// Id Unique identifier of the mapping record
	Id string `json:"id"`

	// Project Project ID this mapping is associated with
	Project string `json:"project"`

	// RootBranchId ID of the root Xata branch mapped to this repository
	RootBranchId string `json:"rootBranchId"`

	// UpdatedAt Timestamp when the mapping was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// IPFilteringConfiguration Configuration for IP filtering on project branches
type IPFilteringConfiguration struct {
	Cidr []CidrEntry `json:"cidr"`

	// Enabled Whether IP filtering is enabled
	Enabled bool `json:"enabled"`
}

// Image Details of a postgres image
type Image struct {
	// FullVersion full postgres version
	FullVersion string `json:"fullVersion"`

	// MajorVersion major postgres version
	MajorVersion string `json:"majorVersion"`

	// Name Image name
	Name string `json:"name"`

	// Region region where this instance type is available
	Region *[]string `json:"region,omitempty"`
}

// InstanceStatus Status information about an individual database instance within a cluster
type InstanceStatus struct {
	// Id Unique identifier for the database instance
	Id string `json:"id"`

	// Primary Indicates if this instance is currently the primary (write) instance
	Primary bool `json:"primary"`

	// Status Current operational status of the instance
	Status string `json:"status"`

	// TargetPrimary Indicates if this instance is the target primary during a failover operation
	TargetPrimary bool `json:"targetPrimary"`
}

// MetricSeries The metric series
type MetricSeries struct {
	// Aggregation The aggregation used to generate this time-series
	Aggregation MetricSeriesAggregation `json:"aggregation"`

	// InstanceID ID of the instance
	InstanceID string `json:"instanceID"`
	Values     []struct {
		Timestamp time.Time `json:"timestamp"`
		Value     float32   `json:"value"`
	} `json:"values"`
}

// MetricSeriesAggregation The aggregation used to generate this time-series
type MetricSeriesAggregation string

// OrganizationID defines model for OrganizationID.
type OrganizationID = string

// PostgresConfigDetails Detailed information about PostgreSQL configuration parameters for a branch
type PostgresConfigDetails struct {
	// Parameters Array of PostgreSQL configuration parameters with detailed information
	Parameters []PostgresConfigParameter `json:"parameters"`
}

// PostgresConfigParameter Detailed information about a single PostgreSQL configuration parameter
type PostgresConfigParameter struct {
	// AcceptableRange Information about the acceptable range of values for this parameter
	AcceptableRange *struct {
		// EnumValues List of allowed enum values (if applicable)
		EnumValues *[]string `json:"enumValues,omitempty"`

		// MaxValue Maximum allowed value (if applicable)
		MaxValue *string `json:"maxValue,omitempty"`

		// MinValue Minimum allowed value (if applicable)
		MinValue *string `json:"minValue,omitempty"`
	} `json:"acceptableRange,omitempty"`

	// CurrentValue The current value of this parameter in the branch
	CurrentValue string `json:"currentValue"`

	// DefaultValue The default value for this parameter
	DefaultValue string `json:"defaultValue"`

	// DefaultValueSource The source of the default value
	DefaultValueSource PostgresConfigParameterDefaultValueSource `json:"defaultValueSource"`

	// Description Human-readable description of what the parameter controls
	Description string `json:"description"`

	// DocumentationLink Link to PostgreSQL documentation for this parameter
	DocumentationLink string `json:"documentationLink"`

	// Name The name of the PostgreSQL parameter
	Name string `json:"name"`

	// Recommendation Optional recommendation for this parameter (currently empty)
	Recommendation string `json:"recommendation"`

	// RestartRequired Whether a database restart is required for this parameter change to take effect
	RestartRequired *bool `json:"restartRequired,omitempty"`

	// Section The section/category this parameter belongs to
	Section string `json:"section"`

	// Type The data type of the parameter
	Type PostgresConfigParameterType `json:"type"`
}

// PostgresConfigParameterDefaultValueSource The source of the default value
type PostgresConfigParameterDefaultValueSource string

// PostgresConfigParameterType The data type of the parameter
type PostgresConfigParameterType string

// Project Details of a project including its ID, name, and creation/update timestamps
type Project struct {
	// Configuration Configuration details for a project, including its scale to zero settings
	Configuration ProjectConfiguration `json:"configuration"`

	// CreatedAt Timestamp when the project was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the project
	Id string `json:"id"`

	// Name Human-readable name of the project
	Name string `json:"name"`

	// UpdatedAt Timestamp when the project was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProjectConfiguration Configuration details for a project, including its scale to zero settings
type ProjectConfiguration struct {
	// IpFiltering Configuration for IP filtering on project branches
	IpFiltering *IPFilteringConfiguration `json:"ipFiltering,omitempty"`

	// ScaleToZero Whether the project branches are configured to scale down to zero when not in use
	ScaleToZero ProjectScaleToZeroConfiguration `json:"scaleToZero"`
}

// ProjectLimits Resource limits and constraints for projects within an organization
type ProjectLimits struct {
	// MaxBranches Maximum number of branches allowed per project
	MaxBranches int `json:"maxBranches"`

	// MaxDescriptionLength Maximum character length allowed for project descriptions
	MaxDescriptionLength int `json:"maxDescriptionLength"`

	// MaxInstances Maximum number of database instances allowed per branch
	MaxInstances int `json:"maxInstances"`

	// MinInstances Minimum number of database instances required per branch
	MinInstances int `json:"minInstances"`
}

// ProjectScaleToZeroConfiguration Whether the project branches are configured to scale down to zero when not in use
type ProjectScaleToZeroConfiguration struct {
	// BaseBranches Configuration for scaling branches to zero when not in use
	BaseBranches ScaleToZeroConfiguration `json:"baseBranches"`

	// ChildBranches Configuration for scaling branches to zero when not in use
	ChildBranches ScaleToZeroConfiguration `json:"childBranches"`
}

// RestoreDetails Metadata about a backup, used in request to create a restore. If configuration is not provided, the branch will inherit the source branch configuration.
type RestoreDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Configuration Configuration details for a database cluster backing a branch
	Configuration *ClusterConfiguration `json:"configuration,omitempty"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
}

// RotateCredentialsRequest Request to rotate credentials for a branch database user
type RotateCredentialsRequest struct {
	// Username Database username to rotate credentials for
	Username string `json:"username"`
}

// ScaleToZeroConfiguration Configuration for scaling branches to zero when not in use
type ScaleToZeroConfiguration struct {
	// Enabled Whether scale to zero is enabled
	Enabled bool `json:"enabled"`

	// InactivityPeriodMinutes Duration in minutes after which branches will be hibernated if not accessed
	InactivityPeriodMinutes int `json:"inactivityPeriodMinutes"`
}

// UpdateGithubAppInstallationRequest defines model for UpdateGithubAppInstallationRequest.
type UpdateGithubAppInstallationRequest struct {
	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`
}

// UpdateGithubRepositoryRequest defines model for UpdateGithubRepositoryRequest.
type UpdateGithubRepositoryRequest struct {
	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`
}

// UpdateProjectConfiguration Partial configuration update for a project
type UpdateProjectConfiguration struct {
	// IpFiltering Configuration for IP filtering on project branches
	IpFiltering *IPFilteringConfiguration `json:"ipFiltering,omitempty"`

	// ScaleToZero Whether the project branches are configured to scale down to zero when not in use
	ScaleToZero *ProjectScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
}

// AuthorizationError defines model for AuthorizationError.
type AuthorizationError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the authentication or authorization issue
	Message string `json:"message"`
}

// GenericError defines model for GenericError.
type GenericError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the issue
	Message string `json:"message"`
}

// PreconditionFailedError defines model for PreconditionFailedError.
type PreconditionFailedError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the precondition failure
	Message string `json:"message"`
}

// ListExtensionsParams defines parameters for ListExtensions.
type ListExtensionsParams struct {
	// Image Image for which we list extensions
	Image string `form:"image" json:"image"`

	// Region Region to list extensions for image in
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Region Region to check image availability for organization
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// ListInstanceTypesParams defines parameters for ListInstanceTypes.
type ListInstanceTypesParams struct {
	// Region Region to check instance type availability for
	Region string `form:"region" json:"region"`
}

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	// Configuration Configuration details for a project, including its scale to zero settings
	Configuration *ProjectConfiguration `json:"configuration,omitempty"`

	// Name Human-readable name for the new project
	Name string `json:"name"`
}

// UpdateProjectJSONBody defines parameters for UpdateProject.
type UpdateProjectJSONBody struct {
	// Configuration Partial configuration update for a project
	Configuration *UpdateProjectConfiguration `json:"configuration,omitempty"`

	// Name New name for the project
	Name *string `json:"name,omitempty"`
}

// GetBranchCredentialsParams defines parameters for GetBranchCredentials.
type GetBranchCredentialsParams struct {
	// Username Username that the credentials requested for
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// CreateGithubAppInstallationJSONRequestBody defines body for CreateGithubAppInstallation for application/json ContentType.
type CreateGithubAppInstallationJSONRequestBody = CreateGithubAppInstallationRequest

// UpdateGithubAppInstallationJSONRequestBody defines body for UpdateGithubAppInstallation for application/json ContentType.
type UpdateGithubAppInstallationJSONRequestBody = UpdateGithubAppInstallationRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody UpdateProjectJSONBody

// CreateBranchJSONRequestBody defines body for CreateBranch for application/json ContentType.
type CreateBranchJSONRequestBody = BranchCreationDetails

// UpdateBranchJSONRequestBody defines body for UpdateBranch for application/json ContentType.
type UpdateBranchJSONRequestBody = BranchUpdateDetails

// RotateBranchCredentialsJSONRequestBody defines body for RotateBranchCredentials for application/json ContentType.
type RotateBranchCredentialsJSONRequestBody = RotateCredentialsRequest

// CreateGithubRepositoryJSONRequestBody defines body for CreateGithubRepository for application/json ContentType.
type CreateGithubRepositoryJSONRequestBody = CreateGithubRepositoryRequest

// UpdateGithubRepositoryJSONRequestBody defines body for UpdateGithubRepository for application/json ContentType.
type UpdateGithubRepositoryJSONRequestBody = UpdateGithubRepositoryRequest

// BranchMetricsJSONRequestBody defines body for BranchMetrics for application/json ContentType.
type BranchMetricsJSONRequestBody = BranchMetricsRequest

// RestoreFromBackupJSONRequestBody defines body for RestoreFromBackup for application/json ContentType.
type RestoreFromBackupJSONRequestBody = RestoreDetails

// AsBranchFromParent returns the union data inside the BranchCreationDetails as a BranchFromParent
func (t BranchCreationDetails) AsBranchFromParent() (BranchFromParent, error) {
	var body BranchFromParent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBranchFromParent overwrites any union data inside the BranchCreationDetails as the provided BranchFromParent
func (t *BranchCreationDetails) FromBranchFromParent(v BranchFromParent) error {
	t.Mode = "inherit"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBranchFromParent performs a merge with any union data inside the BranchCreationDetails, using the provided BranchFromParent
func (t *BranchCreationDetails) MergeBranchFromParent(v BranchFromParent) error {
	t.Mode = "inherit"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBranchFromConfiguration returns the union data inside the BranchCreationDetails as a BranchFromConfiguration
func (t BranchCreationDetails) AsBranchFromConfiguration() (BranchFromConfiguration, error) {
	var body BranchFromConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBranchFromConfiguration overwrites any union data inside the BranchCreationDetails as the provided BranchFromConfiguration
func (t *BranchCreationDetails) FromBranchFromConfiguration(v BranchFromConfiguration) error {
	t.Mode = "custom"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBranchFromConfiguration performs a merge with any union data inside the BranchCreationDetails, using the provided BranchFromConfiguration
func (t *BranchCreationDetails) MergeBranchFromConfiguration(v BranchFromConfiguration) error {
	t.Mode = "custom"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BranchCreationDetails) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"mode"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t BranchCreationDetails) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "custom":
		return t.AsBranchFromConfiguration()
	case "inherit":
		return t.AsBranchFromParent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t BranchCreationDetails) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.BackupConfiguration != nil {
		object["backupConfiguration"], err = json.Marshal(t.BackupConfiguration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backupConfiguration': %w", err)
		}
	}

	if t.Description != nil {
		object["description"], err = json.Marshal(t.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	object["mode"], err = json.Marshal(t.Mode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mode': %w", err)
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if t.ScaleToZero != nil {
		object["scaleToZero"], err = json.Marshal(t.ScaleToZero)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scaleToZero': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *BranchCreationDetails) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["backupConfiguration"]; found {
		err = json.Unmarshal(raw, &t.BackupConfiguration)
		if err != nil {
			return fmt.Errorf("error reading 'backupConfiguration': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &t.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["scaleToZero"]; found {
		err = json.Unmarshal(raw, &t.ScaleToZero)
		if err != nil {
			return fmt.Errorf("error reading 'scaleToZero': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get available extensions for image
	// (GET /organizations/{organizationID}/extensions)
	ListExtensions(ctx echo.Context, organizationID OrganizationID, params ListExtensionsParams) error
	// List GitHub App installations for organization
	// (GET /organizations/{organizationID}/githubapp/installations)
	ListGithubAppInstallations(ctx echo.Context, organizationID OrganizationID) error
	// Create GitHub App installation
	// (POST /organizations/{organizationID}/githubapp/installations)
	CreateGithubAppInstallation(ctx echo.Context, organizationID OrganizationID) error
	// Update GitHub App installation
	// (PUT /organizations/{organizationID}/githubapp/installations/{githubInstallationID})
	UpdateGithubAppInstallation(ctx echo.Context, organizationID OrganizationID, githubInstallationID string) error
	// Get available images
	// (GET /organizations/{organizationID}/images)
	ListImages(ctx echo.Context, organizationID OrganizationID, params ListImagesParams) error
	// Get available instance types
	// (GET /organizations/{organizationID}/instanceTypes)
	ListInstanceTypes(ctx echo.Context, organizationID OrganizationID, params ListInstanceTypesParams) error
	// List all projects
	// (GET /organizations/{organizationID}/projects)
	ListProjects(ctx echo.Context, organizationID OrganizationID) error
	// Create a new project
	// (POST /organizations/{organizationID}/projects)
	CreateProject(ctx echo.Context, organizationID OrganizationID) error
	// Get project resource limits
	// (GET /organizations/{organizationID}/projects/limits)
	GetDefaultProjectLimits(ctx echo.Context, organizationID OrganizationID) error
	// Delete a project
	// (DELETE /organizations/{organizationID}/projects/{projectID})
	DeleteProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Get project details
	// (GET /organizations/{organizationID}/projects/{projectID})
	GetProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Update project details
	// (PATCH /organizations/{organizationID}/projects/{projectID})
	UpdateProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// List project backups
	// (GET /organizations/{organizationID}/projects/{projectID}/backups)
	ListBackups(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Get project backup by ID
	// (GET /organizations/{organizationID}/projects/{projectID}/backups/{backupID})
	GetBackup(ctx echo.Context, organizationID OrganizationID, projectID string, backupID string) error
	// List all branches
	// (GET /organizations/{organizationID}/projects/{projectID}/branches)
	ListBranches(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Create a new branch
	// (POST /organizations/{organizationID}/projects/{projectID}/branches)
	CreateBranch(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Delete a branch
	// (DELETE /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	DeleteBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get branch details
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	DescribeBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Update branch details
	// (PATCH /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	UpdateBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Retrieve branch credentials
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/credentials)
	GetBranchCredentials(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string, params GetBranchCredentialsParams) error
	// Rotate branch credentials
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/credentials/rotate)
	RotateBranchCredentials(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Delete GitHub repository mapping
	// (DELETE /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	DeleteGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get GitHub repository for branch
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	GetGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Create GitHub repository mapping
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	CreateGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Update GitHub repository mapping
	// (PUT /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	UpdateGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Retrieve branch metrics
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/metrics)
	BranchMetrics(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get PostgreSQL configuration details
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/postgres-config)
	GetBranchPostgresConfig(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Create a new branch from a backup of another branch
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/restore)
	RestoreFromBackup(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get available regions
	// (GET /organizations/{organizationID}/regions)
	ListRegions(ctx echo.Context, organizationID OrganizationID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListExtensions converts echo context to params.
func (w *ServerInterfaceWrapper) ListExtensions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExtensionsParams
	// ------------- Required query parameter "image" -------------

	err = runtime.BindQueryParameter("form", true, true, "image", ctx.QueryParams(), &params.Image)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter image: %s", err))
	}

	// ------------- Optional query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, false, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListExtensions(ctx, organizationID, params)
	return err
}

// ListGithubAppInstallations converts echo context to params.
func (w *ServerInterfaceWrapper) ListGithubAppInstallations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGithubAppInstallations(ctx, organizationID)
	return err
}

// CreateGithubAppInstallation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGithubAppInstallation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGithubAppInstallation(ctx, organizationID)
	return err
}

// UpdateGithubAppInstallation converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGithubAppInstallation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "githubInstallationID" -------------
	var githubInstallationID string

	err = runtime.BindStyledParameterWithOptions("simple", "githubInstallationID", ctx.Param("githubInstallationID"), &githubInstallationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter githubInstallationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGithubAppInstallation(ctx, organizationID, githubInstallationID)
	return err
}

// ListImages converts echo context to params.
func (w *ServerInterfaceWrapper) ListImages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListImagesParams
	// ------------- Optional query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, false, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListImages(ctx, organizationID, params)
	return err
}

// ListInstanceTypes converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceTypes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstanceTypesParams
	// ------------- Required query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, true, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceTypes(ctx, organizationID, params)
	return err
}

// ListProjects converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjects(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjects(ctx, organizationID)
	return err
}

// CreateProject converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProject(ctx, organizationID)
	return err
}

// GetDefaultProjectLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetDefaultProjectLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDefaultProjectLimits(ctx, organizationID)
	return err
}

// DeleteProject converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProject(ctx, organizationID, projectID)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, organizationID, projectID)
	return err
}

// UpdateProject converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProject(ctx, organizationID, projectID)
	return err
}

// ListBackups converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackups(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackups(ctx, organizationID, projectID)
	return err
}

// GetBackup converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "backupID" -------------
	var backupID string

	err = runtime.BindStyledParameterWithOptions("simple", "backupID", ctx.Param("backupID"), &backupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backupID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackup(ctx, organizationID, projectID, backupID)
	return err
}

// ListBranches converts echo context to params.
func (w *ServerInterfaceWrapper) ListBranches(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBranches(ctx, organizationID, projectID)
	return err
}

// CreateBranch converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBranch(ctx, organizationID, projectID)
	return err
}

// DeleteBranch converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBranch(ctx, organizationID, projectID, branchID)
	return err
}

// DescribeBranch converts echo context to params.
func (w *ServerInterfaceWrapper) DescribeBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DescribeBranch(ctx, organizationID, projectID, branchID)
	return err
}

// UpdateBranch converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBranch(ctx, organizationID, projectID, branchID)
	return err
}

// GetBranchCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GetBranchCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"credentials:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBranchCredentialsParams
	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", ctx.QueryParams(), &params.Username)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter username: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBranchCredentials(ctx, organizationID, projectID, branchID, params)
	return err
}

// RotateBranchCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) RotateBranchCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"credentials:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RotateBranchCredentials(ctx, organizationID, projectID, branchID)
	return err
}

// DeleteGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// GetGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) GetGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// CreateGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// UpdateGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// BranchMetrics converts echo context to params.
func (w *ServerInterfaceWrapper) BranchMetrics(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"metrics:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BranchMetrics(ctx, organizationID, projectID, branchID)
	return err
}

// GetBranchPostgresConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetBranchPostgresConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBranchPostgresConfig(ctx, organizationID, projectID, branchID)
	return err
}

// RestoreFromBackup converts echo context to params.
func (w *ServerInterfaceWrapper) RestoreFromBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestoreFromBackup(ctx, organizationID, projectID, branchID)
	return err
}

// ListRegions converts echo context to params.
func (w *ServerInterfaceWrapper) ListRegions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRegions(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/organizations/:organizationID/extensions", wrapper.ListExtensions)
	router.GET(baseURL+"/organizations/:organizationID/githubapp/installations", wrapper.ListGithubAppInstallations)
	router.POST(baseURL+"/organizations/:organizationID/githubapp/installations", wrapper.CreateGithubAppInstallation)
	router.PUT(baseURL+"/organizations/:organizationID/githubapp/installations/:githubInstallationID", wrapper.UpdateGithubAppInstallation)
	router.GET(baseURL+"/organizations/:organizationID/images", wrapper.ListImages)
	router.GET(baseURL+"/organizations/:organizationID/instanceTypes", wrapper.ListInstanceTypes)
	router.GET(baseURL+"/organizations/:organizationID/projects", wrapper.ListProjects)
	router.POST(baseURL+"/organizations/:organizationID/projects", wrapper.CreateProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/limits", wrapper.GetDefaultProjectLimits)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.DeleteProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.GetProject)
	router.PATCH(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.UpdateProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/backups", wrapper.ListBackups)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/backups/:backupID", wrapper.GetBackup)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches", wrapper.ListBranches)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches", wrapper.CreateBranch)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.DeleteBranch)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.DescribeBranch)
	router.PATCH(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.UpdateBranch)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/credentials", wrapper.GetBranchCredentials)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/credentials/rotate", wrapper.RotateBranchCredentials)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.DeleteGithubRepository)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.GetGithubRepository)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.CreateGithubRepository)
	router.PUT(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.UpdateGithubRepository)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/metrics", wrapper.BranchMetrics)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/postgres-config", wrapper.GetBranchPostgresConfig)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/restore", wrapper.RestoreFromBackup)
	router.GET(baseURL+"/organizations/:organizationID/regions", wrapper.ListRegions)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PbuNX/V8Hw3xdJS1+SzXb+9TsndrKeyWZd22m3zfrJQCQkoaEAFgBtq6mfz/4M",
	"rgRJgKQU+bbRm12HInE5OOeHc8PB1ySji5ISRARPDr4mDPGSEo7UPw4rMacM/wcKTMkxY5TJpxklAhEh",
	"/4RlWeBM/bz3L06JfMazOVpA+VfJaImYwLoxnMv/5ohnDJfyi+QgUW0CnCMi8BQjBqaUAcFg9gWTGYAk",
	"BzmaVLMZJrMkTcSyRMlBwgWT/75NkwXiHM5Qt92fqgUkOwzBHE4KBJDqxrwN0E1ZQExkD2KOAKzEXPav",
	"pwEoU0/ctAHmvELd3m/ThKF/V5ihPDn45IZy6V6kk3+hTCS38s3QrC2lwfUckcFRTCEuuJzzO0QQw9nv",
	"dTU2T21DMNOto7qc24JyYZ5nlORYfqGIfMqQe/AW4gLlv1d6l95MFZNV7B6YvdWtnPYcAdkF4gJgDggV",
	"YIGE6lmTVFHxNcy+VOUbSqZ4VjGou2hP/wgJKSwATmglVMMTBkk2l2ssMKloxcFENSSfeC2lrTXTL13g",
	"RYDGAi8QoFOQw+XeNUJf9MSuEYAMAQH1CoJpVRSmL9k6FAIx+fX/PPvttz/+99P+zp8vnx882/+0v/OX",
	"y/++0P97+Wl/5wf5+NP+zo+X6tnzP4TWnyHJiJiSU8QwNfw1hVUhkoOX7WWY02tQUDkohuQwvyBUWh7Q",
	"A+QAMlqRXC5HkiZTyhZQJAcJJuKHl0maLOANXlSL5OCHH9NkgYn+x0s3MEwEmiGmlqzJFWlys4NusqLK",
	"JfsIViH5RL7PCCz0k9vULO7PSMAcCtgl+cL8YhYWdtezu4Jq4U+OAuvn2OLkyOcRyDnNMBQoB9dYzD36",
	"hJag0Wa7C+9fklP6W0KQFRhxcYa4oAyFB2xeAiXFRABMgOJCeAVxoSR9qiVNUOaWVs3KX84cCrQjvwuN",
	"IoRSFcH/rlAHpnpnU0AxNBf9yl1NpQVYOE/Smhma69YFsTR5rV59w5ACBgMocaSxXWkQyNRnSv4Juq7H",
	"nWP57QITKPRWsoCllEG1q1Rc0EVykPy/vVof2zPIt6eH85bRxZsWYGEyRwyL4Q9PIZO71q2TkOUHKHEt",
	"WdAcyceUoF+mycGnr8kfGJqu0ODYD5pDv70Mo20H23sbD3wyJJW/qD9gAXzxdBytQaCsWEk5AlovkCjL",
	"wbMFvAE/7oNsDhnMBGL8uQbF94jMxDw5+HG/gfCf4M5/Dnf+KeH7T/XfO+Dyj0EwV8vQGezFHAH5C6g4",
	"yoGgwOMhBCZIXCNEgGyMS4jRw0d8N0kTRCQ8f3Ickloeuwz0TuBiWI+QLzlKNTi70x7PYIEu6D8Ro0Nr",
	"eF6/2lrIlgyrMRpC9cqsAioYklfvRzURmGWIcy2qejKppDRTM5X6Vwk5v6Ys72ws7odOH6fml1YHHnfJ",
	"PWwCeRCAbe/ddj/aca3RbouSrpO0nsdlaNPubtERae6ou9kqYvymqLhArCPHViYsK0cZuK2eyu/S1hji",
	"LOOhWWce7SFYaQoJUanaCCkbJ1Op8HJEROov2DUuCmBa1Mq4asFTV+vxa3NA6kUjZ+9GE5/4e8xFXN36",
	"ua1umWEpKFIbXYG52ucs7MhtXKr21DBQCN/5MZFgEhCcv8+RmKMGDmPTJEMzSQIxhwLwqiwpE1bl4zU9",
	"JpQWCCrOUVswyg9FAFLxAnEBF6Weg78ckAPz4WiFafWtxmqC0Z1mrF72Ma6XRXF5PM43hpmsxu31iEwr",
	"Tb7G8qFcWg4gyBHDVyh38EukxUQlI1xjBWXygRyWNRy6A6kmBc4OFSKO4ipYFPSaA/2dgVKl7Cs2b/hh",
	"gsylubHb1TtEZwyWc5xZhr2eI2kNNhg6R2VBl4rFuuhf5uuxbQG5AObrb9CQzaZQS48/JDfxFsnTtmTH",
	"AScONlqTRjlYhFEnBZhIA1LCDRYccAFFxRUojrHhN6FV3it+bWL7zCghKJP/Otdr3qW60RhA/SrQ/NHR",
	"MjCvsWBQJLfwu4XfJwi/G7Fa0kRj0yDKqCGd63efEPab2QXgpQ1bQ/tEk+C9uwbDWYC5DkFGi8LgFp3K",
	"vUO+CJ5lZZWCBVpQtkylyfwl3d3dfa4EFMFsbuUCEy4gybTtDGtha+4giCjpHwdIegjy/S53IWZjAQIt",
	"BvlDz/pcf1S7VCFjcGm4jInxA6sIFmH/gvzFUkQPHzwrEcsQEXCGUjBZCsRTsOApQCLbfT7ITnpkqSKc",
	"o4ibvxnK4HKf6WBA1ySDsxlDM6hjNZ0ZSZtGLaf3FhAUzJCyvTTuzem1mq5UNHaUB1IjECaGLwRiV7BQ",
	"vnLbEMp3wbFiHoK05TZDBDEoEICAoxKqPyX5d/RMgWnNhj52k7ReeWtPwquZ9iIlyqcetCvbK28YshVm",
	"ITkwaz/S1WuZP05D+wo4OVI0/HeF2NKfxeBQa3Ho2JaSz9RW5zXsDP2yUpwjBVg7Tr80AId/hpnAV6j1",
	"EOeF2rKQuKbsy2dMZkwDj32C7ANMS/5Z7rj272uGhfy2gAKRbGl/s/+0P4s5o9VsXlbCvuE9sS9dw+Iz",
	"X5LssyE9Qy5M+LmAM/04tNBOpJvEOpePV1nccfJYM0DalKm4aJ7PKevxGLyGHGdxDV45DjCpY4GCGoVv",
	"T+80QIq5GUTadShtldmtMrtVZn/XvoQe6HFKdcRxYDwCmOgBK5dp03EJSa58BxXJESuWEgpyhxnahu7A",
	"jgXJN7QiIUpSAQtAqsVEM6hrr1YtjRZQd+Di6H4Y/UWaCCwkZyYfXGs9jbRj7jWcnyGYLyPD/dA3UOWd",
	"kBqPFN6lopbDY1jEBr7fP3Dd1grD50P5HEqBxyTHVzivJB62Z9LtbZS+fWI+ry0yO6+2OhRfDqf3FHiK",
	"smVWoJG+m/fu/XZeT8lQpiTRQFYv2kZyfLKKKcx0ppud2Xm1WEC2tNBq5uO9F9BQglJ4boUvl2BH29uH",
	"BEbKlPNOUPDmw+k7bxBvGqNrjSU+iAv1uCOQy1LtN83G3M5jFczzi8OLj+efL/5xevz544fz0+M3J29P",
	"jo+StPHLT8eH7y9++kfr6cXZ4Yfzk+MPF63nbw8/vm8/++nk9fHZh8OL46PkMqCWaSp780lbgBMUa19Y",
	"4oD5UYHtYOqCkvoMEjBBFvS1ukQAumnEd5IHCth/QNd9sfpoXN5g1TdF5ed4ghiBAoUMLuXF6GyhfE6r",
	"IpfkdB/nygmhX8dTgAUgCOXKpJoouJXGjLIwgzoCXgSz/E4pFzOGzv/6Hqg3ZHMVryP0XYjvMwPD4iRp",
	"73BVfru2XihbaiQQ9GiDemK8wSankMEFksurfAC5Th2ExWmDJft16uSQTbBgEvE84jXDrKXrx420A0W1",
	"qJUMFRTm7/GEQevdCdvSXofoRiDClWNCbrKF/VguoGlwJSPb2Jd81H5vX5adKfcbELQ32+9Va7Pv7Nwb",
	"85pSFuTz10au9O9y732HX4NnMzyDyjX1vHf4L3/cH5GheJsmb3DOjolgy0AyA85ZIJnk5OgMTAqafQHP",
	"0O5sNwW/JS/+8nL3xZ///+7+7v7ey1e/Jc/Xt/MKOEGF40HVGVLDG9K+1WhD+0IwTtSdVkMccrNNqC2h",
	"oy6rGJafPtPVnx8Ouy48D6/GroYWIru5gQI23+F1CuIWmjYBTaubt5a3lI91gnqN3DHQ5xAP+/v0Lji+",
	"QmwJsjkucs+kNvaqTv4l1H29Cy7m8ueGprT7jch5v5DXMNGVXHpmeEOWPML2AMl738gZslROOna5b5k4",
	"e0kp7kjHYwaN83IOeYB61qBQP/t+/bqXklETkwqwFOQhlj1Tz2vJC488BYiXKMOwKJYS0aaVxnBCtZm2",
	"1K9Fjaue6XjGeE0lX2CeqQ5Sl3+cajZVf9nIjTWA1KvWPaODd/Zl9eeMwdz8Tb4Qeq0jEwGLrW1u1wQJ",
	"+aGVf1wvW5CxlPC9w2JeTQ7LUpnkRaEmHQ0HYe+lk4Br8x0WP1UTcFiWwH8VqDxwX4j+/CoZFptmZ0Nz",
	"OEMl5VhQtowOf9Z6MeQENVNg7qX1Bh/oKjSBY7sHxI1GJZ52L6w3jY6A9mo6rh/fugvqSzQU/D2iWbVA",
	"ROjV/Hj2frwtUvdsnJTdfV7vdWeOeu0mMLf7YZ38b6HB0QMowRdBo04EdRZh3Bc+n3lS26B0Uc0w0QnR",
	"VREOKF0hxgdob18Z0ioNpZpLVX+s1qhLN9Pq5ZongrQU+TAQSgKISXj7KA+UCzKDxByp7IaYVgr0NLpa",
	"J9wzLg7jpyrY3hjKdE56WCO+MzBMkwb9uraL9ytQx6pUApzXzwQVlMy4tjm/MWTRWYANBS5aNGxNOhbR",
	"CCFpexMIMa85A+TOckDQRXupikPwqzRWYsnVq/Gu7XQdtr3LDWtFobDTiMuDJVfXANU/OC61TWHeho2g",
	"jkip0Dp6SMhOjuwA5Xt63YyBIbvRB3lUrzWBvl0c/DXdkCQElromaYsKq8jFyelbXAgkO17JGSE32JNT",
	"MLUfA2kUm4W0ZxC6kmGcN6OCQLUTKJh3M5D52xgb5gC5RLf2/t+idv1i1HlzEnakhDUya901KTGtiuJv",
	"MY1AnVR2DUS1Amlm/ouyaDPq11HthFUzNc2oWhZzJ7R8CHbXcY4f3HTrOFZYYHKi/34xmHcVOY3mUyNt",
	"kDi4is0gYzyO1glik/6Yp7FyYTyQvVLWR6cDL15n5wDMwWCFCgHkxQsY2vJOdIxQcum0tVaYW7O6WJri",
	"BKoR8EylVj0PjcbPyfAb8j4P6t+xSGbM2q6DiYFBhEOY/osd3oJshsTpekSSjesGHIXyipmKAxAX9Eru",
	"kXYCEWJZex1zwK+xyOa25oTNp+n2MgxkattwgU3vs8Z0PVfCuaOY4vBYBL8jSI3s2PCxWZ1i6LJOo0mk",
	"4c+9F9zhW5fwqUjkpXp6JtqYhE47z2DC09EY9rmCRdXKJW7OT1gFYXyGsGrT8+rqrJbOEtct209CQNeL",
	"nd78G6mHiZtYqEnfutCUq+O6dSj3887/Hlz+yeP51mftiUu7k8IS72Q0RzNEdtCNYHBHwJmi4xUscK7c",
	"ckkNk2pCp41QwECcXSU+tjF9rKM/GlwpG4GHdjyBwWXLux/tRZnHeWCkY5NnmsRwAZFBTvBmEFryWLOr",
	"UBkCjsmsQCMI0UWJLEOlkFrDGSQh9Svs1a4/A0x+J5dBM7bZYDHv6VQiyd+cfEey24uCXqMcyHdt08/w",
	"FJiKRJMCPV8tTxve/M2KfytTW0cVXI+qs0BfXT0Rk1iTOiiyapOhoK1RFyIdXXh+et0Jnbao3wwKhaO1",
	"qqROTxfmDdNFcIV7Wz2nFcsibXP1m90SGj15m47Vt704zueW421k+LmVUNZKNr6eQ3dQ3dAvo0QwWvCI",
	"47Z20b7H5EuIockXubV6wtn4aiQ5w8aEJKCfgOx10tsaQxldLBDJ4UCMvvliYKzgWa3QokUpls/D/akU",
	"/bi32ept0M/jUN8AzNsO6Eb/2VwBkKBAwC8IoOlU2+4BhVinzEfYUP+4J3XSGWXLdjf9fj0Rjc+rcwLW",
	"6d1gLI+73U6NVfLbtKBQ/l9FQu1raZLXx87srC5HOrWFjnk2fdsNuQ8KbAt+Qvze4aWazsH9Luauapr5",
	"xuXRPBF9cpQqZk/1oWhTusierHBaW/BkxfgEPjPC7lnjlfyPdgZ35za3hmztrfr28ws9ba3mqvOnfz/Z",
	"9sOlUIILu1JykJlV56S+STID/0GMAo6EwGTW5UJcOp/gYKZ2zH24WjKamfHo+kNDh1VNe+/xAgseyh8w",
	"e3mhXrClC7hgUJ0/lEQ0JHSHEYciVgt489r6PaOaW306wdVpsZpXiZjP1cZi6vmw9UHHfb+AN0f1IGxl",
	"rNjIXMouKNSbblweLXwVhCd+4cEfuyM2zTRQMhhcbg75JH72oEuLwMkJn5xOkQwd7ei21jhTADtqqD9O",
	"TPrGaXTq3nE6RWF4oJ3mxg60XYzIp25rEhF2SRts3SNpUcntPbjVDhioIy8WH7WfR0NWTq+Jwy2F3YSq",
	"SoUVR4FceI58UVw3C1alo317Q61VaIyu3UmIwqZyY9Sr0a0NpRL7/TOeupSrO+KpqqCoRnfBybRlgZuC",
	"ryWjVzhHeX+RLAOjoSJZu3d4RmEjJVnu6YjnBo9m3lklv3VzQs6ogAJ5lfy81Kr2jut4kKmPJCs26/+1",
	"S+ep6n8dJooX5Tvyv7On2cOdja/KFxLI8VjXDZnKJWyUaRsLaoMBz6Zu1xvxlNabOueCxVLXK/4Zk0rY",
	"vcyULf5hv503euQwgoCF/gLAqcoPnuNsXk/KpgvXp24AnqrZ6VO5/qhiu1U9/NhgQ2ujT1o97axFfw5P",
	"MmtRT2CcFXMKmRTL1iZkLOWGMfNEzJRAEXZMplQHgrRGd2pNi8PTEy9z7yB5sbu/u69yu0pEYImTg+QH",
	"9Uidm5urWe/5Vgjf+0obMZXbvfrYQLAwiamwoks6C4bRlYo1ulrP3qkDqWku4AxxrUnIT1w5ZU/UQ9aR",
	"3PxnKLgPqD4lcKiSlcaB7ndr3QUqd3uKJXYsTOa9fOx3oww3k3Aww1dIWhUu1ipFWTnpj2uKpI04zafR",
	"2U2NTqUeNUfZl/aJFk1DXGCxNJsMlo3KlbNegYOEtkNgtXzpbba+tKCPE1uRtNvbNJy9IYmpwfkaaYIj",
	"nxpqgLbiixlhfRwhNrDO3tld5ZkhVKtLNR67nJH+6+pW0Q4v0+bdKC/397/hOog+iXGhu1pCjEzYivRY",
	"mce2uZExujqveygq5w1uzA0PNijlHx5q1HFX0eyYPMnRvNK0DI3e0XyvcfGJ+ujF8EeBG2xu0+THX38N",
	"ORHRTYkyqTi4F51iMvyydqFXDIulkvIbVSLnkxS+A1Ur6FKyENcn7tURKBGGQMeuKm9iJjHDobdcj1Fa",
	"ct1PjUTgl7q8zm06COp644VluefrD0EfCZFrG1FZuD1OPharK0aUSyXeYOiOhhq52/10wTmoqm0GqO8X",
	"gDeLSQPL7GApti5jgSiQ1T8qY8T1swooRQf7O4cdo8AGoUfRpldcWyxtYaj+Jrk0p2GDRfZV5pq+/SJm",
	"yNh05a7m1S+/PUfEnqoAKxvrNc2XK8lur/tp+BzdbVPEzLbRQpMXGxtRSOa7Quv/7k7i8krZ79OqKJYP",
	"IbWv9v+yen/3rWHo2oMtOddsEBPBuFx7Skr9aWNtak0CPPNlY4dntET582/QL/a+zjq8cnJ0G1U7oIWO",
	"LDZR5RWuQiRWFj9v1LoZwKsuIPV4f54gIKWjx2gIFT6YFhhxaFVXsvjuCCtHeO9GYeX+Q2Klrdz08Fj5",
	"ap3+nirAat65Y4CdKMfpCEDVToK1PHDGv3Cn7javj7jC53nXgqbbiZ7jhn1qyjfh+9IeGHRrX1ZsgCEt",
	"/VE4tmJMeEdOLX0sbtB81INaxW40g+s6sra+q7bvCluZ7HqrGlinZXdFL5Rfl2ZNbGvWd7pbjOv29Q1Y",
	"15j6dxRG6MDfqMHGkG9FDXOz7rQ454YAsck9g8DY7G9OK1Ysz4I1hEqGM6TSvuRbdaJ4i7I+P9aZqLRq",
	"VEOz58KiR3gbbUaP8sJF6IbfBWVLXe8qmAS3oQPAgdJLqtLWz5SI+TANF/I1Eyh+91qXm9WVuhxhVyHj",
	"VVaGTqLWuXdXb04/8uFIuSG1bk5TOPW5onGJS2e+a5/i0/y90t4aqbi33WPje2yDZCP2Wvu+Wp0V91yb",
	"hjy03dr7H+sDB2Q2lMO88pbabq9nPxX2eJJXeB/lKjcLzCG35fkFDYeFHCk3tdWqabjxTxldPOXwUJwr",
	"3FZmc2s1BDR2MHsryOgTpSYBZ/AEqRcZHQSgQ8dZIa76nlBnMDzki14MbsbEf9xZlyHp3QUuRclkZAuI",
	"iT0D7RI067RtpazoZGAeixOd1mlcm1GetUfdzyPHTydkdAfnvta7ODx6kmpUovA9h64cEnXxxFaR8t2u",
	"7kDbd4IgfZEn2F7tfqXFAYAO7Szk0q2gruwVkaNXVmtp+wj8I9WsdTxrxHGsEarM6B56odE/Umeq/Nbn",
	"cVJrfOiDn/Ysklb1A8D4DokjPaLmgbVNQaSuF6Plop7p01J8RsCBoVoAFI5WWO+myrHOZv3OI3erx9EC",
	"B+xkVpC1r+YvF5otUMhoPkVsAYk+AK/f4X7E1h3GWpozzJaH/Rwvt8t7YtBQA6xyYIt0Q335WwYJoUKV",
	"6yY5JagrC0dqRBtVEozeYuGlxr5HGcS19BfUrE54oG6tv9Gd9ipeiLGxheqx5E8mgvlo9l3N0I3zC0EI",
	"GOdE9wuIKzmTresyYyEJPjkasSPmvZV64rgwbD+EdrqtaKsDaYb6dyvc+/epcdvSA3ZqTzT14bGY/L4W",
	"YUgbNfqhyObxXCqt8XrVSuIynco1mwPIdZUaWzBCsmUszWorz+qmHEWLjUvzvTsVes7sjb9HrM+XsIbf",
	"YP/B/Aa2CMwWu1ZUekwW1kj86lo/6wVHfAtoT5cZGAyYLCCBMy9IYsom8JWCIuabQHKBaTUc3XhthrhV",
	"hSRBfSo+JrUoVL0iwFZtXvC0Y28txsRZNFu4O92Hwi12RKtFW3qGuUW7NYIzLfjYzEFBAxAbhMO9r/qP",
	"YPp+Exlnui5Ya2ajcFG/qg3QVUDxHTKYuIXEO4XE8YMyK9nV7AJjsZz1aIzWNpB28fCinuLCw9st/K1p",
	"qPqCv0kI3AgCRsvyjUih6WSl+iC2UvJMu6UgNPrhpWayRmrCSCa0pNNnbAnHiJrp3cPyHYOqWgRH/Xjq",
	"z6PQMqO86hJ7TJmsDeT1aP6QnDJe54xXqovnGIY4f6tzxkFX06s/H8i7Y8mCbV1FcGQ+kKvqF8ejXWBb",
	"tdft2qPAUo4AzxgUkhkZyBHDV/a5f4qzhKrou7nqN5Ic9NrdqvAdA5WX0WQvQSaPxLM4DCNvTJVrW6fy",
	"njOD9CDO55SJPr3P3ub8SJKE1juj+eLl8EenDGWU6OvP36oo30NC2XBiUl31MoRmnlqoF3DNrKSQWrj3",
	"Vf/1bdkTRmB7kyckU66XFrGFx9aoHbs8hGmsl3ogT8My1ebTNEIYts3SWA+DXJJGP/5sLkejxokNpmi0",
	"wce3IvUNcKkUIKKvuwCa3VJb9r5Zs7kNP3Jcky0APU4Acv5C7/qHO4Wj/Q0rbCN0tW16ySYNyHdIuELb",
	"neBs04IcTi5pFu1tpph0MSmaYZL6VdZToDDVZM/CoqBZBJv0SLbI9CiRqS8vZn0suivjVbPSSqbr/mMw",
	"Xbd5KuupfSZNZRwQdozPDcYkPONzz7ukQNV115phN1Bq3S3u5Q723S9cbRJnNoUWXchyl0LYg8n+nRAG",
	"WXSV80gRC3cnxMNqTP7CB1DiTetaDQ+VtwrUaOzweCOoRZ25OL25+aYhjQEUuSOc2NP3m6g4UtDhf8Hw",
	"bIYYB9Abo74Vpb4lEwWvXtkFF+aIqC8pJgpQ89IVhh1xQvaQn74dxHUn11l5zrrKnL5KZottD6cJRS/z",
	"GaUOvQoGmzoMhwkW+OmWR3woDAoqMXrBHgSC6nqx9ZUyfc7zI+Mw94qVenfRxOtPx4KGur32FTm/6xqv",
	"vcbo/dh19+3oPuuyiPFzb9FjE0cTo5IYr5bad9uE146g4Fco3JVuplk+eNXEpvDhHRJbcPgdgcO3pFRZ",
	"nh5V6dnjl+71qbqdMZlPcR62vobvuKbROyQCQi6FuxOEW/+Si0Ew6r/OYosbTxU37vYGj+59jA9yeUcD",
	"pjroE9Cbthd4bLCU0hp606p3XqwBX+FrQ7fw9b3DV/91sg9yn8bK8PWk79R4bIez14Cv4CUZ3jrdUURs",
	"gQTDGffd203Mc0kk6rWtr/h+o+aG7g8EJc21D+CI+alxu/wWNAKgYcRsVKRr4WSt42JOLcU37GyWoj9j",
	"iO/odCMvNr5G1qQKVVVMHUk51Q2f//V9K5OphpEG8/hple4VXQW8kcLEU3U+rxSq4iqDZKZf0LUIr2BR",
	"yX+r7EszEv0sfC5adW2GynVllm2202PNw4yy1NNJzGyyWiMnqnUiIjbXbcbmpjM2h0h99xE/hrigDA0W",
	"9JVvKV+9Ogbo1Y4YdSDRnCIfcS6xm0CgB/iW0cW2lERr1CaZ9iGxsjGEZpGJx29CG97aHm38XvJDA0cT",
	"m4imkt0JFXPE+o4OrVz1wnCa7syIxwgYNxXG17qTzXyrr3ZAZUGXd3F1jO1FXwtVk7U+WK771imYK9WW",
	"fY+5ODME2OzNbOYqq4e9km2z0dAopwTuQHNrttrlZ6Z20TGRjeTdnv4+R1puTI0jyBBA+mUvCigZwwQt",
	"lBLgX+RlYH9CaYGgKlCJ8xAUtBfbcla7ofryscYiBtr8pXPHEb1WeQtueCnAU8CR8DoCmANKiqVHWkH1",
	"Ny0vO6kKfS+aYZnO+MpqUuDsUEF8nLJyiwBlAYm6bU1/szOFmdIHqBqZxiAkhonbvmosT1rDSNsr3iHj",
	"yveZWS5dpcqI5dbv+wqzocB7R7qHa3OaKyB9H++t+6gjIPVlyf7tnumYY7IDe04NtW6gXQW01b+r8tm9",
	"tMh0Yjv1nTuZqWWRNq0tf7j+cNx+P344A1fb87pxzxN/e3n7fwEAAP//rcdp0CPwAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
