// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "xata/services/branch-operator/api/v1alpha1"
	apiv1alpha1 "xata/services/branch-operator/applyconfiguration/api/v1alpha1"
	internal "xata/services/branch-operator/applyconfiguration/internal"

	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=xata.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AffinitySpec"):
		return &apiv1alpha1.AffinitySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BackupSpec"):
		return &apiv1alpha1.BackupSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Branch"):
		return &apiv1alpha1.BranchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BranchSpec"):
		return &apiv1alpha1.BranchSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BranchStatus"):
		return &apiv1alpha1.BranchStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterSpec"):
		return &apiv1alpha1.ClusterSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InheritedMetadata"):
		return &apiv1alpha1.InheritedMetadataApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PgBackRestSpec"):
		return &apiv1alpha1.PgBackRestSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PoolerSpec"):
		return &apiv1alpha1.PoolerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PostgresConfiguration"):
		return &apiv1alpha1.PostgresConfigurationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PostgresParameter"):
		return &apiv1alpha1.PostgresParameterApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RestoreSpec"):
		return &apiv1alpha1.RestoreSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScaleToZeroConfiguration"):
		return &apiv1alpha1.ScaleToZeroConfigurationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScheduledBackupSpec"):
		return &apiv1alpha1.ScheduledBackupSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("StorageSpec"):
		return &apiv1alpha1.StorageSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("WakeupRequest"):
		return &apiv1alpha1.WakeupRequestApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("WakeupRequestSpec"):
		return &apiv1alpha1.WakeupRequestSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("WakeupRequestStatus"):
		return &apiv1alpha1.WakeupRequestStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
