// Code generated by gen-scopes.go. DO NOT EDIT.

package spec

import "strings"

// GetScopes returns required scopes for a given route and method
func GetScopes(method, path string) []string {
	switch strings.ToUpper(method) {
	case "DELETE":
		switch path {
		case "/api-keys":
			return []string{"keys:write"}
		case "/organizations/:organizationID":
			return []string{"org:write"}
		case "/organizations/:organizationID/api-keys":
			return []string{"keys:write"}
		case "/organizations/:organizationID/invitations/:invitationID":
			return []string{"invite:write"}
		case "/organizations/:organizationID/members/:userID":
			return []string{"org:write"}
		case "/organizations/:organizationID/projects/:projectID":
			return []string{"project:write"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID":
			return []string{"branch:write"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository":
			return []string{"project:write"}
		}
	case "GET":
		switch path {
		case "/api-keys":
			return []string{"keys:read"}
		case "/organizations":
			return []string{"org:read"}
		case "/organizations/:organizationID":
			return []string{"org:read"}
		case "/organizations/:organizationID/api-keys":
			return []string{"keys:read"}
		case "/organizations/:organizationID/extensions":
			return []string{"org:read"}
		case "/organizations/:organizationID/githubapp/installations":
			return []string{"project:read"}
		case "/organizations/:organizationID/images":
			return []string{"org:read"}
		case "/organizations/:organizationID/instanceTypes":
			return []string{"org:read"}
		case "/organizations/:organizationID/invitations":
			return []string{"invite:read"}
		case "/organizations/:organizationID/invitations/:invitationID":
			return []string{"invite:read"}
		case "/organizations/:organizationID/limits":
			return []string{"org:read"}
		case "/organizations/:organizationID/members":
			return []string{"org:read"}
		case "/organizations/:organizationID/membership-limits":
			return []string{"org:read"}
		case "/organizations/:organizationID/projects":
			return []string{"project:read"}
		case "/organizations/:organizationID/projects/:projectID":
			return []string{"project:read"}
		case "/organizations/:organizationID/projects/:projectID/backups":
			return []string{"project:read"}
		case "/organizations/:organizationID/projects/:projectID/backups/:backupID":
			return []string{"project:read"}
		case "/organizations/:organizationID/projects/:projectID/branches":
			return []string{"branch:read"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID":
			return []string{"branch:read"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/credentials":
			return []string{"credentials:read"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository":
			return []string{"project:read"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/postgres-config":
			return []string{"branch:read"}
		case "/organizations/:organizationID/projects/:projectID/limits":
			return []string{"project:read"}
		case "/organizations/:organizationID/projects/limits":
			return []string{"project:read"}
		case "/organizations/:organizationID/regions":
			return []string{"project:read"}
		}
	case "PATCH":
		switch path {
		case "/organizations/:organizationID/projects/:projectID":
			return []string{"project:write"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID":
			return []string{"branch:write"}
		}
	case "POST":
		switch path {
		case "/api-keys":
			return []string{"keys:write"}
		case "/marketplace/register":
			return []string{"marketplace:write"}
		case "/organizations":
			return []string{"org:write"}
		case "/organizations/:organizationID/api-keys":
			return []string{"keys:write"}
		case "/organizations/:organizationID/deletion-request":
			return []string{"org:write"}
		case "/organizations/:organizationID/githubapp/installations":
			return []string{"org:write"}
		case "/organizations/:organizationID/invitations":
			return []string{"invite:write"}
		case "/organizations/:organizationID/invitations/:invitationID/resend":
			return []string{"invite:write"}
		case "/organizations/:organizationID/projects":
			return []string{"project:write"}
		case "/organizations/:organizationID/projects/:projectID/branches":
			return []string{"branch:write"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/credentials/rotate":
			return []string{"credentials:write"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository":
			return []string{"project:write"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/logs":
			return []string{"logs:read"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/metrics":
			return []string{"metrics:read"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/restore":
			return []string{"branch:write"}
		}
	case "PUT":
		switch path {
		case "/organizations/:organizationID":
			return []string{"org:write"}
		case "/organizations/:organizationID/githubapp/installations/:githubInstallationID":
			return []string{"org:write"}
		case "/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository":
			return []string{"project:write"}
		}
	}
	return nil
}

// GetAllScopes returns all unique scopes defined in the OpenAPI spec
func GetAllScopes() []string {
	return []string{
		"branch:read",
		"branch:write",
		"credentials:read",
		"credentials:write",
		"invite:read",
		"invite:write",
		"keys:read",
		"keys:write",
		"logs:read",
		"marketplace:write",
		"metrics:read",
		"org:read",
		"org:write",
		"project:read",
		"project:write",
	}
}
