// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bulk delete API Keys for the authenticated user
	// (DELETE /api-keys)
	DeleteUserAPIKeys(ctx echo.Context) error
	// List API Keys for the authenticated user
	// (GET /api-keys)
	ListUserAPIKeys(ctx echo.Context) error
	// Create a User API Key
	// (POST /api-keys)
	CreateUserAPIKey(ctx echo.Context) error
	// Register with a cloud marketplace
	// (POST /marketplace/register)
	RegisterMarketplace(ctx echo.Context) error
	// Get list of organizations
	// (GET /organizations)
	GetOrganizationsList(ctx echo.Context) error
	// Create a new organization
	// (POST /organizations)
	CreateOrganization(ctx echo.Context) error
	// Delete an organization
	// (DELETE /organizations/{organizationID})
	DeleteOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get organization details
	// (GET /organizations/{organizationID})
	GetOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update organization details
	// (PUT /organizations/{organizationID})
	UpdateOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Bulk delete API Keys for an organization
	// (DELETE /organizations/{organizationID}/api-keys)
	DeleteOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// List API Keys for an organization
	// (GET /organizations/{organizationID}/api-keys)
	ListOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create an Organization API Key
	// (POST /organizations/{organizationID}/api-keys)
	CreateOrganizationAPIKey(ctx echo.Context, organizationID OrganizationIDParam) error
	// Request organization deletion
	// (POST /organizations/{organizationID}/deletion-request)
	RequestOrganizationDeletion(ctx echo.Context, organizationID OrganizationIDParam) error
	// List invitations for an organization
	// (GET /organizations/{organizationID}/invitations)
	ListOrganizationInvitations(ctx echo.Context, organizationID OrganizationIDParam, params ListOrganizationInvitationsParams) error
	// Send an invitation to join an organization
	// (POST /organizations/{organizationID}/invitations)
	CreateOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam) error
	// Delete an invitation
	// (DELETE /organizations/{organizationID}/invitations/{invitationID})
	DeleteOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Get details of a specific invitation
	// (GET /organizations/{organizationID}/invitations/{invitationID})
	GetOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Resend an invitation
	// (POST /organizations/{organizationID}/invitations/{invitationID}/resend)
	ResendOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// List members of an organization
	// (GET /organizations/{organizationID}/members)
	ListOrganizationMembers(ctx echo.Context, organizationID OrganizationIDParam) error
	// Remove a member from an organization
	// (DELETE /organizations/{organizationID}/members/{userID})
	RemoveOrganizationMember(ctx echo.Context, organizationID OrganizationIDParam, userID UserIDParam) error
	// Get organization membership limits
	// (GET /organizations/{organizationID}/membership-limits)
	GetOrganizationMembershipLimits(ctx echo.Context, organizationID OrganizationIDParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAPIKeys(ctx)
	return err
}

// ListUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAPIKeys(ctx)
	return err
}

// CreateUserAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUserAPIKey(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUserAPIKey(ctx)
	return err
}

// RegisterMarketplace converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterMarketplace(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"marketplace:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterMarketplace(ctx)
	return err
}

// GetOrganizationsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationsList(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationsList(ctx)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganization(ctx, organizationID)
	return err
}

// GetOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganization(ctx, organizationID)
	return err
}

// UpdateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganization(ctx, organizationID)
	return err
}

// DeleteOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationAPIKeys(ctx, organizationID)
	return err
}

// ListOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationAPIKeys(ctx, organizationID)
	return err
}

// CreateOrganizationAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationAPIKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationAPIKey(ctx, organizationID)
	return err
}

// RequestOrganizationDeletion converts echo context to params.
func (w *ServerInterfaceWrapper) RequestOrganizationDeletion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestOrganizationDeletion(ctx, organizationID)
	return err
}

// ListOrganizationInvitations converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationInvitations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationInvitationsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameter("form", true, false, "email", ctx.QueryParams(), &params.Email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// ------------- Optional query parameter "first_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "first_name", ctx.QueryParams(), &params.FirstName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first_name: %s", err))
	}

	// ------------- Optional query parameter "last_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "last_name", ctx.QueryParams(), &params.LastName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter last_name: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameter("form", true, false, "first", ctx.QueryParams(), &params.First)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first: %s", err))
	}

	// ------------- Optional query parameter "max" -------------

	err = runtime.BindQueryParameter("form", true, false, "max", ctx.QueryParams(), &params.Max)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter max: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationInvitations(ctx, organizationID, params)
	return err
}

// CreateOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationInvitation(ctx, organizationID)
	return err
}

// DeleteOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// GetOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ResendOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) ResendOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ListOrganizationMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationMembers(ctx, organizationID)
	return err
}

// RemoveOrganizationMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveOrganizationMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveOrganizationMember(ctx, organizationID, userID)
	return err
}

// GetOrganizationMembershipLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationMembershipLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationMembershipLimits(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/api-keys", wrapper.DeleteUserAPIKeys)
	router.GET(baseURL+"/api-keys", wrapper.ListUserAPIKeys)
	router.POST(baseURL+"/api-keys", wrapper.CreateUserAPIKey)
	router.POST(baseURL+"/marketplace/register", wrapper.RegisterMarketplace)
	router.GET(baseURL+"/organizations", wrapper.GetOrganizationsList)
	router.POST(baseURL+"/organizations", wrapper.CreateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID", wrapper.DeleteOrganization)
	router.GET(baseURL+"/organizations/:organizationID", wrapper.GetOrganization)
	router.PUT(baseURL+"/organizations/:organizationID", wrapper.UpdateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID/api-keys", wrapper.DeleteOrganizationAPIKeys)
	router.GET(baseURL+"/organizations/:organizationID/api-keys", wrapper.ListOrganizationAPIKeys)
	router.POST(baseURL+"/organizations/:organizationID/api-keys", wrapper.CreateOrganizationAPIKey)
	router.POST(baseURL+"/organizations/:organizationID/deletion-request", wrapper.RequestOrganizationDeletion)
	router.GET(baseURL+"/organizations/:organizationID/invitations", wrapper.ListOrganizationInvitations)
	router.POST(baseURL+"/organizations/:organizationID/invitations", wrapper.CreateOrganizationInvitation)
	router.DELETE(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.DeleteOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.GetOrganizationInvitation)
	router.POST(baseURL+"/organizations/:organizationID/invitations/:invitationID/resend", wrapper.ResendOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/members", wrapper.ListOrganizationMembers)
	router.DELETE(baseURL+"/organizations/:organizationID/members/:userID", wrapper.RemoveOrganizationMember)
	router.GET(baseURL+"/organizations/:organizationID/membership-limits", wrapper.GetOrganizationMembershipLimits)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd727cOJJ/FZ7ugJngZLuTnfkwBha4zHpnzthkHCQbzOAyhpctVXdzLJEakrLdG/hw",
	"D3FPeE9yKFKUKIn603Y7cXb9zWlJZFXxV39YVWQ+RonIC8GBaxUdf4wKKmkOGqT51ym/YppqJvjpyRt8",
	"gj+moBLJCvw1Oo7ec/Z7CYSlwDVbMZBkJSShnLD62yiOGL5aUL2J4ojTHKLjiHljR3Ek4feSSUijYy1L",
	"iCOVbCCnOJ/eFvi+0pLxdXR7G0dnck05+/udCCOqgIStWEKEN0qYRNGaZ5TIf5Owio6jfz1qxHlkn6qj",
	"NrmGg/cK5N0pLxVIQpNElFyHKS/N+Hem2JIX3SKpElQhuAIDiJel3vxZSiHxH4ngGrjGP2lRZCwxHB79",
	"ppCLj95UcEPzIgP8Mwel6Lpaf5qxlLx8c0ouYRvdxlEhRQFSMzsXS/uiMXN3JaMlTS4ZXxPKU5LCslyv",
	"ESlxFzlxM3t33P8sc8oPJNCULjMgYKap3iZwU2SUcZxBb4AwpUroj37rC/tDPdV5/aJY/gaJtkINcSVB",
	"l5JDSq43wAkt9Qa5tEIlCIBSb4SscERWlGUKefqepm/h9xKU3n1hngTeCBxnklaQhCmS02wlZA4pih4F",
	"ShlXxIHWM5O3cfSOIbyfxD9X/D8CB8mSalpnYMyQlQUytubN6V9g+0bCFYPrvriWkvJkY/9uD/999YTo",
	"DVPOvpANVWgzQSmiBVpNDbkK+JeafiolNWYpkUA1pBfULCmiAv+KUqrhQLMcQpJ33yy3ffpOT4hYGdEa",
	"Q643VJPq/RbJaM7LLMMVcuZ7ZJ4L/GJkLieHe00HNwWTgWlOqIZGjdxU5m1Q5Gscl7AV4cL+tn0WxWFB",
	"TlJgtaT3c0aVvigVBHTorywHpWleOEnguwTnM/9CQq+pwrVIPUrhCuTdqbRuOEBn0cA58EygxgQQ/aZ6",
	"si9Eq0QUldGZ+U1H21nqYo2GpZai1FDxl6ae2OM1bhS5bzri6E9mSGsKKje3iyl4xXKmGyHhgisg9ftj",
	"Msvpzal9+O2iL8EhRfgz/m49NALG2utGJWJiAIa/1rrwECAbAlJYHt5i3FUeDaLaE56ZP2hG7AuEKsXW",
	"6HPt5J7tudvMHVwakQzjqBWJ1/uPQVxBTlkWWGP8mdA0lSjFlikXdtsD/praUab8p31rHukewW3Kqgek",
	"oNtM0NTgzCiliRYIh+vurqfNsENUe9SfaN4AOTDGOGODS/JDmWVWsZ+c+5Nzf3Lun8+5x5EWl8AD0t0A",
	"oYkuadYgzLw5pfR3jQ/c6DvHCa+pvARdZDSBt7BmSoOctJJaEFm9S66Z3hBKkkyUKcmbwXomkl4HlvDl",
	"z+8O6uyM9zVJQZt9em8Um7y5CO35Xv78ziV3iMnh9O1CqbTIQQ5+7kmDuJcHxiqkSMtEzxqqejc4UgcA",
	"PomtSWKf99BKJiIvKN9ehH3Rn+xTwn2f5Evcrqgc8E0YTDRrG8R7DwLI9hVLQSJoeZkje4iC88ktcQtG",
	"Lb7izggN+76fD4RT3lMHLsJ4kpUpuvjTE5MTqBWvn17YJU85IazXARFVS8JUK0YgX8Ph+pD8ikz/Gj2L",
	"0QYvWZYZHyVFuUbVa0trthEezWsYlFSOYTxoiSOlqS7VLjJ6Z78Ys33VoFMLfXpic+9ag0Q2PtCDv788",
	"+K/FwXcXB/99fP7vSC/TKI3uZ11G4ujmQNCCHSQihTXwA7jRkh5oujasmewV1Sb/WieV+jn1JnXfi8za",
	"8dKQM66jhSbLb/xw9fWQ6+2HJDtE4DbyTk3cNSP+rjwQqDuwUn05m40Vk0oPWLQf8FkLqR1GZkZNc2oI",
	"bTZClNq5LzLGLwODvn1F8Al6ToxNCj1jROPew6y/ovfk3Nfpi7sYuEbpO26mlBK4JvZ5izzHqHMFBfDU",
	"ap5FRTrtGIyF6NIe10Dth0kWpLPNyWvIlyDVhhVmvx/gr3mDZOYVV7Ub3R7iRtysUGhEesPyMie8xJFR",
	"YpVgPKkpQrNMXENKqCaCG0OfM47fRcfPGxs3a6wGa4xrWKMZM6mCirU5FOb21ZoqxkOeYh6FLX9XDRwg",
	"sRci1PTGvninVvhdjdtOXJnmjF9IoCoUPbw1v9eWIKlAbj6qoB7SYHTVjK93Hbb6bMbAQ1p4ylOWUG02",
	"+9DRxZa8V1LkhNYzFiAxGtfsCjxFFZdoUsRFQbc5cH2Rg96I1NRPrwRL4EJcgUxNqaPkl1xc4+KnkIHR",
	"0Ko0FFTveFev2CL+Ln4xZQoNo0kNmOUbEx4LSAy3l0sATtxIZLlF/beD1TMuhciA8mYTXqSGzpn7cPu6",
	"y/X5BHylGlzMY3kaJNcb0BuQfWYZbqURDTFh+itF0DWU6GeoIn/7l54sycufTkgbm+SPfyRficuv/ubh",
	"Cbj5LGpWIwiNUtE1XGiMs/oO1dTb8FkI1odEP0fa8fcUVrTMtM0cd1JwKib6hWHSJVdtBZm4WqXBO7F4",
	"x/dQY1gGhx4z+jnK/MW076pXrQ/BnkK3mO8gKGTh3quwkEASxi1KzHLW+x3jMWOyKrPMxBGx2f4UUiB7",
	"hOV03d8HzQopqVIiYSaLZjIDdT6v6bqYji9HsqleinBeAjUeSRBX3Rqz+0g6jMzadrx3DSV72m7geD8z",
	"vbF00yw7W0XHH6a7UqLbuF9y0cDTKmokViw2EWqBUrmP0krDvOQRs/s2uW6O6QV1/cU5N9VvBK9rDKCJ",
	"bjLtkSqLQkj9HzdU00MmTCqukvjLdgPIyzenURxdgVSW6+eHCxMBF8BpwaLj6A+Hi8OFXc6N4eQI1+US",
	"tpXNzEAH0Hhifid5mWlWZHV2V2EsRIlifJ3VbRFoL1BUNn5O669RIDaRr6qOI1D6e5Fu79UMEUqzSUm3",
	"qDsuGXl6YqpYljnydV5FZd8uLA8FSEf7s31VmJCwcI9Du9Wq2zn1YvFNgKE3pwTFVnGQElWalC8aNJOX",
	"/WaxGIJjPfpRtwPIfPd8+rummct88c30F36jy20cffvLLyGrAzcYfEFKqhfReUNSSqa3RscR7ChKXKPj",
	"a8k0ROe353GkyjynchsdR9+X2aVb1VpGLr70OqOaraK1OB9qiUbnt3G0hmD2V0sGV0AoyZjSHpzGpuhj",
	"/xVTuov81nov7gH/Rm3H8N8QXEmhRviY/Wr31UxV+g0lc5p6XnWFKStBf05U7wOhEmjaBahh9h7ILESo",
	"MGErvVWh1tm4XTBpB2hQeQ9zPIagUFPGLBP4/H4qMUWXV1EOwHgWiqtVqmuoXzZ0g8a1RpkJrCuGw0C9",
	"jaMjLy9/5MplZnWCEH7F+KUawKtJGwbqK6pc1kMckjOebYngw1Uds9OpMjbo4cOq4KqAr1tlhYfQhpHS",
	"4yylWIyXVlqsN3D81NHBd7tHB4sX91B3r3V1f42ng3Jt6leU4UZ+UK08UIa16+2MirLTNB+b57iVghuz",
	"YXFQQfVrbfRDFUumCPC0EIxrYlMSyuv54amJcvDv1kiGPMbJL7jxIGetR1Ta5gktioMMriAjqMfadZe4",
	"XmhXmo/rfjq7/dZAc5cBRb0cj8JMrqgKHWiWdagcMCRLyARfY+wfe9kAvQEmzZ7AFUHVIWkLyNgN0w4i",
	"zc4BQ6DwtFuyoRgkuhaMvoX5EXRLbhgT7DcKnFh7F3H1RWaENNhBcv+68BdffB0Nedtin2NXzv7yD79Z",
	"E3IdjIR/BF3rb1twjZ07awt0Iv5VgU7FJgsXsAZUEaaVS1aIaz4cGp+1cfhwwXGoXfO2f55q15B4rnYE",
	"QerL049r6+rDPwOGx0PiUHfrIIib79v+8zXldA05LmjPgx99bB8qvB1Lzn34SWhiJICDQUq2oM/JG5A5",
	"RUFlW5cj6RRuK69HE7PUCeVcaLIEUvJUcBhK4/V0Yyp7NQyoKp31qQH1hy8YgifBlRzF31gkWAW0itQr",
	"rcbOv8Y2MsIoqkrb0Cy25TvG13F10syWQk2k1iaTLLfGBJfdisN0/Geb2Ezxvanw0KUo9RCtbrLTk8mY",
	"7L7h2N7MrWvVeww5sS9GT4bCDRGQ7Hi04R1qH6gxNa8chU6XIxFFGcDxe1vh9sFbddLATWDfFeO6b1zE",
	"gnFqH8N2yD1FKg8V6/8E1+0e3IkzIcHYZ/EIYh9Xj35SwdmuqsL8zmoYjpfIWe2hZoRLn6yo6ZPYlHj2",
	"Y0k+W4n0qQi6by3bY21zOPS7f1FzIJQKVzUfFvqfrUbave/lqVb6BTqlHSqyM/Vpx1Jsd6s9I9FU12I/",
	"r/d4quh2Ar3+e7jIph+eSKDJxl7+4u58kbVc7lxy5a1Ky3TtdSIWcjvyA+mdYA/C+YeMrlWgb1rIelt/",
	"SP7avgFHwm9WJUP9w0qzLKtKDJpdNXcIHP7KcRy/pouDJZQnYE58sTyHlFEN2dakFSjfElFqpWnd4i9Y",
	"ArYMlYgss0TQUgvcYCUUo3a60oBebS3N6TOQTKS2PFVIuEIIkZwpjPSQP7o1qWK6Rv4KIQ2VJy6dgbBD",
	"b6wIVVuebKTgolSmCJ2AKQ61SDLX4aSGdAVaZ5Ae/soD5WcjR3+53YQP5UtfDATCyGPdvU7+73/+N9CC",
	"jou5ROnkAp1QzfngwlSsP34P9d2j2Ta5Y8edfVMNiqGN0wxD4B+LOf44FSJaRNdncgJezZZbhLu7Y8Uy",
	"DbhNIMtt1bYfu95rV2qdDiVPW2d39qACcf8oHdLZYq4m2N2T93sJ5tS5a8B1D73b6nY62DWPBvC7ywdI",
	"cX3kIzcfzptsVZ8oHJjJO464h+kyOj5bcwBwp8neAZXJJixIIccmVObL3WY75SncuGq1FaAEVWbVLQG6",
	"lJx8vThYUoXmcbVSYM9iFHTNuCHv2ZiwW8RUZzmi44V3uGwROis2fYTNEqkaKgeoyOlNmIbni4XZ+ldH",
	"3BaLzoG3Lk373cN1DNesPdnASeXJK6u8qXbZo/kAfNqmzXSC9iDv8EZtwv/coXfgHZhYsnVK29gK03To",
	"2g9/E4zfZQt36p/8fezbuPFbruZv67oWshasMkej/8E14DOEjpXWBKPHAL4H8Ly3UPLoo39H82inQrgn",
	"waNVQiJkOifZvm9Viyc/699yHfBy34xqxGNIXX85bmGiAaJ9n8SgH9hHX4GH0PldBY8UoQ9TTfUjrH6Q",
	"1FKBpxaHfcVIP4Ku5SlWYcA+lJlHfoGnw7nEt+Y5oYFLOVzT+0qC2thbcipXxUIZAjvSF2/8jcD0E9zv",
	"bvsdpPje8J03t8BUfmI8OdXcwvLo6pweK7P2x97R+qk9sRt6bo/7rt1aZq/nbtnptw3uZYmPPtr/7KIT",
	"n3YtTS6uoL/gn8rK+P/fxzz7YulzGfk7pZvxS0Ir+Vd35DzAAmxYcZDV90yNRmW2BJUHL58yV/xYN2fq",
	"bv71ge5gf31hE0/9FMKzyZCtdyPWo9DzuTFYj/rQ0bZBobYW/BP5l0/V/dmD0hiib+tn/VvKW03S7vhc",
	"7IJZ83eoG7p7rK5JuLZn76dyO1PmlNM1DudfzqL862y8sdGa7DKmazPxD8tZHgWP3fnAdpN3M1ldkp6c",
	"L2P8ss+CFhNHfj3G/AORt+e3/x8AAP///4w2VJ1qAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
