// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bulk delete API Keys for the authenticated user
	// (DELETE /api-keys)
	DeleteUserAPIKeys(ctx echo.Context) error
	// List API Keys for the authenticated user
	// (GET /api-keys)
	ListUserAPIKeys(ctx echo.Context) error
	// Create a User API Key
	// (POST /api-keys)
	CreateUserAPIKey(ctx echo.Context) error
	// Register with a cloud marketplace
	// (POST /marketplace/register)
	RegisterMarketplace(ctx echo.Context) error
	// Get list of organizations
	// (GET /organizations)
	GetOrganizationsList(ctx echo.Context) error
	// Create a new organization
	// (POST /organizations)
	CreateOrganization(ctx echo.Context) error
	// Delete an organization
	// (DELETE /organizations/{organizationID})
	DeleteOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get organization details
	// (GET /organizations/{organizationID})
	GetOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update organization details
	// (PUT /organizations/{organizationID})
	UpdateOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Bulk delete API Keys for an organization
	// (DELETE /organizations/{organizationID}/api-keys)
	DeleteOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// List API Keys for an organization
	// (GET /organizations/{organizationID}/api-keys)
	ListOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create an Organization API Key
	// (POST /organizations/{organizationID}/api-keys)
	CreateOrganizationAPIKey(ctx echo.Context, organizationID OrganizationIDParam) error
	// Request organization deletion
	// (POST /organizations/{organizationID}/deletion-request)
	RequestOrganizationDeletion(ctx echo.Context, organizationID OrganizationIDParam) error
	// List invitations for an organization
	// (GET /organizations/{organizationID}/invitations)
	ListOrganizationInvitations(ctx echo.Context, organizationID OrganizationIDParam, params ListOrganizationInvitationsParams) error
	// Send an invitation to join an organization
	// (POST /organizations/{organizationID}/invitations)
	CreateOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam) error
	// Delete an invitation
	// (DELETE /organizations/{organizationID}/invitations/{invitationID})
	DeleteOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Get details of a specific invitation
	// (GET /organizations/{organizationID}/invitations/{invitationID})
	GetOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Resend an invitation
	// (POST /organizations/{organizationID}/invitations/{invitationID}/resend)
	ResendOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// List members of an organization
	// (GET /organizations/{organizationID}/members)
	ListOrganizationMembers(ctx echo.Context, organizationID OrganizationIDParam) error
	// Remove a member from an organization
	// (DELETE /organizations/{organizationID}/members/{userID})
	RemoveOrganizationMember(ctx echo.Context, organizationID OrganizationIDParam, userID UserIDParam) error
	// Get organization membership limits
	// (GET /organizations/{organizationID}/membership-limits)
	GetOrganizationMembershipLimits(ctx echo.Context, organizationID OrganizationIDParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAPIKeys(ctx)
	return err
}

// ListUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAPIKeys(ctx)
	return err
}

// CreateUserAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUserAPIKey(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUserAPIKey(ctx)
	return err
}

// RegisterMarketplace converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterMarketplace(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"marketplace:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterMarketplace(ctx)
	return err
}

// GetOrganizationsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationsList(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationsList(ctx)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganization(ctx, organizationID)
	return err
}

// GetOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganization(ctx, organizationID)
	return err
}

// UpdateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganization(ctx, organizationID)
	return err
}

// DeleteOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationAPIKeys(ctx, organizationID)
	return err
}

// ListOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationAPIKeys(ctx, organizationID)
	return err
}

// CreateOrganizationAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationAPIKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationAPIKey(ctx, organizationID)
	return err
}

// RequestOrganizationDeletion converts echo context to params.
func (w *ServerInterfaceWrapper) RequestOrganizationDeletion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestOrganizationDeletion(ctx, organizationID)
	return err
}

// ListOrganizationInvitations converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationInvitations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationInvitationsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameter("form", true, false, "email", ctx.QueryParams(), &params.Email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// ------------- Optional query parameter "first_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "first_name", ctx.QueryParams(), &params.FirstName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first_name: %s", err))
	}

	// ------------- Optional query parameter "last_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "last_name", ctx.QueryParams(), &params.LastName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter last_name: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameter("form", true, false, "first", ctx.QueryParams(), &params.First)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first: %s", err))
	}

	// ------------- Optional query parameter "max" -------------

	err = runtime.BindQueryParameter("form", true, false, "max", ctx.QueryParams(), &params.Max)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter max: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationInvitations(ctx, organizationID, params)
	return err
}

// CreateOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationInvitation(ctx, organizationID)
	return err
}

// DeleteOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// GetOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ResendOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) ResendOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ListOrganizationMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationMembers(ctx, organizationID)
	return err
}

// RemoveOrganizationMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveOrganizationMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveOrganizationMember(ctx, organizationID, userID)
	return err
}

// GetOrganizationMembershipLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationMembershipLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationMembershipLimits(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/api-keys", wrapper.DeleteUserAPIKeys)
	router.GET(baseURL+"/api-keys", wrapper.ListUserAPIKeys)
	router.POST(baseURL+"/api-keys", wrapper.CreateUserAPIKey)
	router.POST(baseURL+"/marketplace/register", wrapper.RegisterMarketplace)
	router.GET(baseURL+"/organizations", wrapper.GetOrganizationsList)
	router.POST(baseURL+"/organizations", wrapper.CreateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID", wrapper.DeleteOrganization)
	router.GET(baseURL+"/organizations/:organizationID", wrapper.GetOrganization)
	router.PUT(baseURL+"/organizations/:organizationID", wrapper.UpdateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID/api-keys", wrapper.DeleteOrganizationAPIKeys)
	router.GET(baseURL+"/organizations/:organizationID/api-keys", wrapper.ListOrganizationAPIKeys)
	router.POST(baseURL+"/organizations/:organizationID/api-keys", wrapper.CreateOrganizationAPIKey)
	router.POST(baseURL+"/organizations/:organizationID/deletion-request", wrapper.RequestOrganizationDeletion)
	router.GET(baseURL+"/organizations/:organizationID/invitations", wrapper.ListOrganizationInvitations)
	router.POST(baseURL+"/organizations/:organizationID/invitations", wrapper.CreateOrganizationInvitation)
	router.DELETE(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.DeleteOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.GetOrganizationInvitation)
	router.POST(baseURL+"/organizations/:organizationID/invitations/:invitationID/resend", wrapper.ResendOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/members", wrapper.ListOrganizationMembers)
	router.DELETE(baseURL+"/organizations/:organizationID/members/:userID", wrapper.RemoveOrganizationMember)
	router.GET(baseURL+"/organizations/:organizationID/membership-limits", wrapper.GetOrganizationMembershipLimits)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xde2/cOJL/KjzdATPByXYnO/PHGFjgnPVOrrFJbCQbzOAyhpctVXczlkiFpGz3Bn2f",
	"/cCXREnUo+124uz5P6clkVXFXz1YVWS+RAnLC0aBShEdf4kKzHEOErj+15xeE4klYXR+eq6eqB9TEAkn",
	"hfo1Oo4+UPK5BERSoJIsCXC0ZBxhikj1bRRHRL1aYLmO4ojiHKLjiHhjR3HE4XNJOKTRseQlxJFI1pBj",
	"NZ/cFOp9ITmhq2i7jaMzvsKU/PNOhCFRQEKWJEHMGyVMImvMM0jkf3BYRsfRvx/V4jwyT8VRk1zNwQcB",
	"/O6UlwI4wknCSirDlJd6/DtTbMiLtopUDqJgVIAGxEkp13/lnHH1j4RRCVSqP3FRZCTRHB59EoqLL95U",
	"cIvzIgP1Zw5C4JVdf5yRFJ2cz9EVbKJtHBWcFcAlMXORtCsaPXdbMpLj5IrQFcI0RSksytVKISVuIyeu",
	"Z2+P+99ljukBB5ziRQYI9DT2bQS3RYYJVTPINSAiRAnd0be+sD9WU11UL7LFJ0ikEWqIKw6y5BRSdLMG",
	"inAp14pLI1SkAFDKNeMWR2iJSSYUTy9x+g4+lyDk7gvzJPBa4GombgSJiEA5zpaM55Aq0SuBYkIFcqD1",
	"zOQ2jt4TBe8n8U8V/yugwElip3UGRg9pLZC2Nefzv8HmnMM1gZuuuBYc02Rt/m4O/9I+QXJNhLMvaI2F",
	"spkgBJJMWU0JuQj4l4p+zDnWZinhgCWkl1gvqUKF+itKsYQDSXIISd59s9h06ZufIrbUotWGXK6xRPb9",
	"BsnKnJdZplbIme+BeS7VFwNzOTncazq4LQgPTHOKJdRq5KbSb4NAP6pxEVkiysxvm2dRHBbkKAVGSzo/",
	"Z1jIy1JAQIf+TnIQEueFk4R6F6n59L8UoTdYqLVIPUrhGvjdqTRuOEBnUcM58IwpjQkg+tw+2ReiRcIK",
	"a3QmftPSdpK6WKNmqaEoFVT8pakm9niNa0Xumo44+ose0pgC6+Z2MQWvSU5kLSS14AJQ9f6QzHJ8OzcP",
	"f551JdinCH9VvxsPrQBj7HWtEjHSAFO/VrrwECDrA1JYHt5i3FUeNaKaE57pP3CGzAsIC0FWyueayT3b",
	"c7eZW7jUIunHUSMSr/YfvbiCHJMssMbqZ4TTlCspNkw5M9se8NfUjDLmP81b00j3CG5SZh+gAm8yhlON",
	"M62UOlpAFG7au54mww5RzVHf4rwGcmCMYcZ6l+TXMsuMYj859yfn/uTcv51zjyPJroAGpLsGhBNZ4qxG",
	"mH5zTOnvGh+40XeOE95gfgWyyHAC72BFhAQ+aiUlQ9y+i26IXCOMkoyVKcrrwTomEt8ElvDkt/cHVXbG",
	"+xqlIPU+vTOKSd5chvZ8J7+9d8kdpHM4XbtQCsly4L2fe9JA7uWesQrO0jKRk4ay7wZHagHAJ7ExSezz",
	"HlrJhOUFppvLsC/6i3mKqO+TfImbFeU9vkkFE/XaBvHegYBi+5qkwBVoaZkr9hQKLka3xA0YNfiKWyPU",
	"7Pt+PhBOeU8duBChSVamysXPT3VOoFK8bnphlzzliLDeBERkl4SIRoyAfoTD1SH6QzH9R/QsVjZ4QbJM",
	"+yjOypVSvaa0JhvhwbyGRol1DMNBSxwJiWUpdpHRe/PFkO2zg44t9PzU5N6lBK7Y+IgP/nly8D+zg18u",
	"D/73+OI/Fb1EKmm0P2szEke3BwwX5CBhKayAHsCt5PhA4pVmTWevsNT51yqp1M2p16n7TmTWjJf6nHEV",
	"LdRZfu2H7dd9rrcbkuwQgZvIO9Vx14T423ogEHdgxX45mY0l4UL2WLRf1bMGUluMTIyaptQQmmyEKDVz",
	"X2aEXgUGffcaqSfKc6rYpJATRtTuPcz6a3xPzn2dvryLgauVvuVmSs6BSmSeN8hzjDpXUABNjeYZVKTj",
	"jkFbiDbtcQXUbphkQDrZnLyBfAFcrEmh9/sB/uo3UKZfcVW7we2h2ojrFQqNiG9JXuaIlmpkJTErGE9q",
	"AuEsYzeQIiwRo9rQ54Sq76Lj57WNmzRWjTVCJayUGdOpAsvaFApz82pFFaEhTzGNwoa/swMHSOyECBW9",
	"sS/esRV+X+G2FVemOaGXHLAIRQ/v9O+VJUgsyPVHFuohDVaumtDVrsPazyYM3KeFc5qSBEu92YeWLjbk",
	"veQsR7iasQCuonFJrsFTVHalTAq7LPAmByovc5Brlur66TUjCVyya+CpLnWU9IqyG7X4KWSgNdSWhoLq",
	"He/qFRvE38UvpkQow6hTA3r5hoRHAhJT28sFAEVuJLTYKP03g1UzLhjLANN6E16kms6J+3Dzusv1+QT8",
	"IGpcTGN5HCQ3a5Br4F1midpKKzTEiMgfBFKuoVR+Bgv0j3/ryBKdvD1FTWyiP/8Z/cCufviHhyeg+rOo",
	"Xo0gNEqBV3ApVZzVdai63qaehWB9iORzRbv6PYUlLjNpMsetFJyIkXyhmXTJVVNBRq5WqfGODN7Ve0pj",
	"SAaHHjPyuZL5i3HfVa1aF4IdhW4w30JQyMJ9EGEhAUeEGpTo5az2O9pjxmhZZpmOI2K9/Sk4U+whkuNV",
	"dx80KaTEQrCE6CyazgxU+by662I8vhzIpnopwmkJ1HggQWy7NSb3kbQYmbTt+OAaSva03VDj/Ubk2tCN",
	"s+xsGR1/HO9KibZxt+QigaY2akRGLCYRaoBi3UdppKFf8ojZfZtcNcd0grru4lzo6rcCr2sMwImsM+2R",
	"KIuCcflft1jiQ8J0Ks5K/KTZAHJyPo/i6Bq4MFw/P5zpCLgAigsSHUd/OpwdzsxyrjUnR2pdrmBjbWYG",
	"MoDGU/07ystMkiKrsrtCxUIYCUJXWdUWoeyFEpWJn9PqayUQk8gXtuMIhHzJ0s29miFCaTbO8UbpjktG",
	"zk91Fcswh37MbVT288zwUAB3tD/bV4VJERbucWi2WrU7p17MfgowdD5HSmyWgxSJUqd8lUHTedmfZrM+",
	"OFajH7U7gPR3z8e/q5u59Bc/jX/hN7ps4+jn338PWR24VcEXpMi+qJw3JCUncqN1XIFdiVKt0fENJxKi",
	"i+1FHIkyzzHfRMfRyzK7cqtaycjFl15nVL1VNBbnYyXR6GIbRysIZn8lJ3ANCKOMCOnBaWiKLvZfEyHb",
	"yG+s9+we8K/Vdgj/NcFWChXCh+xXs69mrNKvKZnS1PO6LUxuBf0tUb0PhHLAaRugmtl7ILNgocKEqfTa",
	"Qq2zcbtg0gxQo/Ie5ngIQaGmjEkm8Pn9VGKMLq+iHIDxJBTbVapqqN83dIPGtUKZDqwtw2GgbuPoyMvL",
	"H7lymV6dIIRfE3olevCq04aB+oooF9UQh+iMZhvEaH9VR+90bMZGefiwKrgq4JtGWeEhtGGg9DhJKWbD",
	"pZUG6zUcv3Z08Mvu0cHsxT3U3Wtd3V/jaa9c6/oVJmoj36tWHijD2vVuQkXZaZqPzQu1lYJbvWFxUFHq",
	"19johyqWRCCgacEIlcikJITX80NTHeWovxsjafIIRb+rjQc6azzC3DRPSFYcZHANGVJ6LF13ieuFdqX5",
	"uOqnM9tvCTh3GVCll8NRmM4V2dABZ1mLyh5DsoCM0ZWK/WMvGyDXQLjeE7giqDhETQFpu6HbQbjeOagQ",
	"KDztBq2xChJdC0bXwrwC2ZCbign2GwWOrL2LuLoi00Lq7SC5f134uy++Doa8TbFPsStnf/uX36wxvgpG",
	"wq9AVvrbFFxt586aAh2Jf0WgU7HOwgWsARaISOGSFeyG9ofGZ00cPlxwHGrX3HbPU+0aEk/VjiBIfXn6",
	"cW1Vffj/gOHhkDjU3doL4vr7pv98gyleQa4WtOPBj740DxVuh5JzH98yibQE1GCQog3IC3QOPMdKUNnG",
	"5UhahVvr9XCilzrBlDKJFoBKmjIKfWm8jm6MZa/6AWXTWV8bUH/6jiF4GlzJQfwNRYI2oBWoWmkxdP41",
	"NpGRiqJs2gZnsSnfEbqK7UkzUwrVkVqTTLTYaBNctisO4/GfaWLTxfe6woMXrJR9tLrJ5qejMdl9w7G9",
	"mVvXqvcYcmLfjZ70hRssINnhaMM71N5TY6pfOQqdLldEFGUAxx9MhdsHr+2kgdvAvitW6752EYuKU7sY",
	"NkPuKVJ5qFj/Ldw0e3BHzoQEY5/ZI4h9XD36SQUnuyqL+Z3VMBwvobPKQ00Il75aUdMnsS7x7MeSfLMS",
	"6VMRdN9atsfaZn/od/+iZk8oFa5qPiz0v1mNtH3fy1Ot9Dt0SjtUZCfq046l2PZWe0KiqarFflvv8VTR",
	"bQV63ffUIut+eMQBJ2tz+Yu784VXcrlzyZU2Ki3jtdeRWMjtyA+4d4I9COdfM7wSgb5pxqtt/SH6e/MG",
	"HA6fjEqG+oeFJFlmSwySXNd3CCiJsVIKiauOfUYSEIfojCZgj43og1/dJl2S55ASLCHbIEJN7YIsMjj8",
	"gwbqu5pQX56nlpOHclYveiJNRb2Tm+Pv8ZvuXx7NfsKdx21tKKrF7NtRTNAQ/7zI8Zex2CnLGodVAube",
	"1CGYu9RiSTIJKn5Gi43tZ49dU7KrQY7HWPPGoZY9QDfunjFTdDaYqwh2F8h9LkEfx3adqe6hd43bTiee",
	"ptEAftt1DymuwXrgSsBpky2ro3Y9M3nn9PYwXYaHZ6tPxu002XvAPFmHBcn40IRCf7nbbHOawq0r4xoB",
	"chBlZo/Py5JT9OPsYIGF8pbLpQBzSKHAK0I1ec+GhN0gxh5yiI5n3qmrWegQ1fjZLkOkqKnsoSLHt2Ea",
	"ns9mek9sz37NZq2TYG2a9ru5aRmuSZuVniO8o3c5eVPtsnnxAfi0f5noBM0J1/4dzIj/uUNR/T3QtHkf",
	"q7UVuhvP9eV9YoTeZW8z94/EPvb9zfD1T9P3O20LWQlW6DPD/+Ia8A1CR6s1wegxgO8ePO8tlDz64l9e",
	"PFjCDxfrPVo5JIynU7LQ+1a1ePSz7vXPAS/306BGPIac7vfjFkY6A5oXLfT6gX0U3D2ETi+3P1KEPkyZ",
	"0Y+wukFSQwWeav/7ipFegazkyZZhwD6UmVf8Ak37k2zv9HOEA7dVuG7wJQexNtfHWFdFQhkCM9J3b/y1",
	"wOQT3O9u+x2k6N7wndfXo1g/MZycqq8neXQFQI+VSftj78z52J7YDT21+XvXNia913PXz3T76fayxEdf",
	"zP8C0YpP25YmZ9fQXfCvZWX8/whjmn0x9CGuCU/vlG5WXyJs5W8vj3mABViT4iCrLmAajMpMbSYP3sqk",
	"774xbk4XpPx79dyJ9+omI5r6KYRnoyFb56qoR6HnU2OwDvWhM1+9Qm0s+FfyL1+rLbIDpSFEb6tn3eu7",
	"G93D7lxZ7IJZ/XeoTbh93qxOuDZn76ZyW1PmmOKVGs6/tUT497x4YytrssuYrv/CP0VmeGQ0dgfnmt3P",
	"9WRVrXZ0vozQqy4Lko2chfUY808Kbi+2/xcAAP//pMHb0LZpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
