// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bulk delete API Keys for the authenticated user
	// (DELETE /api-keys)
	DeleteUserAPIKeys(ctx echo.Context) error
	// List API Keys for the authenticated user
	// (GET /api-keys)
	ListUserAPIKeys(ctx echo.Context) error
	// Create a User API Key
	// (POST /api-keys)
	CreateUserAPIKey(ctx echo.Context) error
	// Register with a cloud marketplace
	// (POST /marketplace/register)
	RegisterMarketplace(ctx echo.Context) error
	// Get list of organizations
	// (GET /organizations)
	GetOrganizationsList(ctx echo.Context) error
	// Create a new organization
	// (POST /organizations)
	CreateOrganization(ctx echo.Context) error
	// Delete an organization
	// (DELETE /organizations/{organizationID})
	DeleteOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get organization details
	// (GET /organizations/{organizationID})
	GetOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update organization details
	// (PUT /organizations/{organizationID})
	UpdateOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Bulk delete API Keys for an organization
	// (DELETE /organizations/{organizationID}/api-keys)
	DeleteOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// List API Keys for an organization
	// (GET /organizations/{organizationID}/api-keys)
	ListOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create an Organization API Key
	// (POST /organizations/{organizationID}/api-keys)
	CreateOrganizationAPIKey(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing checkout session
	// (POST /organizations/{organizationID}/billing/checkout-session)
	CreateBillingCheckoutSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get billing customer details
	// (GET /organizations/{organizationID}/billing/customer)
	GetBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update billing customer details
	// (PATCH /organizations/{organizationID}/billing/customer)
	UpdateBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// List billing invoices
	// (GET /organizations/{organizationID}/billing/invoices)
	GetBillingInvoices(ctx echo.Context, organizationID OrganizationIDParam, params GetBillingInvoicesParams) error
	// Get upcoming billing invoice
	// (GET /organizations/{organizationID}/billing/invoices/upcoming)
	GetBillingUpcomingInvoice(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing payment method session
	// (POST /organizations/{organizationID}/billing/payment-method-session)
	CreateBillingPaymentMethodSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Request organization deletion
	// (POST /organizations/{organizationID}/deletion-request)
	RequestOrganizationDeletion(ctx echo.Context, organizationID OrganizationIDParam) error
	// List invitations for an organization
	// (GET /organizations/{organizationID}/invitations)
	ListOrganizationInvitations(ctx echo.Context, organizationID OrganizationIDParam, params ListOrganizationInvitationsParams) error
	// Send an invitation to join an organization
	// (POST /organizations/{organizationID}/invitations)
	CreateOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam) error
	// Delete an invitation
	// (DELETE /organizations/{organizationID}/invitations/{invitationID})
	DeleteOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Get details of a specific invitation
	// (GET /organizations/{organizationID}/invitations/{invitationID})
	GetOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Resend an invitation
	// (POST /organizations/{organizationID}/invitations/{invitationID}/resend)
	ResendOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// List members of an organization
	// (GET /organizations/{organizationID}/members)
	ListOrganizationMembers(ctx echo.Context, organizationID OrganizationIDParam) error
	// Remove a member from an organization
	// (DELETE /organizations/{organizationID}/members/{userID})
	RemoveOrganizationMember(ctx echo.Context, organizationID OrganizationIDParam, userID UserIDParam) error
	// Get organization membership limits
	// (GET /organizations/{organizationID}/membership-limits)
	GetOrganizationMembershipLimits(ctx echo.Context, organizationID OrganizationIDParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAPIKeys(ctx)
	return err
}

// ListUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAPIKeys(ctx)
	return err
}

// CreateUserAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUserAPIKey(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUserAPIKey(ctx)
	return err
}

// RegisterMarketplace converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterMarketplace(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"marketplace:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterMarketplace(ctx)
	return err
}

// GetOrganizationsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationsList(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationsList(ctx)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganization(ctx, organizationID)
	return err
}

// GetOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganization(ctx, organizationID)
	return err
}

// UpdateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganization(ctx, organizationID)
	return err
}

// DeleteOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationAPIKeys(ctx, organizationID)
	return err
}

// ListOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationAPIKeys(ctx, organizationID)
	return err
}

// CreateOrganizationAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationAPIKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationAPIKey(ctx, organizationID)
	return err
}

// CreateBillingCheckoutSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingCheckoutSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingCheckoutSession(ctx, organizationID)
	return err
}

// GetBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingCustomer(ctx, organizationID)
	return err
}

// UpdateBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBillingCustomer(ctx, organizationID)
	return err
}

// GetBillingInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingInvoices(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBillingInvoicesParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingInvoices(ctx, organizationID, params)
	return err
}

// GetBillingUpcomingInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingUpcomingInvoice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingUpcomingInvoice(ctx, organizationID)
	return err
}

// CreateBillingPaymentMethodSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingPaymentMethodSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingPaymentMethodSession(ctx, organizationID)
	return err
}

// RequestOrganizationDeletion converts echo context to params.
func (w *ServerInterfaceWrapper) RequestOrganizationDeletion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestOrganizationDeletion(ctx, organizationID)
	return err
}

// ListOrganizationInvitations converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationInvitations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationInvitationsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameter("form", true, false, "email", ctx.QueryParams(), &params.Email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// ------------- Optional query parameter "first_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "first_name", ctx.QueryParams(), &params.FirstName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first_name: %s", err))
	}

	// ------------- Optional query parameter "last_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "last_name", ctx.QueryParams(), &params.LastName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter last_name: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameter("form", true, false, "first", ctx.QueryParams(), &params.First)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first: %s", err))
	}

	// ------------- Optional query parameter "max" -------------

	err = runtime.BindQueryParameter("form", true, false, "max", ctx.QueryParams(), &params.Max)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter max: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationInvitations(ctx, organizationID, params)
	return err
}

// CreateOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationInvitation(ctx, organizationID)
	return err
}

// DeleteOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// GetOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ResendOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) ResendOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ListOrganizationMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationMembers(ctx, organizationID)
	return err
}

// RemoveOrganizationMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveOrganizationMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveOrganizationMember(ctx, organizationID, userID)
	return err
}

// GetOrganizationMembershipLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationMembershipLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationMembershipLimits(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/api-keys", wrapper.DeleteUserAPIKeys)
	router.GET(baseURL+"/api-keys", wrapper.ListUserAPIKeys)
	router.POST(baseURL+"/api-keys", wrapper.CreateUserAPIKey)
	router.POST(baseURL+"/marketplace/register", wrapper.RegisterMarketplace)
	router.GET(baseURL+"/organizations", wrapper.GetOrganizationsList)
	router.POST(baseURL+"/organizations", wrapper.CreateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID", wrapper.DeleteOrganization)
	router.GET(baseURL+"/organizations/:organizationID", wrapper.GetOrganization)
	router.PUT(baseURL+"/organizations/:organizationID", wrapper.UpdateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID/api-keys", wrapper.DeleteOrganizationAPIKeys)
	router.GET(baseURL+"/organizations/:organizationID/api-keys", wrapper.ListOrganizationAPIKeys)
	router.POST(baseURL+"/organizations/:organizationID/api-keys", wrapper.CreateOrganizationAPIKey)
	router.POST(baseURL+"/organizations/:organizationID/billing/checkout-session", wrapper.CreateBillingCheckoutSession)
	router.GET(baseURL+"/organizations/:organizationID/billing/customer", wrapper.GetBillingCustomer)
	router.PATCH(baseURL+"/organizations/:organizationID/billing/customer", wrapper.UpdateBillingCustomer)
	router.GET(baseURL+"/organizations/:organizationID/billing/invoices", wrapper.GetBillingInvoices)
	router.GET(baseURL+"/organizations/:organizationID/billing/invoices/upcoming", wrapper.GetBillingUpcomingInvoice)
	router.POST(baseURL+"/organizations/:organizationID/billing/payment-method-session", wrapper.CreateBillingPaymentMethodSession)
	router.POST(baseURL+"/organizations/:organizationID/deletion-request", wrapper.RequestOrganizationDeletion)
	router.GET(baseURL+"/organizations/:organizationID/invitations", wrapper.ListOrganizationInvitations)
	router.POST(baseURL+"/organizations/:organizationID/invitations", wrapper.CreateOrganizationInvitation)
	router.DELETE(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.DeleteOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.GetOrganizationInvitation)
	router.POST(baseURL+"/organizations/:organizationID/invitations/:invitationID/resend", wrapper.ResendOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/members", wrapper.ListOrganizationMembers)
	router.DELETE(baseURL+"/organizations/:organizationID/members/:userID", wrapper.RemoveOrganizationMember)
	router.GET(baseURL+"/organizations/:organizationID/membership-limits", wrapper.GetOrganizationMembershipLimits)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w97W4cN5Kvwus7IDGuR5Id50cELHC2tfEJa8eCHSPBOcIsp7tmhlE32SHZkmYNHe4h",
	"7gnvSQ786mZ3sz9mNLKljX5ZnuFHVbGqWKyv+RwlLC8YBSpFdPw5KjDHOUjg+n+n9JJILAmjpydn6hv1",
	"YQoi4aRQn0bH0UdK/igBkRSoJEsCHC0ZR5giUs2N4oiooQWW6yiOKM4hOo6It3YURxz+KAmHNDqWvIQ4",
	"Eskacqz2k5tCjReSE7qKbm7i6B1fYUr+sRNgSBSQkCVJEPNWCYPIGvsMAvlvHJbRcfSvhzU5D8234rAJ",
	"rsbgowC+O+SlAI5wkrCSyjDkpV5/Z4gNeNGNApWDKBgVoBniRSnXf+WccfWfhFEJVKo/cVFkJNEYHv4u",
	"FBafva3gGudFBurPHITAK3v+OCMpenF2ii5gE93EUcFZAVwSsxdJu6TRe7cpIzlOLghdIUxTlMKiXK0U",
	"p8Rtzonr3dvr/meZYzrjgFO8yACB3saORnBdZJhQtYNcAyJClNBd/cYn9qdqq/NqIFv8Dok0RA1hxUGW",
	"nEKKrtZAES7lWmFpiIoUA5RyzbjlI7TEJBMKp5c4fQ9/lCDk9gfzSPCa4GonbgiJiEA5zpaM55Aq0iuC",
	"YkIFckzrqcmbOPpAFHs/kn8q+V8DBU4Su61TMHpJq4G0rjk7/RtszjhcErjqkmvBMU3W5u/m8i/tN0iu",
	"iXD6Ba2xUDoThECSKa0pIReB+6WCH3OOtVpKOGAJ6RzrI1Vcof6KUixhJkkOIcq7OYtNF77TE8SWmrRa",
	"kcs1lsiOb4Cs1HmZZeqEnPoe2GeuZgzs5ehwq+3guiA8sM0JllCLkdtKjwaBvlXrIrJElJnPNk+iOEzI",
	"UQiMlHQ+zrCQ81JAQIZ+JjkIifPCUUKNRWo//T8F6BUW6ixSD1K4BL47lOYaDsBZ1Owc+I4piQlw9Jn9",
	"Zl8cLRJWWKUzcU5L2knqbI0apYagVKziH021sYdrXAtyV3XE0UuSZYSuXq0huWCl/ABCEEbfO5XR0Qol",
	"z7rk+yA5KQAldhEkzCro4/s3/gmXnIyqObX+EJwcUiIDygpnmCYBRfwecqtqEz0V2ZEHDdZjpWK2alta",
	"5gvgWh6XS0gkuYS5Ys8xuXRbQMJyUByvePigj8l7hH+bnawCiNUdqiVLXV/mO2EUUcoQZW7gwb61Qo6v",
	"SV7mc0KJJDib9x7DqRnQOgS0gCXjgDDdKGKtpp6KkFiW+tyBlrliG6wPSfE90JTQ1bzAm1zZCOdjDKcl",
	"zcHdOfDmofQjXME0yrsnILVl2WFhg8Lcnl6XhK/ssV4RuUZmMDKbxggjDjhZQ4oq+JGCOEYFE0T/10Ia",
	"a6OGMlQoJW2QO/B129CzpSmEAb2X4o2Yl1SSbK61UgOnef/lthFIz6qvD4ugz+ebms2dHHBlPSlslqUs",
	"FSMFZh308zehElaGpdqQ22NXxO7n6hDgjuAzx+NbojA8fxoyg7TfTQF4RNnLIh3K7raiZBJn867oTFAi",
	"ZmpGlqA222pyS4X0rNQk2gD2cVv2h06wB+eJsjeN0YeUWCkky4H3WwgLM3CuLt6sQU7zSdjIVjCmtWqc",
	"rIWcOq1WaVpdt9NmsMRlJt1dMs9Brpm+CHGWvVtGx58mbXBmpr81s2/O26+1n9eArAVld0QJ5uoNrOch",
	"s21sNAajWl8kjC7JquSQan3OQXICl87caIrNTRytsQhg0QKDl76BYc/ZGMHIvMrHoTyoj3fBWAaYdqSl",
	"yR9B2HpJXx9yh2kGePaUXjKSBFgV56ykcp6WId0OCclxhswYlJZTjZOk5BxosgkaTD12FDEQVqbfNHvR",
	"zbJ7Dy1cpEv1/ag+7VpWKcdL7QQVotRPjAJrk+mS6X/EhiaQTjSzWgDH/gF4hGvRo4Kqic74gYt+JZVi",
	"ibdVFI6NApqiwCtCtRdKcSp2qw8telZNeetmtGmmPwwvPoB8U910MFdCOxHhxkqv1Lw2hHqxqbC8sjt3",
	"3UxhobA3U86oXHsDPDvHjtgA5uEB6oZ7Ho5xNFSShsENb+3c3GYqsrd6SDd16h0+pz8WCctr1u6H9m40",
	"5S5+vyHtumZCree0hCVxi2DjOrBcaBOrH1M3YiKeEvMVyC2V+wgI0/dvi6zvQ+rTvz7EHkEcVEFKh9js",
	"ld7MOJptEGUbR/MbkhNZu+CUYSIAVeOHPHI5vj41X35/1NXXfS/Rv6rPTfxH4W6iAbXDNa6dLJWn9S5c",
	"mH1uyjA9PFffrvSo/ZXNDd/pPxTH6wEIC0FWFFK7uefZ3m3nFm9qkvTzUSPOW0W3e/mqeoC0zlh9jHCa",
	"ckXFRqCAmaA6+Gfa82hpQW5GTQPdA7jtqzTRsQJvMoZT58zDUseiEIWrdky9ibDjqOaqP+G8ZuTAGsOI",
	"9R7Jj2WWGcF+DB09ho4eQ0dfL3SkbuULoAHqrrVHtMRZzWF65KTH2g7RJ7f61lGot5hfgCwyrGzQFRES",
	"+KiWlAxxO9b6xFGSsTJFeb1YR0Xiq8ARvvjlw6zK/fFmI+db6KxiUoPmoYyCF798cKlDSGcIBUxY41rp",
	"ne5Ro/bDhNcqOEvLRE5ayo4NrtQ2Ej0QG5vEPu6hk1SvSUw38/Bd9Mp8i6h/J/kUNyfKe+4mZUzUZxvk",
	"9w4LKLQvSardDVW06EqMeyyabNTAK26tUKPv3/MBc8r71jEXIjTJylRd8acnJjjjBK+bvLJNFtwIsd4G",
	"SGSPhIiGjYC+hYPVAfpNIf1b9CRWOnhBskzfUZyVKyV6TWpNVsKDWTOaS+zFMGy0+I6rqTT6YGYM6b6B",
	"mF6L2jqzU0rgCo1PePaPF7P/Opr9MJ/99/H5vyt4iVTUaE9rIxJH1zOGCzJLWAoroDO4lhzPJF5p1LQX",
	"Vr8iozplqZuxWSeGdr0/DXup7zKurIU6h1Tfw3b29ID2Fha4sbxTbXdNsL/tDQRiB1TszMloLAkXskej",
	"/ai+a3BqC5GJVtOUDNUmGj0eYSJhnhF6EVj0/RukvlE3p7JNCjlhRX29h1F/g2+JuS/T810UXC30rWtG",
	"ezKkDY83wHOIuqvA5gs4i2ayK7sNe1wxatdMMkw6WZ28hXwBXKxJod/7AfzqESjTQ1xO+ODzUD3E9QmF",
	"VjR5Dcg4jRTFLGE8qgmEs4xdQYqwRMwELnNC1bzo+Gmt4yatFYXi1jm+tqhNgTA3QyuoCA3dFNMgbNx3",
	"duEAiB0ToYI39sk7dsIfKr5t2ZVpTuicAxYh6+G9/rzSBIllcj0JVSGSjpS5eNuWy9ppExbuk8JTmpIE",
	"S/3Yh5YsNui95CxHuNqxAK6scZvQ4wSVXSiVwroRQeeDZJfAjSOzpBeUXVEdRsxAS6hNPA6Kd7ztrdgA",
	"fpd7MSU6M0y7BvTxDRGPBCimnpcLAIrcSmixUfJvFuuGYN0zrUg1nBPf4Wa48/X5AHwjar6YhvI4k1yt",
	"Qa6Bd5Elwub1xIjIbwRSV0Op7hks0N//pUNL9OKnE9TkTfSXv6Bv2MU3f/f4CaieFtWnEWQNnZY2l8TE",
	"V1sXqs7mVt+F2PoAyacKdvW5i5hrz3HLBSdiJJ9pJJ1z1dQnIJcJ34gFKducoiUxgX6HjHyqaP5s/O6q",
	"Tq3Lgh2BbiDf4qCQhgtENDsabo3FPGfcd8B4TErhWs6TkguT5z9iQLRQq5ZurhOC9KPGopPR0hef2Dah",
	"ZTDhIQiPCLMXcESo2U0LQvVS1EvFaFlmmbbATFZfwZliDERyvOq+ICcZ41gIlhDtf9Q+lcoTWldDjVvm",
	"A35oz7k6zfUcR8NkM2+vafVdLUQmPdg+ukKvPT3U1Hq/ELk2cE/LI9LscRN3g1USaGrtbWTIYlzIhlHs",
	"xVsaauhBHjDbOxiqorWOOdw9nHNdlaKY1xXs4ETWMYpIlEXBuPyPayzxAWHaiWkp/qJZmPXi7DSKo0vg",
	"wmD99OBIvx0KoLgg0XH03cHRwZE5zrXG5FCdywVs7G2TQTCdWn+O8jKTpMgqv7hQViRGgtBVVpUrKU2r",
	"SGVeHmk1WxHEhECErQQEIV+ydHOrIqWQg5JzvFGy49y4pyc6/meQQ9/arGT0/ZHBoQDuYH+yr9icAixc",
	"e9QsgWxXND47eh5A6OwUKbJZDFIkSu0sVwpNe7SfHx31sWO1+mG7Mk/Pezo+ry6y1DOej8/wC9Bu4uj7",
	"X38NaR24VmYrpMgOVGYPJCUncqNl/FpfiZ8idUbHV5xIiM5vzuNIlHmO+SY6jl6W2YU71YpGzjL3Khbr",
	"R7bROJ8qikbnN3G0gqDfXOcIAsIoI0J67DS0RZf33xAh25zfOO+jW7B/LbZD/F8DbKkwKY2rWe82VoGj",
	"IZlSbPemTUybjPlVuXofHMoBp20G1cjegjMLFgrpmBi5DXE7HbcNT5oFaq68hToe4qBQOsskFfj0diIx",
	"BpcXiw+w8SQutqdURZ8fNusGlWvFZdqwtgiHGfUmjg69iMahCzTq0wmy8BtCL0QPv2qHayAyJcpFtcQB",
	"ekezjU7v7ouH6Tei9XWpGz4sCi5++rYRkLkLaRgI2k4SiqPhoFQD9Zodv7R18MP21sHRs1uIu1dSvr+C",
	"8F661pE/TDJI+8XKY8qwdL2fEIt3kubz5rl6SsG1frA4VlHi13CRhGK9RCCgacEIlcg4c4SXLUVTbeWo",
	"vxsrafAIRb+qhwd61/gKc5N2Ilkxy+ASMqTkWLq8HNejwCU1xFUmonl+S8C58x0ruRy2wrSXzZoOOMta",
	"UPYokgVkjK6U7R973gC5BsL1m8CFj8UBahJI6w2dSMP1y0GZQOFtN2iNlZHokle6GuY1yAbdlE2wXytw",
	"5OydxdUlmSZSb+7N7SPqDz5sPWjyNsk+Ra+8+9s//WON8VXQEn4NspLfJuFqPfeuSdAR+1cEcjxrL1xA",
	"G2CBiBTOWcGuaL9p/K7Jh3dnHIcSXW+6fY62NYmnSkeQSX16+nZtFbf5M/DwsEkcygvuZeJ6fvP+fIsp",
	"XoEuu+/c4Iefm82+boacc59+YhJpCqjFIEUbkOfoDHiOFaGyjfORtELe9tbDiT7qBFPKJFoAKmnKKPS5",
	"8TqyMea96mco68760gz13QNmwZPgSQ7y35AlaA1agaqTFkN96WJjGSkrytXQZrEJfBK6im0HKBNE1pZa",
	"E0y02GgVXLYjDuP2n0n/02kLdYQHL1gp+2B1m52ejNpktzXH9qZuXZLjffCJPRg56TM3WICyw9aG12yy",
	"J8ZUDzkMdX1UQBRlgI9NCLXBvDYHCa4D765YnfvaWSzKTu3ysFlyT5bKXdn6P8FVM3t5pJomaPsc3QPb",
	"x0XyH0Vw8lVleX5rMQzbS+hddUNNMJe+WFDTB7EO8exHk3y1EOljEHTfUrbH2Ga/6Xf7oGaPKRWOat4t",
	"63+1GGm7D/NjrPQBXkpbRGQnytOWodj2U3uCo6mKxX7d2+Mxotsy9Lrj1CHrSoKqjyDjVS9mXtFl55Ar",
	"bURaxmOvI7aQzag8dA1HZ7ZDSn94tvaw9vUq1TXGujJGkksFtO5u5XLSt5CAcEfV+3GRTGmH1tMJNsBh",
	"dkaXll/Jr/rdl800GPeqLnoI5DG+peG0MOiAJNgkZoXPoKEkaqBcZbHz0Th7wVpMWgkMsftrkK0U6ofD",
	"5O0uhkPc3aLTn9T51Mc2E3lZ5+cm6z5H0h7ZMpjcf6+NkMFyhOmpNF9dQB5dSru6lG4pXFtcFLZaTmxx",
	"Ubgpt7ggXEPG/YhhpxKirjxCpurHlRTq5iWsFPVvYNhf8/mjBN29xJYj2FqhwV9F6niCq+LRikCSoSUo",
	"LRfeRVvYjU1sXVh0/Oyo6i0eHT89OmrVrbbLUL/AFdnpoTmgASqmepT8qVeqfra3JezuxP2wtJ0eJ8i9",
	"TqSyw9sgjuiAb0TVmb6Z29rJs6voJ5lNOJMoZ0LqDNjQGgPapdXF8sFYoX3dNwOS9rHnPP6kxmgfe+5f",
	"gGz57cyU3+7gaBAgy2KWs3TI55Bqh4utt27nGHQ7bA+4HUJNaB+MQAx20B24f3r65T66IZpuiDCZ9icz",
	"LlFmxr1S6qCU/JjhlQg0gmC8yrY5QD83fzCOw++GHqGGCEKSLLOZv/rucEnaB79RtY5/lej++ZgmoFtY",
	"kTyHlGAJ2UZn+2C6QayUQuKqZ4kx7tStlbAsM0DgUrIcS5LgTE1cSuAIoxXX7bSAE5aarHFlgarDRzkR",
	"Qq2XQoY3OoMTrxR+BeMayhOXZaQYJgOtQ8SGJmvOKCuFrg1JQOdsN0Ayfdk16AKkzCA9+I0GqkI0HX3B",
	"dhvelXZ41hOfVjhW7TjQ//3P/wZ6aqjDXCjq5OxSmRgO896DsajffwP0h3vz9HR9FFvpDBVT9OUzTFAE",
	"fp+fMXvTcXTVZCjgajdZ0Mw1I16STALX1/+m+gkk2xLBVUCMR3hPG82I7uJZ+qOGs4FcBXDPE7H60vtx",
	"1606VU2DAfymDz2guPYOWzyJw5stqxZpPTt5/dX2sF2Gh3erO5pttdkHwDxZhwnJ+NCGQs/cbrdTmsK1",
	"KyIxBOQgysy2PZUlp+jbo9kCKwuSLZcCTHOZ+rcingwRO+yE8L0OR6HmV+M9uQyQooayB4ocX4dhML6P",
	"L+cJaaUWNRXXpFSJntaLo7/w6G21TeqEz4CP2RMTL0HTmbDfETNy/+xQ0vMBtC3ZaDupdYWuBXZVwb8z",
	"QnfJrDj1Wxne9+yK4bb907Mt2hqyIqzQvR7/ySXgK5iOVmqC1mOAv3v4eW+m5OHn+j8jBUThUiEPVg4J",
	"4+mUHNh9i1o8Ou3Uw7L3dfV8UCLuQ0bpw7kWRuqSmg1ye++BfZT7eBw6vdjnnnLo3RQ5+BZW10hqiMBj",
	"5dG+bKTXICt6smWYYe9KzSt8wfxCXNjSeq+/RzjQZdj1olhyEGvT9tteVSTkITArPXjlrwkmH9l9d93v",
	"WIrujb/zuq21vSeGnVN1W+l7V37goTLpfex1vBx7E7ulp7ae2Cno7tqGd6t593LEh59L3SezZZ+2NU3O",
	"LqF74F9Ky5hWntvoFwOf88jv5G5WMxG29LcZOndwAGtSzLKqcf6EXIc82E2/P8mh7rdZdaCnqe9CeDJq",
	"snVa/N/7CO0g9KGOU71EbRz4wwmxTirK7rDSEEffVN91f3ax0bvAdbWKnTGr/w41KWh3u6odrs3du67c",
	"1pY5pnillvN7Jgu/y7S3ttIm26zpqr/8HlYGR0Zj17ar2Xuh3qyqFBndLyP0oouCZCOd+DzE/D5lIR+9",
	"BE5x1mrSYIPtdf+Jej0XX785v/n/AAAA//+fnaVpGJIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
