// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	XataScopes = "xata.Scopes"
)

// Defines values for MarketplaceRegisterRequestMarketplace.
const (
	Aws MarketplaceRegisterRequestMarketplace = "aws"
)

// Defines values for OrganizationInvitationStatus.
const (
	OrganizationInvitationStatusExpired OrganizationInvitationStatus = "expired"
	OrganizationInvitationStatusPending OrganizationInvitationStatus = "pending"
)

// Defines values for OrganizationStatusBillingStatus.
const (
	DeletionRequested OrganizationStatusBillingStatus = "deletion_requested"
	InvoiceOverdue    OrganizationStatusBillingStatus = "invoice_overdue"
	NoPaymentMethod   OrganizationStatusBillingStatus = "no_payment_method"
	Ok                OrganizationStatusBillingStatus = "ok"
	Unknown           OrganizationStatusBillingStatus = "unknown"
)

// Defines values for OrganizationStatusStatus.
const (
	Disabled OrganizationStatusStatus = "disabled"
	Enabled  OrganizationStatusStatus = "enabled"
)

// Defines values for OrganizationStatusUsageTier.
const (
	T1 OrganizationStatusUsageTier = "t1"
	T2 OrganizationStatusUsageTier = "t2"
)

// Defines values for ListOrganizationInvitationsParamsStatus.
const (
	ListOrganizationInvitationsParamsStatusExpired ListOrganizationInvitationsParamsStatus = "expired"
	ListOrganizationInvitationsParamsStatusPending ListOrganizationInvitationsParamsStatus = "pending"
)

// APIKeyPreview defines model for APIKeyPreview.
type APIKeyPreview struct {
	// Branches Branches this API key has access to
	Branches  []string  `json:"branches"`
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy ID of the user that created this API key
	CreatedBy *string `json:"created_by"`

	// CreatedByKey ID of the API key that created this API key
	CreatedByKey *string `json:"created_by_key"`

	// Expiry Date when the API key expires (null if no expiry)
	Expiry *time.Time `json:"expiry"`
	Id     string     `json:"id"`

	// LastUsed Timestamp of the last time the key was used (null if never)
	LastUsed *time.Time `json:"last_used"`
	Name     string     `json:"name"`
	Preview  string     `json:"preview"`

	// Projects Projects this API key has access to
	Projects []string `json:"projects"`
	Scopes   []string `json:"scopes"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// Branches Limit access to these branches
	Branches *[]string `json:"branches,omitempty"`

	// Expiry Expiration date for the API key, null for no expiry
	Expiry *time.Time `json:"expiry"`
	Name   string     `json:"name"`

	// Projects Limit access to these projects
	Projects *[]string `json:"projects,omitempty"`

	// Scopes Optional scopes assigned to the API key
	Scopes *[]string `json:"scopes,omitempty"`
}

// CreateOrganizationInvitationRequest defines model for CreateOrganizationInvitationRequest.
type CreateOrganizationInvitationRequest struct {
	// Email Email address of the user to invite
	Email openapi_types.Email `json:"email"`
}

// CreateOrganizationRequest Request payload for creating a new organization
type CreateOrganizationRequest struct {
	// Name Name for the new organization
	Name string `json:"name"`
}

// FullAPIKey defines model for FullAPIKey.
type FullAPIKey struct {
	// Branches Branches this API key has access to
	Branches  []string  `json:"branches"`
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy ID of the user that created this API key
	CreatedBy *string `json:"created_by"`

	// CreatedByKey ID of the API key that created this API key
	CreatedByKey *string `json:"created_by_key"`

	// Expiry Date when the API key expires (null if no expiry)
	Expiry *time.Time `json:"expiry"`
	Id     string     `json:"id"`

	// LastUsed Timestamp of the last time the key was used (null if never)
	LastUsed *time.Time `json:"last_used"`
	Name     string     `json:"name"`
	Preview  string     `json:"preview"`

	// Projects Projects this API key has access to
	Projects []string `json:"projects"`
	Scopes   []string `json:"scopes"`

	// Token The actual API key token
	Token string `json:"token"`
}

// MarketplaceRegisterRequest Request to register with a cloud marketplace
type MarketplaceRegisterRequest struct {
	// Aws AWS-specific marketplace details
	Aws struct {
		// AccountId AWS account ID
		AccountId string `json:"account_id"`

		// CustomerId AWS Marketplace customer ID
		CustomerId string `json:"customer_id"`

		// ProductId AWS Marketplace product ID
		ProductId string `json:"product_id"`
	} `json:"aws"`

	// CompanyName Company name for the marketplace registration
	CompanyName string `json:"company_name"`

	// Marketplace The cloud marketplace provider
	Marketplace MarketplaceRegisterRequestMarketplace `json:"marketplace"`
}

// MarketplaceRegisterRequestMarketplace The cloud marketplace provider
type MarketplaceRegisterRequestMarketplace string

// Organization Organization details including ID and name
type Organization struct {
	Id OrganizationID `json:"id" validate:"identifier"`

	// Marketplace Marketplace provider for this organization (e.g. "aws"), if billed through a marketplace
	Marketplace *string `json:"marketplace"`

	// Name Human-readable name of the organization
	Name   string             `json:"name"`
	Status OrganizationStatus `json:"status"`
}

// OrganizationID defines model for OrganizationID.
type OrganizationID = string

// OrganizationInvitation defines model for OrganizationInvitation.
type OrganizationInvitation struct {
	// CreatedAt Timestamp when the invitation was created
	CreatedAt time.Time `json:"created_at"`

	// Email Email address of the invited user
	Email openapi_types.Email `json:"email"`

	// ExpiresAt Timestamp when the invitation expires
	ExpiresAt time.Time `json:"expires_at"`

	// FirstName First name of the invited user
	FirstName *string `json:"first_name"`

	// Id Unique identifier for the invitation
	Id string `json:"id"`

	// InviteLink URL link to accept the invitation
	InviteLink *string `json:"invite_link,omitempty"`

	// LastName Last name of the invited user
	LastName       *string        `json:"last_name"`
	OrganizationId OrganizationID `json:"organization_id" validate:"identifier"`

	// Status Current status of the invitation
	Status OrganizationInvitationStatus `json:"status"`
}

// OrganizationInvitationStatus Current status of the invitation
type OrganizationInvitationStatus string

// OrganizationStatus defines model for OrganizationStatus.
type OrganizationStatus struct {
	// AdminReason Reason for the current admin status
	AdminReason *string `json:"admin_reason,omitempty"`

	// BillingReason Reason for the current billing status
	BillingReason *string `json:"billing_reason,omitempty"`

	// BillingStatus Indicates the status of the organization from a billing perspective
	BillingStatus OrganizationStatusBillingStatus `json:"billing_status"`

	// CreatedAt Timestamp when the organization was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DisabledByAdmin Indicates if the organization has been disabled by an admin
	DisabledByAdmin bool `json:"disabled_by_admin"`

	// LastUpdated Timestamp of the last update to the organization's status
	LastUpdated time.Time `json:"last_updated"`

	// Status Indicates whether the organization is active, it's computed as `!disabled_by_admin AND billing_status == 'ok'`
	Status OrganizationStatusStatus `json:"status"`

	// UsageTier Usage tier of the organization. t1 is the default for new organizations, t2 is assigned when a valid payment method is on file.
	UsageTier OrganizationStatusUsageTier `json:"usage_tier"`
}

// OrganizationStatusBillingStatus Indicates the status of the organization from a billing perspective
type OrganizationStatusBillingStatus string

// OrganizationStatusStatus Indicates whether the organization is active, it's computed as `!disabled_by_admin AND billing_status == 'ok'`
type OrganizationStatusStatus string

// OrganizationStatusUsageTier Usage tier of the organization. t1 is the default for new organizations, t2 is assigned when a valid payment method is on file.
type OrganizationStatusUsageTier string

// User User information including email, full name, and profile image
type User struct {
	// Email Email address associated with the user account
	Email openapi_types.Email `json:"email"`

	// Name Name of the user
	Name string `json:"name"`
}

// UserID Unique identifier for a user account
type UserID = string

// UserWithID defines model for UserWithID.
type UserWithID struct {
	// Email Email address associated with the user account
	Email openapi_types.Email `json:"email"`

	// Id Unique identifier for a user account
	Id UserID `json:"id" validate:"identifier"`

	// Name Name of the user
	Name string `json:"name"`
}

// InvitationIDParam defines model for InvitationIDParam.
type InvitationIDParam = string

// OrganizationIDParam defines model for OrganizationIDParam.
type OrganizationIDParam = OrganizationID

// UserIDParam Unique identifier for a user account
type UserIDParam = UserID

// AuthError defines model for AuthError.
type AuthError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the issue
	Message string `json:"message"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the issue
	Message string `json:"message"`
}

// SimpleError defines model for SimpleError.
type SimpleError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the issue
	Message string `json:"message"`
}

// DeleteUserAPIKeysJSONBody defines parameters for DeleteUserAPIKeys.
type DeleteUserAPIKeysJSONBody struct {
	// Ids Array of API key IDs to delete (maximum 50 keys per request)
	Ids []string `json:"ids"`
}

// UpdateOrganizationJSONBody defines parameters for UpdateOrganization.
type UpdateOrganizationJSONBody struct {
	Id *OrganizationID `json:"id,omitempty" validate:"identifier"`

	// Name New name for the organization
	Name *string `json:"name,omitempty"`
}

// DeleteOrganizationAPIKeysJSONBody defines parameters for DeleteOrganizationAPIKeys.
type DeleteOrganizationAPIKeysJSONBody struct {
	// Ids Array of API key IDs to delete
	Ids []string `json:"ids"`
}

// ListOrganizationInvitationsParams defines parameters for ListOrganizationInvitations.
type ListOrganizationInvitationsParams struct {
	// Status Filter invitations by status
	Status *ListOrganizationInvitationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Email Filter invitations by email address
	Email *string `form:"email,omitempty" json:"email,omitempty"`

	// FirstName Filter invitations by first name
	FirstName *string `form:"first_name,omitempty" json:"first_name,omitempty"`

	// LastName Filter invitations by last name
	LastName *string `form:"last_name,omitempty" json:"last_name,omitempty"`

	// Search Search invitations by email or name
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// First Index of the first result to return (0-based offset for pagination)
	First *int `form:"first,omitempty" json:"first,omitempty"`

	// Max Maximum number of results to return
	Max *int `form:"max,omitempty" json:"max,omitempty"`
}

// ListOrganizationInvitationsParamsStatus defines parameters for ListOrganizationInvitations.
type ListOrganizationInvitationsParamsStatus string

// DeleteUserAPIKeysJSONRequestBody defines body for DeleteUserAPIKeys for application/json ContentType.
type DeleteUserAPIKeysJSONRequestBody DeleteUserAPIKeysJSONBody

// CreateUserAPIKeyJSONRequestBody defines body for CreateUserAPIKey for application/json ContentType.
type CreateUserAPIKeyJSONRequestBody = CreateAPIKeyRequest

// RegisterMarketplaceJSONRequestBody defines body for RegisterMarketplace for application/json ContentType.
type RegisterMarketplaceJSONRequestBody = MarketplaceRegisterRequest

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = CreateOrganizationRequest

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody UpdateOrganizationJSONBody

// DeleteOrganizationAPIKeysJSONRequestBody defines body for DeleteOrganizationAPIKeys for application/json ContentType.
type DeleteOrganizationAPIKeysJSONRequestBody DeleteOrganizationAPIKeysJSONBody

// CreateOrganizationAPIKeyJSONRequestBody defines body for CreateOrganizationAPIKey for application/json ContentType.
type CreateOrganizationAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateOrganizationInvitationJSONRequestBody defines body for CreateOrganizationInvitation for application/json ContentType.
type CreateOrganizationInvitationJSONRequestBody = CreateOrganizationInvitationRequest
