// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	context "context"
	key "xata/internal/api/key"

	mock "github.com/stretchr/testify/mock"

	store "xata/services/auth/store"
)

// AuthStore is an autogenerated mock type for the AuthStore type
type AuthStore struct {
	mock.Mock
}

type AuthStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthStore) EXPECT() *AuthStore_Expecter {
	return &AuthStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *AuthStore) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type AuthStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthStore_Expecter) Close(ctx interface{}) *AuthStore_Close_Call {
	return &AuthStore_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *AuthStore_Close_Call) Run(run func(ctx context.Context)) *AuthStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthStore_Close_Call) Return(_a0 error) *AuthStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

// CreateAPIKey provides a mock function with given fields: ctx, targetType, targetID, _a3
func (_m *AuthStore) CreateAPIKey(ctx context.Context, targetType store.KeyTargetType, targetID string, _a3 *store.APIKeyCreate) (key.Key, *store.APIKey, error) {
	ret := _m.Called(ctx, targetType, targetID, _a3)

	var r0 key.Key
	if rf, ok := ret.Get(0).(func(context.Context, store.KeyTargetType, string, *store.APIKeyCreate) key.Key); ok {
		r0 = rf(ctx, targetType, targetID, _a3)
	} else {
		r0 = ret.Get(0).(key.Key)
	}

	var r1 *store.APIKey
	if rf, ok := ret.Get(1).(func(context.Context, store.KeyTargetType, string, *store.APIKeyCreate) *store.APIKey); ok {
		r1 = rf(ctx, targetType, targetID, _a3)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*store.APIKey)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, store.KeyTargetType, string, *store.APIKeyCreate) error); ok {
		r2 = rf(ctx, targetType, targetID, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AuthStore_CreateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIKey'
type AuthStore_CreateAPIKey_Call struct {
	*mock.Call
}

// CreateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - targetType store.KeyTargetType
//   - targetID string
//   - _a3 *store.APIKeyCreate
func (_e *AuthStore_Expecter) CreateAPIKey(ctx interface{}, targetType interface{}, targetID interface{}, _a3 interface{}) *AuthStore_CreateAPIKey_Call {
	return &AuthStore_CreateAPIKey_Call{Call: _e.mock.On("CreateAPIKey", ctx, targetType, targetID, _a3)}
}

func (_c *AuthStore_CreateAPIKey_Call) Run(run func(ctx context.Context, targetType store.KeyTargetType, targetID string, _a3 *store.APIKeyCreate)) *AuthStore_CreateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.KeyTargetType), args[2].(string), args[3].(*store.APIKeyCreate))
	})
	return _c
}

func (_c *AuthStore_CreateAPIKey_Call) Return(_a0 key.Key, _a1 *store.APIKey, _a2 error) *AuthStore_CreateAPIKey_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// DeleteAPIKeys provides a mock function with given fields: ctx, targetType, targetID, keyIDs
func (_m *AuthStore) DeleteAPIKeys(ctx context.Context, targetType store.KeyTargetType, targetID string, keyIDs []string) error {
	ret := _m.Called(ctx, targetType, targetID, keyIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, store.KeyTargetType, string, []string) error); ok {
		r0 = rf(ctx, targetType, targetID, keyIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthStore_DeleteAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAPIKeys'
type AuthStore_DeleteAPIKeys_Call struct {
	*mock.Call
}

// DeleteAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - targetType store.KeyTargetType
//   - targetID string
//   - keyIDs []string
func (_e *AuthStore_Expecter) DeleteAPIKeys(ctx interface{}, targetType interface{}, targetID interface{}, keyIDs interface{}) *AuthStore_DeleteAPIKeys_Call {
	return &AuthStore_DeleteAPIKeys_Call{Call: _e.mock.On("DeleteAPIKeys", ctx, targetType, targetID, keyIDs)}
}

func (_c *AuthStore_DeleteAPIKeys_Call) Run(run func(ctx context.Context, targetType store.KeyTargetType, targetID string, keyIDs []string)) *AuthStore_DeleteAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.KeyTargetType), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *AuthStore_DeleteAPIKeys_Call) Return(_a0 error) *AuthStore_DeleteAPIKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

// DeleteOrgLimit provides a mock function with given fields: ctx, orgID, _a2
func (_m *AuthStore) DeleteOrgLimit(ctx context.Context, orgID string, _a2 store.OrgLimitKey) error {
	ret := _m.Called(ctx, orgID, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, store.OrgLimitKey) error); ok {
		r0 = rf(ctx, orgID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthStore_DeleteOrgLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgLimit'
type AuthStore_DeleteOrgLimit_Call struct {
	*mock.Call
}

// DeleteOrgLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - _a2 store.OrgLimitKey
func (_e *AuthStore_Expecter) DeleteOrgLimit(ctx interface{}, orgID interface{}, _a2 interface{}) *AuthStore_DeleteOrgLimit_Call {
	return &AuthStore_DeleteOrgLimit_Call{Call: _e.mock.On("DeleteOrgLimit", ctx, orgID, _a2)}
}

func (_c *AuthStore_DeleteOrgLimit_Call) Run(run func(ctx context.Context, orgID string, _a2 store.OrgLimitKey)) *AuthStore_DeleteOrgLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(store.OrgLimitKey))
	})
	return _c
}

func (_c *AuthStore_DeleteOrgLimit_Call) Return(_a0 error) *AuthStore_DeleteOrgLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetAPIKey provides a mock function with given fields: ctx, id
func (_m *AuthStore) GetAPIKey(ctx context.Context, id string) (*store.APIKey, error) {
	ret := _m.Called(ctx, id)

	var r0 *store.APIKey
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.APIKey); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.APIKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthStore_GetAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIKey'
type AuthStore_GetAPIKey_Call struct {
	*mock.Call
}

// GetAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AuthStore_Expecter) GetAPIKey(ctx interface{}, id interface{}) *AuthStore_GetAPIKey_Call {
	return &AuthStore_GetAPIKey_Call{Call: _e.mock.On("GetAPIKey", ctx, id)}
}

func (_c *AuthStore_GetAPIKey_Call) Run(run func(ctx context.Context, id string)) *AuthStore_GetAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthStore_GetAPIKey_Call) Return(_a0 *store.APIKey, _a1 error) *AuthStore_GetAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetOrgLimits provides a mock function with given fields: ctx, orgID
func (_m *AuthStore) GetOrgLimits(ctx context.Context, orgID string) (map[store.OrgLimitKey]interface{}, error) {
	ret := _m.Called(ctx, orgID)

	var r0 map[store.OrgLimitKey]interface{}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[store.OrgLimitKey]interface{}); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[store.OrgLimitKey]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthStore_GetOrgLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgLimits'
type AuthStore_GetOrgLimits_Call struct {
	*mock.Call
}

// GetOrgLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *AuthStore_Expecter) GetOrgLimits(ctx interface{}, orgID interface{}) *AuthStore_GetOrgLimits_Call {
	return &AuthStore_GetOrgLimits_Call{Call: _e.mock.On("GetOrgLimits", ctx, orgID)}
}

func (_c *AuthStore_GetOrgLimits_Call) Run(run func(ctx context.Context, orgID string)) *AuthStore_GetOrgLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthStore_GetOrgLimits_Call) Return(_a0 map[store.OrgLimitKey]interface{}, _a1 error) *AuthStore_GetOrgLimits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListAPIKeys provides a mock function with given fields: ctx, targetType, targetID
func (_m *AuthStore) ListAPIKeys(ctx context.Context, targetType store.KeyTargetType, targetID string) ([]store.APIKey, error) {
	ret := _m.Called(ctx, targetType, targetID)

	var r0 []store.APIKey
	if rf, ok := ret.Get(0).(func(context.Context, store.KeyTargetType, string) []store.APIKey); ok {
		r0 = rf(ctx, targetType, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.APIKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, store.KeyTargetType, string) error); ok {
		r1 = rf(ctx, targetType, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthStore_ListAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAPIKeys'
type AuthStore_ListAPIKeys_Call struct {
	*mock.Call
}

// ListAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - targetType store.KeyTargetType
//   - targetID string
func (_e *AuthStore_Expecter) ListAPIKeys(ctx interface{}, targetType interface{}, targetID interface{}) *AuthStore_ListAPIKeys_Call {
	return &AuthStore_ListAPIKeys_Call{Call: _e.mock.On("ListAPIKeys", ctx, targetType, targetID)}
}

func (_c *AuthStore_ListAPIKeys_Call) Run(run func(ctx context.Context, targetType store.KeyTargetType, targetID string)) *AuthStore_ListAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.KeyTargetType), args[2].(string))
	})
	return _c
}

func (_c *AuthStore_ListAPIKeys_Call) Return(_a0 []store.APIKey, _a1 error) *AuthStore_ListAPIKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetOrgLimit provides a mock function with given fields: ctx, orgID, _a2, value
func (_m *AuthStore) SetOrgLimit(ctx context.Context, orgID string, _a2 store.OrgLimitKey, value interface{}) error {
	ret := _m.Called(ctx, orgID, _a2, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, store.OrgLimitKey, interface{}) error); ok {
		r0 = rf(ctx, orgID, _a2, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthStore_SetOrgLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrgLimit'
type AuthStore_SetOrgLimit_Call struct {
	*mock.Call
}

// SetOrgLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - _a2 store.OrgLimitKey
//   - value interface{}
func (_e *AuthStore_Expecter) SetOrgLimit(ctx interface{}, orgID interface{}, _a2 interface{}, value interface{}) *AuthStore_SetOrgLimit_Call {
	return &AuthStore_SetOrgLimit_Call{Call: _e.mock.On("SetOrgLimit", ctx, orgID, _a2, value)}
}

func (_c *AuthStore_SetOrgLimit_Call) Run(run func(ctx context.Context, orgID string, _a2 store.OrgLimitKey, value interface{})) *AuthStore_SetOrgLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(store.OrgLimitKey), args[3].(interface{}))
	})
	return _c
}

func (_c *AuthStore_SetOrgLimit_Call) Return(_a0 error) *AuthStore_SetOrgLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

// Setup provides a mock function with given fields: ctx
func (_m *AuthStore) Setup(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthStore_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type AuthStore_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthStore_Expecter) Setup(ctx interface{}) *AuthStore_Setup_Call {
	return &AuthStore_Setup_Call{Call: _e.mock.On("Setup", ctx)}
}

func (_c *AuthStore_Setup_Call) Run(run func(ctx context.Context)) *AuthStore_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthStore_Setup_Call) Return(_a0 error) *AuthStore_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

// ValidateAPIKey provides a mock function with given fields: ctx, apiKey
func (_m *AuthStore) ValidateAPIKey(ctx context.Context, apiKey key.Key) (*store.APIKey, error) {
	ret := _m.Called(ctx, apiKey)

	var r0 *store.APIKey
	if rf, ok := ret.Get(0).(func(context.Context, key.Key) *store.APIKey); ok {
		r0 = rf(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.APIKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, key.Key) error); ok {
		r1 = rf(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthStore_ValidateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAPIKey'
type AuthStore_ValidateAPIKey_Call struct {
	*mock.Call
}

// ValidateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey key.Key
func (_e *AuthStore_Expecter) ValidateAPIKey(ctx interface{}, apiKey interface{}) *AuthStore_ValidateAPIKey_Call {
	return &AuthStore_ValidateAPIKey_Call{Call: _e.mock.On("ValidateAPIKey", ctx, apiKey)}
}

func (_c *AuthStore_ValidateAPIKey_Call) Run(run func(ctx context.Context, apiKey key.Key)) *AuthStore_ValidateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(key.Key))
	})
	return _c
}

func (_c *AuthStore_ValidateAPIKey_Call) Return(_a0 *store.APIKey, _a1 error) *AuthStore_ValidateAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewAuthStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthStore creates a new instance of AuthStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthStore(t mockConstructorTestingTNewAuthStore) *AuthStore {
	mock := &AuthStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
