// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AffinitySpecApplyConfiguration represents a declarative configuration of the AffinitySpec type for use
// with apply.
//
// AffinitySpec defines pod scheduling constraints
type AffinitySpecApplyConfiguration struct {
	// NodeSelector specifies node labels that pods must match to be scheduled
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
}

// AffinitySpecApplyConfiguration constructs a declarative configuration of the AffinitySpec type for use with
// apply.
func AffinitySpec() *AffinitySpecApplyConfiguration {
	return &AffinitySpecApplyConfiguration{}
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *AffinitySpecApplyConfiguration) WithNodeSelector(entries map[string]string) *AffinitySpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}
