// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "xata/services/branch-operator/api/v1alpha1"
)

// BackupSpecApplyConfiguration represents a declarative configuration of the BackupSpec type for use
// with apply.
//
// BackupSpec defines backup settings for a Branch
type BackupSpecApplyConfiguration struct {
	// Retention specifies how long to retain backups
	// Examples: "60d", "4w", "2m"
	Retention *string `json:"retention,omitempty"`
	// WALArchiving specifies whether WAL archiving is enabled
	WALArchiving *apiv1alpha1.WALArchivingMode `json:"walArchiving,omitempty"`
	// ScheduledBackup configures periodic base backups.
	ScheduledBackup *ScheduledBackupSpecApplyConfiguration `json:"scheduledBackup,omitempty"`
	// ServerName overrides the barman serverName plugin parameter.
	// When empty, serverName defaults to the branch name.
	ServerName *string `json:"serverName,omitempty"`
}

// BackupSpecApplyConfiguration constructs a declarative configuration of the BackupSpec type for use with
// apply.
func BackupSpec() *BackupSpecApplyConfiguration {
	return &BackupSpecApplyConfiguration{}
}

// WithRetention sets the Retention field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retention field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithRetention(value string) *BackupSpecApplyConfiguration {
	b.Retention = &value
	return b
}

// WithWALArchiving sets the WALArchiving field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WALArchiving field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithWALArchiving(value apiv1alpha1.WALArchivingMode) *BackupSpecApplyConfiguration {
	b.WALArchiving = &value
	return b
}

// WithScheduledBackup sets the ScheduledBackup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScheduledBackup field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithScheduledBackup(value *ScheduledBackupSpecApplyConfiguration) *BackupSpecApplyConfiguration {
	b.ScheduledBackup = value
	return b
}

// WithServerName sets the ServerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerName field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithServerName(value string) *BackupSpecApplyConfiguration {
	b.ServerName = &value
	return b
}
