// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BranchStatusApplyConfiguration represents a declarative configuration of the BranchStatus type for use
// with apply.
//
// BranchStatus defines the observed state of a Branch
type BranchStatusApplyConfiguration struct {
	// ObservedGeneration reflects the generation of the most recently observed Branch spec
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the Branch's state
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// LastError contains the last error message encountered during
	// reconciliation, if any.
	LastError *string `json:"lastError,omitempty"`
	// PrimaryXVolName is the name of the XVol backing the primary instance's
	// PersistentVolume. Retained after cluster removal.
	PrimaryXVolName *string `json:"primaryXVolName,omitempty"`
}

// BranchStatusApplyConfiguration constructs a declarative configuration of the BranchStatus type for use with
// apply.
func BranchStatus() *BranchStatusApplyConfiguration {
	return &BranchStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BranchStatusApplyConfiguration) WithObservedGeneration(value int64) *BranchStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BranchStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BranchStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLastError sets the LastError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastError field is set to the value of the last call.
func (b *BranchStatusApplyConfiguration) WithLastError(value string) *BranchStatusApplyConfiguration {
	b.LastError = &value
	return b
}

// WithPrimaryXVolName sets the PrimaryXVolName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrimaryXVolName field is set to the value of the last call.
func (b *BranchStatusApplyConfiguration) WithPrimaryXVolName(value string) *BranchStatusApplyConfiguration {
	b.PrimaryXVolName = &value
	return b
}
