// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BranchSpecApplyConfiguration represents a declarative configuration of the BranchSpec type for use
// with apply.
//
// BranchSpec defines the desired state of a Branch
type BranchSpecApplyConfiguration struct {
	// Restore specifies how to restore the branch from a backup source.
	Restore *RestoreSpecApplyConfiguration `json:"restore,omitempty"`
	// ClusterSpec defines the CNPG cluster configuration for the branch
	ClusterSpec *ClusterSpecApplyConfiguration `json:"cluster,omitempty"`
	// BackupSpec configures backups for the branch. When set, an
	// ObjectStore resource is created to manage backup storage and retention.
	// When nil, no ObjectStore is created.
	BackupSpec *BackupSpecApplyConfiguration `json:"backup,omitempty"`
	// Pooler configures a PgBouncer connection pooler for the branch.
	// When nil, no pooler is created.
	Pooler *PoolerSpecApplyConfiguration `json:"pooler,omitempty"`
	// InheritedMetadata defines metadata to be inherited by all resources
	// created by the operator
	InheritedMetadata *InheritedMetadataApplyConfiguration `json:"inheritedMetadata,omitempty"`
}

// BranchSpecApplyConfiguration constructs a declarative configuration of the BranchSpec type for use with
// apply.
func BranchSpec() *BranchSpecApplyConfiguration {
	return &BranchSpecApplyConfiguration{}
}

// WithRestore sets the Restore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Restore field is set to the value of the last call.
func (b *BranchSpecApplyConfiguration) WithRestore(value *RestoreSpecApplyConfiguration) *BranchSpecApplyConfiguration {
	b.Restore = value
	return b
}

// WithClusterSpec sets the ClusterSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterSpec field is set to the value of the last call.
func (b *BranchSpecApplyConfiguration) WithClusterSpec(value *ClusterSpecApplyConfiguration) *BranchSpecApplyConfiguration {
	b.ClusterSpec = value
	return b
}

// WithBackupSpec sets the BackupSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupSpec field is set to the value of the last call.
func (b *BranchSpecApplyConfiguration) WithBackupSpec(value *BackupSpecApplyConfiguration) *BranchSpecApplyConfiguration {
	b.BackupSpec = value
	return b
}

// WithPooler sets the Pooler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pooler field is set to the value of the last call.
func (b *BranchSpecApplyConfiguration) WithPooler(value *PoolerSpecApplyConfiguration) *BranchSpecApplyConfiguration {
	b.Pooler = value
	return b
}

// WithInheritedMetadata sets the InheritedMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InheritedMetadata field is set to the value of the last call.
func (b *BranchSpecApplyConfiguration) WithInheritedMetadata(value *InheritedMetadataApplyConfiguration) *BranchSpecApplyConfiguration {
	b.InheritedMetadata = value
	return b
}
