// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "xata/services/branch-operator/api/v1alpha1"

	v1 "k8s.io/api/core/v1"
)

// ClusterSpecApplyConfiguration represents a declarative configuration of the ClusterSpec type for use
// with apply.
//
// ClusterSpec defines the PostgreSQL cluster configuration
type ClusterSpecApplyConfiguration struct {
	// Name is the name of the CNPG Cluster resource.
	// If nil, the branch has no cluster associated with it.
	Name *string `json:"name,omitempty"`
	// Image is the PostgreSQL container image to use
	Image *string `json:"image,omitempty"`
	// Instances is the number of PostgreSQL instances in the cluster
	Instances *int32 `json:"instances,omitempty"`
	// Resources defines the compute resources for the PostgreSQL instances
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// Storage defines the persistent volume configuration for each instance
	Storage *StorageSpecApplyConfiguration `json:"storage,omitempty"`
	// Postgres defines PostgreSQL-specific configuration
	Postgres *PostgresConfigurationApplyConfiguration `json:"postgres,omitempty"`
	// ScaleToZero defines scale-to-zero configuration for the cluster
	ScaleToZero *ScaleToZeroConfigurationApplyConfiguration `json:"scaleToZero,omitempty"`
	// Hibernation specifies whether the cluster should be hibernated
	Hibernation *apiv1alpha1.HibernationMode `json:"hibernation,omitempty"`
	// Affinity defines scheduling constraints for the cluster pods
	Affinity *AffinitySpecApplyConfiguration `json:"affinity,omitempty"`
	// SmartShutdownTimeout is the time in seconds reserved for the smart
	// shutdown of Postgres to complete. If not set, the CNPG default (180s)
	// is used.
	SmartShutdownTimeout *int32 `json:"smartShutdownTimeout,omitempty"`
}

// ClusterSpecApplyConfiguration constructs a declarative configuration of the ClusterSpec type for use with
// apply.
func ClusterSpec() *ClusterSpecApplyConfiguration {
	return &ClusterSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithName(value string) *ClusterSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithImage(value string) *ClusterSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithInstances sets the Instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instances field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithInstances(value int32) *ClusterSpecApplyConfiguration {
	b.Instances = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *ClusterSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithStorage(value *StorageSpecApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Storage = value
	return b
}

// WithPostgres sets the Postgres field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Postgres field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPostgres(value *PostgresConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Postgres = value
	return b
}

// WithScaleToZero sets the ScaleToZero field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScaleToZero field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithScaleToZero(value *ScaleToZeroConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.ScaleToZero = value
	return b
}

// WithHibernation sets the Hibernation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hibernation field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithHibernation(value apiv1alpha1.HibernationMode) *ClusterSpecApplyConfiguration {
	b.Hibernation = &value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithAffinity(value *AffinitySpecApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Affinity = value
	return b
}

// WithSmartShutdownTimeout sets the SmartShutdownTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SmartShutdownTimeout field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithSmartShutdownTimeout(value int32) *ClusterSpecApplyConfiguration {
	b.SmartShutdownTimeout = &value
	return b
}
