// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// InheritedMetadataApplyConfiguration represents a declarative configuration of the InheritedMetadata type for use
// with apply.
//
// InheritedMetadata defines metadata to be inherited by all resources created
// by the operator
type InheritedMetadataApplyConfiguration struct {
	// Labels are additional labels to apply to resources created by the operator
	Labels map[string]string `json:"labels,omitempty"`
}

// InheritedMetadataApplyConfiguration constructs a declarative configuration of the InheritedMetadata type for use with
// apply.
func InheritedMetadata() *InheritedMetadataApplyConfiguration {
	return &InheritedMetadataApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *InheritedMetadataApplyConfiguration) WithLabels(entries map[string]string) *InheritedMetadataApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}
