// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PgBackRestSpecApplyConfiguration represents a declarative configuration of the PgBackRestSpec type for use
// with apply.
//
// PgBackRestSpec defines pgbackrest-specific backup configuration.
//
// The following pgbackrest options are set internally with fixed defaults
// and not exposed to users:
// - retention fullType: always "time" (days)
// - retention archive: follows full retention (pgbackrest default)
// - bundle: always on (fewer S3 API calls)
// - blockIncremental: always on (requires bundle; reduces storage for large DBs)
// - startFast: always on (immediate checkpoint, no waiting)
// - delta: always on (faster restores)
// - backupStandby: controlled via backup.target on the Cluster
// - priority: 19 (lowest CPU priority, avoids impacting postgres)
// - processMax: computed from instance CPU resources
type PgBackRestSpecApplyConfiguration struct {
	// Bucket is the S3 bucket for backups and WAL archives.
	Bucket *string `json:"bucket,omitempty"`
	// Region is the S3 region.
	Region *string `json:"region,omitempty"`
	// Endpoint overrides S3 endpoint discovery. Required for non-AWS
	// S3-compatible storage (e.g. Cloudflare R2, or MinIO for local
	// dev). When set, static credentials from the operator-configured
	// credentials Secret are used instead of an IAM role.
	Endpoint *string `json:"endpoint,omitempty"`
	// InheritFromIAMRole uses the pod's IAM role for S3 authentication.
	InheritFromIAMRole *bool `json:"inheritFromIAMRole,omitempty"`
	// RetentionFullDays is the number of days to retain full backups.
	RetentionFullDays *int `json:"retentionFullDays,omitempty"`
	// CompressType sets the compression algorithm.
	CompressType *string `json:"compressType,omitempty"`
	// CompressLevel sets the compression level (0-9).
	CompressLevel *int `json:"compressLevel,omitempty"`
	// ArchiveAsync enables asynchronous WAL archiving.
	ArchiveAsync *bool `json:"archiveAsync,omitempty"`
	// ArchivePushQueueMax is the max WAL push queue size when async is enabled.
	// Uses pgbackrest size format (e.g. "2GiB", "256MiB").
	ArchivePushQueueMax *string `json:"archivePushQueueMax,omitempty"`
	// ArchiveGetQueueMax is the max WAL restore queue size when async is enabled.
	// Uses pgbackrest size format (e.g. "2GiB", "256MiB").
	ArchiveGetQueueMax *string `json:"archiveGetQueueMax,omitempty"`
	// RepoPath overrides the storage path prefix. Defaults to /<clusterName>.
	RepoPath *string `json:"repoPath,omitempty"`
	// StanzaName overrides the pgbackrest stanza this branch archives to.
	// When empty it defaults to the branch name.
	StanzaName *string `json:"stanzaName,omitempty"`
}

// PgBackRestSpecApplyConfiguration constructs a declarative configuration of the PgBackRestSpec type for use with
// apply.
func PgBackRestSpec() *PgBackRestSpecApplyConfiguration {
	return &PgBackRestSpecApplyConfiguration{}
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithBucket(value string) *PgBackRestSpecApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithRegion(value string) *PgBackRestSpecApplyConfiguration {
	b.Region = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithEndpoint(value string) *PgBackRestSpecApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithInheritFromIAMRole sets the InheritFromIAMRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InheritFromIAMRole field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithInheritFromIAMRole(value bool) *PgBackRestSpecApplyConfiguration {
	b.InheritFromIAMRole = &value
	return b
}

// WithRetentionFullDays sets the RetentionFullDays field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetentionFullDays field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithRetentionFullDays(value int) *PgBackRestSpecApplyConfiguration {
	b.RetentionFullDays = &value
	return b
}

// WithCompressType sets the CompressType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompressType field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithCompressType(value string) *PgBackRestSpecApplyConfiguration {
	b.CompressType = &value
	return b
}

// WithCompressLevel sets the CompressLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompressLevel field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithCompressLevel(value int) *PgBackRestSpecApplyConfiguration {
	b.CompressLevel = &value
	return b
}

// WithArchiveAsync sets the ArchiveAsync field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArchiveAsync field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithArchiveAsync(value bool) *PgBackRestSpecApplyConfiguration {
	b.ArchiveAsync = &value
	return b
}

// WithArchivePushQueueMax sets the ArchivePushQueueMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArchivePushQueueMax field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithArchivePushQueueMax(value string) *PgBackRestSpecApplyConfiguration {
	b.ArchivePushQueueMax = &value
	return b
}

// WithArchiveGetQueueMax sets the ArchiveGetQueueMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArchiveGetQueueMax field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithArchiveGetQueueMax(value string) *PgBackRestSpecApplyConfiguration {
	b.ArchiveGetQueueMax = &value
	return b
}

// WithRepoPath sets the RepoPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepoPath field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithRepoPath(value string) *PgBackRestSpecApplyConfiguration {
	b.RepoPath = &value
	return b
}

// WithStanzaName sets the StanzaName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StanzaName field is set to the value of the last call.
func (b *PgBackRestSpecApplyConfiguration) WithStanzaName(value string) *PgBackRestSpecApplyConfiguration {
	b.StanzaName = &value
	return b
}
