// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PostgresConfigurationApplyConfiguration represents a declarative configuration of the PostgresConfiguration type for use
// with apply.
//
// PostgresConfiguration defines PostgreSQL-specific settings
type PostgresConfigurationApplyConfiguration struct {
	// Parameters are PostgreSQL configuration parameters
	Parameters []PostgresParameterApplyConfiguration `json:"parameters,omitempty"`
	// SharedPreloadLibraries are PostgreSQL shared preload libraries
	SharedPreloadLibraries []string `json:"sharedPreloadLibraries,omitempty"`
}

// PostgresConfigurationApplyConfiguration constructs a declarative configuration of the PostgresConfiguration type for use with
// apply.
func PostgresConfiguration() *PostgresConfigurationApplyConfiguration {
	return &PostgresConfigurationApplyConfiguration{}
}

// WithParameters adds the given value to the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parameters field.
func (b *PostgresConfigurationApplyConfiguration) WithParameters(values ...*PostgresParameterApplyConfiguration) *PostgresConfigurationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParameters")
		}
		b.Parameters = append(b.Parameters, *values[i])
	}
	return b
}

// WithSharedPreloadLibraries adds the given value to the SharedPreloadLibraries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SharedPreloadLibraries field.
func (b *PostgresConfigurationApplyConfiguration) WithSharedPreloadLibraries(values ...string) *PostgresConfigurationApplyConfiguration {
	for i := range values {
		b.SharedPreloadLibraries = append(b.SharedPreloadLibraries, values[i])
	}
	return b
}
