// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PostgresParameterApplyConfiguration represents a declarative configuration of the PostgresParameter type for use
// with apply.
//
// PostgresParameter defines a PostgreSQL configuration parameter
type PostgresParameterApplyConfiguration struct {
	// Name is the parameter name
	Name *string `json:"name,omitempty"`
	// Value is the parameter value
	Value *string `json:"value,omitempty"`
}

// PostgresParameterApplyConfiguration constructs a declarative configuration of the PostgresParameter type for use with
// apply.
func PostgresParameter() *PostgresParameterApplyConfiguration {
	return &PostgresParameterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PostgresParameterApplyConfiguration) WithName(value string) *PostgresParameterApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *PostgresParameterApplyConfiguration) WithValue(value string) *PostgresParameterApplyConfiguration {
	b.Value = &value
	return b
}
