// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "xata/services/branch-operator/api/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RestoreSpecApplyConfiguration represents a declarative configuration of the RestoreSpec type for use
// with apply.
//
// RestoreSpec defines how to restore the branch from a backup source
type RestoreSpecApplyConfiguration struct {
	// Type specifies the type of restore source
	Type *apiv1alpha1.RestoreType `json:"type,omitempty"`
	// Name is the name of the restore source (for volume snapshot, object store, base backup or XVol clone)
	Name *string `json:"name,omitempty"`
	// Timestamp specifies the point-in-time to restore to.
	// Only applicable when Type is ObjectStore.
	Timestamp *v1.Time `json:"timestamp,omitempty"`
	// ServerName overrides the barman serverName parameter in the external
	// cluster plugin configuration. Only applicable when Type is ObjectStore.
	// When empty, defaults to the restore name.
	ServerName *string `json:"serverName,omitempty"`
}

// RestoreSpecApplyConfiguration constructs a declarative configuration of the RestoreSpec type for use with
// apply.
func RestoreSpec() *RestoreSpecApplyConfiguration {
	return &RestoreSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RestoreSpecApplyConfiguration) WithType(value apiv1alpha1.RestoreType) *RestoreSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RestoreSpecApplyConfiguration) WithName(value string) *RestoreSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithTimestamp sets the Timestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timestamp field is set to the value of the last call.
func (b *RestoreSpecApplyConfiguration) WithTimestamp(value v1.Time) *RestoreSpecApplyConfiguration {
	b.Timestamp = &value
	return b
}

// WithServerName sets the ServerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerName field is set to the value of the last call.
func (b *RestoreSpecApplyConfiguration) WithServerName(value string) *RestoreSpecApplyConfiguration {
	b.ServerName = &value
	return b
}
