// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ScaleToZeroConfigurationApplyConfiguration represents a declarative configuration of the ScaleToZeroConfiguration type for use
// with apply.
//
// ScaleToZeroConfiguration defines scale-to-zero settings
type ScaleToZeroConfigurationApplyConfiguration struct {
	// Enabled controls whether scale-to-zero is active.
	// When false the configuration (e.g. InactivityPeriodMinutes) is preserved
	// but scale-to-zero is disabled.
	Enabled *bool `json:"enabled,omitempty"`
	// InactivityPeriodMinutes is the period of inactivity before scaling to zero
	InactivityPeriodMinutes *int32 `json:"inactivityPeriodMinutes,omitempty"`
}

// ScaleToZeroConfigurationApplyConfiguration constructs a declarative configuration of the ScaleToZeroConfiguration type for use with
// apply.
func ScaleToZeroConfiguration() *ScaleToZeroConfigurationApplyConfiguration {
	return &ScaleToZeroConfigurationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ScaleToZeroConfigurationApplyConfiguration) WithEnabled(value bool) *ScaleToZeroConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithInactivityPeriodMinutes sets the InactivityPeriodMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InactivityPeriodMinutes field is set to the value of the last call.
func (b *ScaleToZeroConfigurationApplyConfiguration) WithInactivityPeriodMinutes(value int32) *ScaleToZeroConfigurationApplyConfiguration {
	b.InactivityPeriodMinutes = &value
	return b
}
