// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// WakeupRequestStatusApplyConfiguration represents a declarative configuration of the WakeupRequestStatus type for use
// with apply.
//
// WakeupRequestStatus defines the observed state of a WakeupRequest
type WakeupRequestStatusApplyConfiguration struct {
	// ObservedGeneration reflects the generation of the most recently observed spec
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the WakeupRequest's state
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// LastError contains the last error message encountered during reconciliation
	LastError *string `json:"lastError,omitempty"`
}

// WakeupRequestStatusApplyConfiguration constructs a declarative configuration of the WakeupRequestStatus type for use with
// apply.
func WakeupRequestStatus() *WakeupRequestStatusApplyConfiguration {
	return &WakeupRequestStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *WakeupRequestStatusApplyConfiguration) WithObservedGeneration(value int64) *WakeupRequestStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *WakeupRequestStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *WakeupRequestStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLastError sets the LastError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastError field is set to the value of the last call.
func (b *WakeupRequestStatusApplyConfiguration) WithLastError(value string) *WakeupRequestStatusApplyConfiguration {
	b.LastError = &value
	return b
}
