// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package metricsmock

import (
	context "context"
	metrics "xata/services/projects/metrics"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetLogs provides a mock function with given fields: ctx, organizationID, cellID, start, end, branchID, filters, limit, cursor
func (_m *Client) GetLogs(ctx context.Context, organizationID string, cellID string, start time.Time, end time.Time, branchID string, filters []metrics.LogFilter, limit int, cursor string) (*metrics.BranchLogs, error) {
	ret := _m.Called(ctx, organizationID, cellID, start, end, branchID, filters, limit, cursor)

	var r0 *metrics.BranchLogs
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time, string, []metrics.LogFilter, int, string) *metrics.BranchLogs); ok {
		r0 = rf(ctx, organizationID, cellID, start, end, branchID, filters, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metrics.BranchLogs)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time, string, []metrics.LogFilter, int, string) error); ok {
		r1 = rf(ctx, organizationID, cellID, start, end, branchID, filters, limit, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type Client_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - cellID string
//   - start time.Time
//   - end time.Time
//   - branchID string
//   - filters []metrics.LogFilter
//   - limit int
//   - cursor string
func (_e *Client_Expecter) GetLogs(ctx interface{}, organizationID interface{}, cellID interface{}, start interface{}, end interface{}, branchID interface{}, filters interface{}, limit interface{}, cursor interface{}) *Client_GetLogs_Call {
	return &Client_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, organizationID, cellID, start, end, branchID, filters, limit, cursor)}
}

func (_c *Client_GetLogs_Call) Run(run func(ctx context.Context, organizationID string, cellID string, start time.Time, end time.Time, branchID string, filters []metrics.LogFilter, limit int, cursor string)) *Client_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time), args[5].(string), args[6].([]metrics.LogFilter), args[7].(int), args[8].(string))
	})
	return _c
}

func (_c *Client_GetLogs_Call) Return(_a0 *metrics.BranchLogs, _a1 error) *Client_GetLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetMetric provides a mock function with given fields: ctx, organizationID, cellID, start, end, branchID, metric, instances, aggregations
func (_m *Client) GetMetric(ctx context.Context, organizationID string, cellID string, start time.Time, end time.Time, branchID string, metric string, instances []string, aggregations []string) (*metrics.BranchMetrics, error) {
	ret := _m.Called(ctx, organizationID, cellID, start, end, branchID, metric, instances, aggregations)

	var r0 *metrics.BranchMetrics
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time, string, string, []string, []string) *metrics.BranchMetrics); ok {
		r0 = rf(ctx, organizationID, cellID, start, end, branchID, metric, instances, aggregations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metrics.BranchMetrics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time, string, string, []string, []string) error); ok {
		r1 = rf(ctx, organizationID, cellID, start, end, branchID, metric, instances, aggregations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type Client_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - cellID string
//   - start time.Time
//   - end time.Time
//   - branchID string
//   - metric string
//   - instances []string
//   - aggregations []string
func (_e *Client_Expecter) GetMetric(ctx interface{}, organizationID interface{}, cellID interface{}, start interface{}, end interface{}, branchID interface{}, metric interface{}, instances interface{}, aggregations interface{}) *Client_GetMetric_Call {
	return &Client_GetMetric_Call{Call: _e.mock.On("GetMetric", ctx, organizationID, cellID, start, end, branchID, metric, instances, aggregations)}
}

func (_c *Client_GetMetric_Call) Run(run func(ctx context.Context, organizationID string, cellID string, start time.Time, end time.Time, branchID string, metric string, instances []string, aggregations []string)) *Client_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time), args[5].(string), args[6].(string), args[7].([]string), args[8].([]string))
	})
	return _c
}

func (_c *Client_GetMetric_Call) Return(_a0 *metrics.BranchMetrics, _a1 error) *Client_GetMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
