image:
  repository: ghcr.io/xataio/xata/clusters
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  grpcPort: 5002

config:
  clusters:
    clustersNamespace: xata-clusters
    storageClass: ""
    nodeSelector: ""
    volumeSnapshotClass: ""
    xatastor: { enabled: false }
    openebs:
      enabled: true
      namespace: openebs
  observability:
    victoriaMetricsURL: "http://victoria-metrics.xata-observability.svc.cluster.local:8428"
    victoriaLogsURL: "http://victoria-logs.xata-observability.svc.cluster.local:9428"

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - clusters
          topologyKey: kubernetes.io/hostname

tolerations:
  - key: "xata.io/workload"
    value: "dataplane"
    effect: "NoSchedule"
