apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dummy
      spec:
        template:
          spec:
            tolerations:
              - key: "xata.io/workload"
                value: "controlplane"
                effect: "NoSchedule"
  - target:
      kind: Statefulset
    patch: |-
      apiVersion: apps/v1
      kind: Statefulset
      metadata:
        name: dummy
      spec:
        template:
          spec:
            tolerations:
              - key: "xata.io/workload"
                value: "controlplane"
                effect: "NoSchedule"
  - target:
      kind: Keycloak
    patch: |-
      apiVersion: k8s.keycloak.org/v2beta1
      kind: Keycloak
      metadata:
        name: dummy
      spec:
        scheduling:
          tolerations:
            - key: "xata.io/workload"
              value: "controlplane"
              effect: "NoSchedule"
  - target:
      kind: Job
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: dummy
      spec:
        template:
          spec:
            tolerations:
              - key: "xata.io/workload"
                value: "controlplane"
                effect: "NoSchedule"
