// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute SQL query
	// (POST /sql)
	Query(ctx echo.Context, params QueryParams) error
	// WebSocket wire protocol proxy
	// (GET /v2)
	Websocket(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Query converts echo context to params.
func (w *ServerInterfaceWrapper) Query(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "Connection-String" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Connection-String")]; found {
		var ConnectionString string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Connection-String, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Connection-String", valueList[0], &ConnectionString, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Connection-String: %s", err))
		}

		params.ConnectionString = &ConnectionString
	}
	// ------------- Optional header parameter "Array-Mode" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Array-Mode")]; found {
		var ArrayMode QueryParamsArrayMode
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Array-Mode, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Array-Mode", valueList[0], &ArrayMode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Array-Mode: %s", err))
		}

		params.ArrayMode = &ArrayMode
	}
	// ------------- Optional header parameter "Raw-Text-Output" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Raw-Text-Output")]; found {
		var RawTextOutput QueryParamsRawTextOutput
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Raw-Text-Output, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Raw-Text-Output", valueList[0], &RawTextOutput, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Raw-Text-Output: %s", err))
		}

		params.RawTextOutput = &RawTextOutput
	}
	// ------------- Optional header parameter "Batch-Isolation-Level" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Isolation-Level")]; found {
		var BatchIsolationLevel QueryParamsBatchIsolationLevel
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Isolation-Level, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Isolation-Level", valueList[0], &BatchIsolationLevel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Isolation-Level: %s", err))
		}

		params.BatchIsolationLevel = &BatchIsolationLevel
	}
	// ------------- Optional header parameter "Batch-Read-Only" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Read-Only")]; found {
		var BatchReadOnly QueryParamsBatchReadOnly
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Read-Only, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Read-Only", valueList[0], &BatchReadOnly, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Read-Only: %s", err))
		}

		params.BatchReadOnly = &BatchReadOnly
	}
	// ------------- Optional header parameter "Batch-Deferrable" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Deferrable")]; found {
		var BatchDeferrable QueryParamsBatchDeferrable
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Deferrable, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Deferrable", valueList[0], &BatchDeferrable, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Deferrable: %s", err))
		}

		params.BatchDeferrable = &BatchDeferrable
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Query(ctx, params)
	return err
}

// Websocket converts echo context to params.
func (w *ServerInterfaceWrapper) Websocket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Websocket(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/sql", wrapper.Query)
	router.GET(baseURL+"/v2", wrapper.Websocket)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZbW/bOBL+K4RuP9iBX5J0ewf406aJdzeHtHmxix6wCWBaGlnclUiVpOy4hYH7EfcL",
	"75ccZkjJsi07Sdsr0C+tI1Izw3l55hnqcxCqLFcSpDXB4HNgwgQyTj/fcBsmd2ByJQ3ggwhMqEVuhZLB",
	"IChXWKw042yKu9nHAvSSwSOEBW7rBZ0g1yoHbQWQUA2mSJ2qHXG4QNKAV6KEZDYBJ72DfykdgUa5wkJG",
	"cn7SEAeD4G/99Un6/hj9WxTiRAerTmCXOQSDgGvNl8Fq1Qk0fCyEhigY/FGZ9lDtU9M/IaQXh1orvd8X",
	"tMx06ZGFsAm7UcbONIxurxjQciwgjcyuS0IVNYjceR23sdbo9mo0PhsP2wy9nuepCDm+UduEGvwBjNVC",
	"zvAAoUqLTO6qOafnTPIMmIaUW4iYVeRzkrhHmDRWcyFtk8By7YVCI275mB5ui7zgljPc/1KJYLlId+Vd",
	"0w+eMreBZWAMnzX7LRZpg0UjVegQGC6yRQIa1pawBTdMQ6402tgyoOegu0ZE0G5UkDR6sTIRl6kmNBiV",
	"zoWcPXFoIS1oydMbZYQT1pBZtILVxPFf90K67M5AgibfUvEdlE+VtSt8DI+WqZiMfKHkVMj9rsbFr3W1",
	"j/Oujt+LjMuuBh7xaVoKP5QV+V7nnidc89CCZnnNzWiyw7PtI6gwLLSGqFGNVoU95BS//rV+cWDZoIWe",
	"v7DoDMxBC7t8BqKVW1kLerMemwzv7q7vJh02+fVsfHY1aTbWYoga8o4i9zJTyW2NCGYxi4Vki0SEyfOi",
	"tdVMylxraia/YiO4gFjI/RVaesrhNsvAcgRIFmuVkUFaLVjtrXq6brcXlHB5savmzFotpoUFJotsCrqs",
	"W68Tu5jPXXI6io6VzrgNBggDr07XXsBSn4EOOsFjd6a6/mkhpD35ex3cm8y4vrzY0hyVgP9lKl+d1lW+",
	"VZGIBeiGnFnm0DU5hCIWIcv8Pp+NuYZQGKFk34Q8dSxHFhloEZJppv0c42p2jMSng73NiE/AWhJm3Iq5",
	"0zfnWqDnuynImU1eoHfTKVUYytcarXCLrDXB7J8gv5hMheR6uacSsdgOEor99ftEGhgHb7SVtY6ZiJlU",
	"lnH/xGVJ+8uTY6tW6SBryzrrktlI3K1QNmRYZU9T1VPDvLSQNRQiM0LO0qpHuMIrOTWaCsbuVjbR2LeN",
	"7PF6DlqLCBjtwdx2GWUTYZiQkZiLqODpTjeeKpUCl9TjuOaZ2U8feMpoC1jQxguHtcCSnu+w7k7wsZk6",
	"INw5B1jlRwh4GmidsL0O99x/z7iBCcdL56/1H5hfQpVlXEZPYDbtYZbPytY2Gl4Nz8fY2y7fjYZ39Ov9",
	"zcXZeIi/LoZXw/FwT5m5sWFvoa07g4+AG2OYAfvsKWm7ITXETKvFmTmjv3Ys+ZCATUBjSzKMazTBFlpC",
	"xLhxCWgQVXQBExpbXIjwWcxTAxvnriWgVotzVTSx43dVu3Iq4xhC7PjTpe8i5H+UKos0dYQB1TfBM0rY",
	"mx642GNDHEex3wqDhNmZz1oOJbrEOf6CpXEjmfQl11okIOvlJwwDibZE7UP1sYlYXO7OqT4hOlUu1lzl",
	"z7MRr6baGN1e3TlYOVSHJfKwG63miCYgKNATWp74yX8Du5RfFWAm9ZuBb4deTk9rQyvtUDJdtr85lrHW",
	"5KcTLNKfTicd1uv12s9AN3/ELZSnw6iY+R2kx0F8BThr7Pfns5pLw8MSjJ5/6UGd5uvAt8HJ7WZA3sqv",
	"Fc2JsXKAKS0PKc0cYQhMkeNo8ssjt7wnlJvUN3hZAuxfCGm/cQsLvmS5Sz/DsiK1IicKICWEVsxxfFD0",
	"ovNnDYYRFafcgBncy3vZZUdHv4/HNwjzR0esNbm5Ho1Z33xMJ23233//h7kxKQVTphjIKFfl+O09gbDu",
	"QkZjTBk2J/4DTEcq/Assyf9tOGb9+amXXrNrITTgkawKVYo/HpdMzUGz6n0vDvfd+H1HRyRGOnK40Wyc",
	"J9ABSjL0LHv986vTe4mREhaxLygdeXZzGXSCOWjjPH3SO0b3qxwkz0UwCF71jnvHWKrcJpRn6CD8P1dN",
	"UDH0idLQQ2uXgrWU5zMupEEqVzvCVHMZJj2M0tHRqJZyg6OjMvYV5rQwBKq8Hpm4yp60GbduUlE5S2EO",
	"qRdHl5g7cgiduFmjtTdxWfamDqP5FJs4tVTCQTZV0fJe4nvsn6Prd+7dHntTXX3iEcviOVTJFBwEQ7q7",
	"u4yCgWMrgYcqwqFg8MdBklHGnblCZK1J7pbNoN8vDOhBzo35JVHG9qPppN1jWFj4J7UskKHCmnLznZ6B",
	"9YGgJK+SvxzDBOpPgEfEc30pn1dGdEcODeq3CRU5L7Rogo0GHiGZ4wkdzyF8g69oBCYP8Ajj5SO11zaC",
	"2y41mLpRIIsMuyiqQcKODKTWIl9mHU9TNudpAWSje9dQ5FXhXIdx8vW219I7vuiO4dF2rwubF/bbmDte",
	"pxsTRqXulphKo9Z4fNLuNY1Su3tZvt+9wvcbDbwDHp2rLBPWAlIS/Pu9DDee5MBpyMK1oBOMQAueik9E",
	"0F4cgrLOqs8D9QpjQjINPOoiKaDO9cQR0aTutUyX/4dkedLSCGLQmmbbZ5h6Ue3+IlsfHJsEY9+oaFm2",
	"aHA8u/ZFof+ncXdTaxWHSEeNUa42GSsaRA/c1xFqK6fHxy/SrCRcxwSIz//ac3jv5tet1QMZvRnE29ow",
	"CBEzRRiCMXGRpsSkfn7hGQ5Zs/l9qcGWSznnqYiqVqQ0qy5SnTEn38+Yt8JgU0MjhLdrpx2hUa+/r4fc",
	"1wZP5NaueX38j+9nRfVV1CrFUmyrRJCdTU0tvU50g05Q6BQL39ocu/hn15FXvc8aZkLJVY9Is4UwQR7n",
	"rwepotxOR9FiTnceQbbs+sdUf7PqsrncUJgucGO7J3iUh05giizjOB5UzK4idHRBNsMTlGwyePhRDrbq",
	"BP35Ke6YQQOLfZ/PNI8wZIyvSXg9pW3CLTF14QnTPjrfu5dIssJUgLREIA3RKQ0hiDmY+ovVCOCv7o2b",
	"Atyda82OGAmhIT57VtgEpC2/+QrDEi6jFCI2F3zbMGO5tkVeiq/f52/Y3LmXhSk/LBqkhuuTdz23rFgj",
	"0Rnpxg3ufFFOVRVnbKK3H2Bq6DjBVic4ccC1NY0uhA0TVFzOP4bGn8bggEFSIUwCUQ2WNwW+4WvoREEF",
	"3cRgxAsf/LXAH7Ng165pmC9/6OJdVcY/YxyiCwEshjIrO+ygZzpUnn6s3izlNe8qHbF6WP0vAAD//wU7",
	"bJ4wIwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
