// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package cellsmock

import (
	context "context"
	clustersv1 "xata/gen/proto/clusters/v1"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CellClient is an autogenerated mock type for the CellClient type
type CellClient struct {
	mock.Mock
}

type CellClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CellClient) EXPECT() *CellClient_Expecter {
	return &CellClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *CellClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CellClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CellClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *CellClient_Expecter) Close() *CellClient_Close_Call {
	return &CellClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *CellClient_Close_Call) Run(run func()) *CellClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CellClient_Close_Call) Return(_a0 error) *CellClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

// CreatePostgresCluster provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) CreatePostgresCluster(ctx context.Context, in *clustersv1.CreatePostgresClusterRequest, opts ...grpc.CallOption) (*clustersv1.CreatePostgresClusterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.CreatePostgresClusterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.CreatePostgresClusterRequest, ...grpc.CallOption) *clustersv1.CreatePostgresClusterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.CreatePostgresClusterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.CreatePostgresClusterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_CreatePostgresCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePostgresCluster'
type CellClient_CreatePostgresCluster_Call struct {
	*mock.Call
}

// CreatePostgresCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.CreatePostgresClusterRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) CreatePostgresCluster(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_CreatePostgresCluster_Call {
	return &CellClient_CreatePostgresCluster_Call{Call: _e.mock.On("CreatePostgresCluster",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_CreatePostgresCluster_Call) Run(run func(ctx context.Context, in *clustersv1.CreatePostgresClusterRequest, opts ...grpc.CallOption)) *CellClient_CreatePostgresCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.CreatePostgresClusterRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_CreatePostgresCluster_Call) Return(_a0 *clustersv1.CreatePostgresClusterResponse, _a1 error) *CellClient_CreatePostgresCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteBranchIPFiltering provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) DeleteBranchIPFiltering(ctx context.Context, in *clustersv1.DeleteBranchIPFilteringRequest, opts ...grpc.CallOption) (*clustersv1.DeleteBranchIPFilteringResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.DeleteBranchIPFilteringResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.DeleteBranchIPFilteringRequest, ...grpc.CallOption) *clustersv1.DeleteBranchIPFilteringResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.DeleteBranchIPFilteringResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.DeleteBranchIPFilteringRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_DeleteBranchIPFiltering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranchIPFiltering'
type CellClient_DeleteBranchIPFiltering_Call struct {
	*mock.Call
}

// DeleteBranchIPFiltering is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.DeleteBranchIPFilteringRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) DeleteBranchIPFiltering(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_DeleteBranchIPFiltering_Call {
	return &CellClient_DeleteBranchIPFiltering_Call{Call: _e.mock.On("DeleteBranchIPFiltering",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_DeleteBranchIPFiltering_Call) Run(run func(ctx context.Context, in *clustersv1.DeleteBranchIPFilteringRequest, opts ...grpc.CallOption)) *CellClient_DeleteBranchIPFiltering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.DeleteBranchIPFilteringRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_DeleteBranchIPFiltering_Call) Return(_a0 *clustersv1.DeleteBranchIPFilteringResponse, _a1 error) *CellClient_DeleteBranchIPFiltering_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeletePostgresCluster provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) DeletePostgresCluster(ctx context.Context, in *clustersv1.DeletePostgresClusterRequest, opts ...grpc.CallOption) (*clustersv1.DeletePostgresClusterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.DeletePostgresClusterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.DeletePostgresClusterRequest, ...grpc.CallOption) *clustersv1.DeletePostgresClusterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.DeletePostgresClusterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.DeletePostgresClusterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_DeletePostgresCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePostgresCluster'
type CellClient_DeletePostgresCluster_Call struct {
	*mock.Call
}

// DeletePostgresCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.DeletePostgresClusterRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) DeletePostgresCluster(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_DeletePostgresCluster_Call {
	return &CellClient_DeletePostgresCluster_Call{Call: _e.mock.On("DeletePostgresCluster",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_DeletePostgresCluster_Call) Run(run func(ctx context.Context, in *clustersv1.DeletePostgresClusterRequest, opts ...grpc.CallOption)) *CellClient_DeletePostgresCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.DeletePostgresClusterRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_DeletePostgresCluster_Call) Return(_a0 *clustersv1.DeletePostgresClusterResponse, _a1 error) *CellClient_DeletePostgresCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeregisterPostgresCluster provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) DeregisterPostgresCluster(ctx context.Context, in *clustersv1.DeregisterPostgresClusterRequest, opts ...grpc.CallOption) (*clustersv1.DeregisterPostgresClusterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.DeregisterPostgresClusterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.DeregisterPostgresClusterRequest, ...grpc.CallOption) *clustersv1.DeregisterPostgresClusterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.DeregisterPostgresClusterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.DeregisterPostgresClusterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_DeregisterPostgresCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeregisterPostgresCluster'
type CellClient_DeregisterPostgresCluster_Call struct {
	*mock.Call
}

// DeregisterPostgresCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.DeregisterPostgresClusterRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) DeregisterPostgresCluster(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_DeregisterPostgresCluster_Call {
	return &CellClient_DeregisterPostgresCluster_Call{Call: _e.mock.On("DeregisterPostgresCluster",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_DeregisterPostgresCluster_Call) Run(run func(ctx context.Context, in *clustersv1.DeregisterPostgresClusterRequest, opts ...grpc.CallOption)) *CellClient_DeregisterPostgresCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.DeregisterPostgresClusterRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_DeregisterPostgresCluster_Call) Return(_a0 *clustersv1.DeregisterPostgresClusterResponse, _a1 error) *CellClient_DeregisterPostgresCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DescribePostgresCluster provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) DescribePostgresCluster(ctx context.Context, in *clustersv1.DescribePostgresClusterRequest, opts ...grpc.CallOption) (*clustersv1.DescribePostgresClusterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.DescribePostgresClusterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.DescribePostgresClusterRequest, ...grpc.CallOption) *clustersv1.DescribePostgresClusterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.DescribePostgresClusterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.DescribePostgresClusterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_DescribePostgresCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribePostgresCluster'
type CellClient_DescribePostgresCluster_Call struct {
	*mock.Call
}

// DescribePostgresCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.DescribePostgresClusterRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) DescribePostgresCluster(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_DescribePostgresCluster_Call {
	return &CellClient_DescribePostgresCluster_Call{Call: _e.mock.On("DescribePostgresCluster",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_DescribePostgresCluster_Call) Run(run func(ctx context.Context, in *clustersv1.DescribePostgresClusterRequest, opts ...grpc.CallOption)) *CellClient_DescribePostgresCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.DescribePostgresClusterRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_DescribePostgresCluster_Call) Return(_a0 *clustersv1.DescribePostgresClusterResponse, _a1 error) *CellClient_DescribePostgresCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetBranchIPFiltering provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) GetBranchIPFiltering(ctx context.Context, in *clustersv1.GetBranchIPFilteringRequest, opts ...grpc.CallOption) (*clustersv1.GetBranchIPFilteringResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.GetBranchIPFilteringResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.GetBranchIPFilteringRequest, ...grpc.CallOption) *clustersv1.GetBranchIPFilteringResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.GetBranchIPFilteringResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.GetBranchIPFilteringRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_GetBranchIPFiltering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranchIPFiltering'
type CellClient_GetBranchIPFiltering_Call struct {
	*mock.Call
}

// GetBranchIPFiltering is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.GetBranchIPFilteringRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) GetBranchIPFiltering(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_GetBranchIPFiltering_Call {
	return &CellClient_GetBranchIPFiltering_Call{Call: _e.mock.On("GetBranchIPFiltering",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_GetBranchIPFiltering_Call) Run(run func(ctx context.Context, in *clustersv1.GetBranchIPFilteringRequest, opts ...grpc.CallOption)) *CellClient_GetBranchIPFiltering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.GetBranchIPFilteringRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_GetBranchIPFiltering_Call) Return(_a0 *clustersv1.GetBranchIPFilteringResponse, _a1 error) *CellClient_GetBranchIPFiltering_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetBranchLogs provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) GetBranchLogs(ctx context.Context, in *clustersv1.GetBranchLogsRequest, opts ...grpc.CallOption) (*clustersv1.GetBranchLogsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.GetBranchLogsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.GetBranchLogsRequest, ...grpc.CallOption) *clustersv1.GetBranchLogsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.GetBranchLogsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.GetBranchLogsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_GetBranchLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranchLogs'
type CellClient_GetBranchLogs_Call struct {
	*mock.Call
}

// GetBranchLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.GetBranchLogsRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) GetBranchLogs(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_GetBranchLogs_Call {
	return &CellClient_GetBranchLogs_Call{Call: _e.mock.On("GetBranchLogs",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_GetBranchLogs_Call) Run(run func(ctx context.Context, in *clustersv1.GetBranchLogsRequest, opts ...grpc.CallOption)) *CellClient_GetBranchLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.GetBranchLogsRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_GetBranchLogs_Call) Return(_a0 *clustersv1.GetBranchLogsResponse, _a1 error) *CellClient_GetBranchLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetBranchMetrics provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) GetBranchMetrics(ctx context.Context, in *clustersv1.GetBranchMetricsRequest, opts ...grpc.CallOption) (*clustersv1.GetBranchMetricsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.GetBranchMetricsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.GetBranchMetricsRequest, ...grpc.CallOption) *clustersv1.GetBranchMetricsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.GetBranchMetricsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.GetBranchMetricsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_GetBranchMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranchMetrics'
type CellClient_GetBranchMetrics_Call struct {
	*mock.Call
}

// GetBranchMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.GetBranchMetricsRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) GetBranchMetrics(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_GetBranchMetrics_Call {
	return &CellClient_GetBranchMetrics_Call{Call: _e.mock.On("GetBranchMetrics",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_GetBranchMetrics_Call) Run(run func(ctx context.Context, in *clustersv1.GetBranchMetricsRequest, opts ...grpc.CallOption)) *CellClient_GetBranchMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.GetBranchMetricsRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_GetBranchMetrics_Call) Return(_a0 *clustersv1.GetBranchMetricsResponse, _a1 error) *CellClient_GetBranchMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetCellUtilization provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) GetCellUtilization(ctx context.Context, in *clustersv1.GetCellUtilizationRequest, opts ...grpc.CallOption) (*clustersv1.GetCellUtilizationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.GetCellUtilizationResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.GetCellUtilizationRequest, ...grpc.CallOption) *clustersv1.GetCellUtilizationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.GetCellUtilizationResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.GetCellUtilizationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_GetCellUtilization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCellUtilization'
type CellClient_GetCellUtilization_Call struct {
	*mock.Call
}

// GetCellUtilization is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.GetCellUtilizationRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) GetCellUtilization(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_GetCellUtilization_Call {
	return &CellClient_GetCellUtilization_Call{Call: _e.mock.On("GetCellUtilization",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_GetCellUtilization_Call) Run(run func(ctx context.Context, in *clustersv1.GetCellUtilizationRequest, opts ...grpc.CallOption)) *CellClient_GetCellUtilization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.GetCellUtilizationRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_GetCellUtilization_Call) Return(_a0 *clustersv1.GetCellUtilizationResponse, _a1 error) *CellClient_GetCellUtilization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetObjectStore provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) GetObjectStore(ctx context.Context, in *clustersv1.GetObjectStoreRequest, opts ...grpc.CallOption) (*clustersv1.GetObjectStoreResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.GetObjectStoreResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.GetObjectStoreRequest, ...grpc.CallOption) *clustersv1.GetObjectStoreResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.GetObjectStoreResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.GetObjectStoreRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_GetObjectStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectStore'
type CellClient_GetObjectStore_Call struct {
	*mock.Call
}

// GetObjectStore is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.GetObjectStoreRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) GetObjectStore(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_GetObjectStore_Call {
	return &CellClient_GetObjectStore_Call{Call: _e.mock.On("GetObjectStore",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_GetObjectStore_Call) Run(run func(ctx context.Context, in *clustersv1.GetObjectStoreRequest, opts ...grpc.CallOption)) *CellClient_GetObjectStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.GetObjectStoreRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_GetObjectStore_Call) Return(_a0 *clustersv1.GetObjectStoreResponse, _a1 error) *CellClient_GetObjectStore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetPostgresClusterCredentials provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) GetPostgresClusterCredentials(ctx context.Context, in *clustersv1.GetPostgresClusterCredentialsRequest, opts ...grpc.CallOption) (*clustersv1.GetPostgresClusterCredentialsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.GetPostgresClusterCredentialsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.GetPostgresClusterCredentialsRequest, ...grpc.CallOption) *clustersv1.GetPostgresClusterCredentialsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.GetPostgresClusterCredentialsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.GetPostgresClusterCredentialsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_GetPostgresClusterCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostgresClusterCredentials'
type CellClient_GetPostgresClusterCredentials_Call struct {
	*mock.Call
}

// GetPostgresClusterCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.GetPostgresClusterCredentialsRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) GetPostgresClusterCredentials(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_GetPostgresClusterCredentials_Call {
	return &CellClient_GetPostgresClusterCredentials_Call{Call: _e.mock.On("GetPostgresClusterCredentials",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_GetPostgresClusterCredentials_Call) Run(run func(ctx context.Context, in *clustersv1.GetPostgresClusterCredentialsRequest, opts ...grpc.CallOption)) *CellClient_GetPostgresClusterCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.GetPostgresClusterCredentialsRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_GetPostgresClusterCredentials_Call) Return(_a0 *clustersv1.GetPostgresClusterCredentialsResponse, _a1 error) *CellClient_GetPostgresClusterCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RegisterPostgresCluster provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) RegisterPostgresCluster(ctx context.Context, in *clustersv1.RegisterPostgresClusterRequest, opts ...grpc.CallOption) (*clustersv1.RegisterPostgresClusterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.RegisterPostgresClusterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.RegisterPostgresClusterRequest, ...grpc.CallOption) *clustersv1.RegisterPostgresClusterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.RegisterPostgresClusterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.RegisterPostgresClusterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_RegisterPostgresCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPostgresCluster'
type CellClient_RegisterPostgresCluster_Call struct {
	*mock.Call
}

// RegisterPostgresCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.RegisterPostgresClusterRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) RegisterPostgresCluster(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_RegisterPostgresCluster_Call {
	return &CellClient_RegisterPostgresCluster_Call{Call: _e.mock.On("RegisterPostgresCluster",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_RegisterPostgresCluster_Call) Run(run func(ctx context.Context, in *clustersv1.RegisterPostgresClusterRequest, opts ...grpc.CallOption)) *CellClient_RegisterPostgresCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.RegisterPostgresClusterRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_RegisterPostgresCluster_Call) Return(_a0 *clustersv1.RegisterPostgresClusterResponse, _a1 error) *CellClient_RegisterPostgresCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RotatePostgresClusterCredentials provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) RotatePostgresClusterCredentials(ctx context.Context, in *clustersv1.RotatePostgresClusterCredentialsRequest, opts ...grpc.CallOption) (*clustersv1.RotatePostgresClusterCredentialsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.RotatePostgresClusterCredentialsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.RotatePostgresClusterCredentialsRequest, ...grpc.CallOption) *clustersv1.RotatePostgresClusterCredentialsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.RotatePostgresClusterCredentialsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.RotatePostgresClusterCredentialsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_RotatePostgresClusterCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotatePostgresClusterCredentials'
type CellClient_RotatePostgresClusterCredentials_Call struct {
	*mock.Call
}

// RotatePostgresClusterCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.RotatePostgresClusterCredentialsRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) RotatePostgresClusterCredentials(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_RotatePostgresClusterCredentials_Call {
	return &CellClient_RotatePostgresClusterCredentials_Call{Call: _e.mock.On("RotatePostgresClusterCredentials",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_RotatePostgresClusterCredentials_Call) Run(run func(ctx context.Context, in *clustersv1.RotatePostgresClusterCredentialsRequest, opts ...grpc.CallOption)) *CellClient_RotatePostgresClusterCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.RotatePostgresClusterCredentialsRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_RotatePostgresClusterCredentials_Call) Return(_a0 *clustersv1.RotatePostgresClusterCredentialsResponse, _a1 error) *CellClient_RotatePostgresClusterCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetBranchIPFiltering provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) SetBranchIPFiltering(ctx context.Context, in *clustersv1.SetBranchIPFilteringRequest, opts ...grpc.CallOption) (*clustersv1.SetBranchIPFilteringResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.SetBranchIPFilteringResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.SetBranchIPFilteringRequest, ...grpc.CallOption) *clustersv1.SetBranchIPFilteringResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.SetBranchIPFilteringResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.SetBranchIPFilteringRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_SetBranchIPFiltering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBranchIPFiltering'
type CellClient_SetBranchIPFiltering_Call struct {
	*mock.Call
}

// SetBranchIPFiltering is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.SetBranchIPFilteringRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) SetBranchIPFiltering(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_SetBranchIPFiltering_Call {
	return &CellClient_SetBranchIPFiltering_Call{Call: _e.mock.On("SetBranchIPFiltering",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_SetBranchIPFiltering_Call) Run(run func(ctx context.Context, in *clustersv1.SetBranchIPFilteringRequest, opts ...grpc.CallOption)) *CellClient_SetBranchIPFiltering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.SetBranchIPFilteringRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_SetBranchIPFiltering_Call) Return(_a0 *clustersv1.SetBranchIPFilteringResponse, _a1 error) *CellClient_SetBranchIPFiltering_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetBranchesIPFiltering provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) SetBranchesIPFiltering(ctx context.Context, in *clustersv1.SetBranchesIPFilteringRequest, opts ...grpc.CallOption) (*clustersv1.SetBranchesIPFilteringResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.SetBranchesIPFilteringResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.SetBranchesIPFilteringRequest, ...grpc.CallOption) *clustersv1.SetBranchesIPFilteringResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.SetBranchesIPFilteringResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.SetBranchesIPFilteringRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_SetBranchesIPFiltering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBranchesIPFiltering'
type CellClient_SetBranchesIPFiltering_Call struct {
	*mock.Call
}

// SetBranchesIPFiltering is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.SetBranchesIPFilteringRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) SetBranchesIPFiltering(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_SetBranchesIPFiltering_Call {
	return &CellClient_SetBranchesIPFiltering_Call{Call: _e.mock.On("SetBranchesIPFiltering",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_SetBranchesIPFiltering_Call) Run(run func(ctx context.Context, in *clustersv1.SetBranchesIPFilteringRequest, opts ...grpc.CallOption)) *CellClient_SetBranchesIPFiltering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.SetBranchesIPFilteringRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_SetBranchesIPFiltering_Call) Return(_a0 *clustersv1.SetBranchesIPFilteringResponse, _a1 error) *CellClient_SetBranchesIPFiltering_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdatePostgresCluster provides a mock function with given fields: ctx, in, opts
func (_m *CellClient) UpdatePostgresCluster(ctx context.Context, in *clustersv1.UpdatePostgresClusterRequest, opts ...grpc.CallOption) (*clustersv1.UpdatePostgresClusterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *clustersv1.UpdatePostgresClusterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *clustersv1.UpdatePostgresClusterRequest, ...grpc.CallOption) *clustersv1.UpdatePostgresClusterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clustersv1.UpdatePostgresClusterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *clustersv1.UpdatePostgresClusterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CellClient_UpdatePostgresCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePostgresCluster'
type CellClient_UpdatePostgresCluster_Call struct {
	*mock.Call
}

// UpdatePostgresCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - in *clustersv1.UpdatePostgresClusterRequest
//   - opts ...grpc.CallOption
func (_e *CellClient_Expecter) UpdatePostgresCluster(ctx interface{}, in interface{}, opts ...interface{}) *CellClient_UpdatePostgresCluster_Call {
	return &CellClient_UpdatePostgresCluster_Call{Call: _e.mock.On("UpdatePostgresCluster",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CellClient_UpdatePostgresCluster_Call) Run(run func(ctx context.Context, in *clustersv1.UpdatePostgresClusterRequest, opts ...grpc.CallOption)) *CellClient_UpdatePostgresCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*clustersv1.UpdatePostgresClusterRequest), variadicArgs...)
	})
	return _c
}

func (_c *CellClient_UpdatePostgresCluster_Call) Return(_a0 *clustersv1.UpdatePostgresClusterResponse, _a1 error) *CellClient_UpdatePostgresCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewCellClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewCellClient creates a new instance of CellClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCellClient(t mockConstructorTestingTNewCellClient) *CellClient {
	mock := &CellClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
